// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:00:37.7071836Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings;

public static unsafe class GL15
{
    #region Constants
    public const int GL_SRC2_ALPHA = 0x0000858A;
    public const int GL_SRC0_ALPHA = 0x00008588;
    public const int GL_SRC2_RGB = 0x00008582;
    public const int GL_SRC1_RGB = 0x00008581;
    public const int GL_SRC0_RGB = 0x00008580;
    public const int GL_FOG_COORD_ARRAY_BUFFER_BINDING = 0x0000889D;
    public const int GL_FOG_COORD_ARRAY = 0x00008457;
    public const int GL_FOG_COORD_ARRAY_POINTER = 0x00008456;
    public const int GL_FOG_COORD_ARRAY_STRIDE = 0x00008455;
    public const int GL_FOG_COORD_ARRAY_TYPE = 0x00008454;
    public const int GL_CURRENT_FOG_COORD = 0x00008453;
    public const int GL_FOG_COORD = 0x00008451;
    public const int GL_FOG_COORD_SRC = 0x00008450;
    public const int GL_WEIGHT_ARRAY_BUFFER_BINDING = 0x0000889E;
    public const int GL_FOG_COORDINATE_ARRAY_BUFFER_BINDING = 0x0000889D;
    public const int GL_SECONDARY_COLOR_ARRAY_BUFFER_BINDING = 0x0000889C;
    public const int GL_EDGE_FLAG_ARRAY_BUFFER_BINDING = 0x0000889B;
    public const int GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING = 0x0000889A;
    public const int GL_INDEX_ARRAY_BUFFER_BINDING = 0x00008899;
    public const int GL_COLOR_ARRAY_BUFFER_BINDING = 0x00008898;
    public const int GL_NORMAL_ARRAY_BUFFER_BINDING = 0x00008897;
    public const int GL_VERTEX_ARRAY_BUFFER_BINDING = 0x00008896;
    public const int GL_SRC1_ALPHA = 0x00008589;
    public const int GL_SAMPLES_PASSED = 0x00008914;
    public const int GL_DYNAMIC_COPY = 0x000088EA;
    public const int GL_DYNAMIC_READ = 0x000088E9;
    public const int GL_DYNAMIC_DRAW = 0x000088E8;
    public const int GL_STATIC_COPY = 0x000088E6;
    public const int GL_STATIC_READ = 0x000088E5;
    public const int GL_STATIC_DRAW = 0x000088E4;
    public const int GL_STREAM_COPY = 0x000088E2;
    public const int GL_STREAM_READ = 0x000088E1;
    public const int GL_STREAM_DRAW = 0x000088E0;
    public const int GL_BUFFER_MAP_POINTER = 0x000088BD;
    public const int GL_BUFFER_MAPPED = 0x000088BC;
    public const int GL_BUFFER_ACCESS = 0x000088BB;
    public const int GL_READ_WRITE = 0x000088BA;
    public const int GL_WRITE_ONLY = 0x000088B9;
    public const int GL_READ_ONLY = 0x000088B8;
    public const int GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = 0x0000889F;
    public const int GL_ELEMENT_ARRAY_BUFFER_BINDING = 0x00008895;
    public const int GL_ARRAY_BUFFER_BINDING = 0x00008894;
    public const int GL_ELEMENT_ARRAY_BUFFER = 0x00008893;
    public const int GL_ARRAY_BUFFER = 0x00008892;
    public const int GL_QUERY_RESULT_AVAILABLE = 0x00008867;
    public const int GL_QUERY_RESULT = 0x00008866;
    public const int GL_CURRENT_QUERY = 0x00008865;
    public const int GL_QUERY_COUNTER_BITS = 0x00008864;
    public const int GL_BUFFER_USAGE = 0x00008765;
    public const int GL_BUFFER_SIZE = 0x00008764;
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, uint, void**, void> _glGetBufferPointerv = null;
    internal static delegate* unmanaged<uint, uint, int*, void> _glGetBufferParameteriv = null;
    internal static delegate* unmanaged<uint, bool> _glUnmapBuffer = null;
    internal static delegate* unmanaged<uint, uint, void*> _glMapBuffer = null;
    internal static delegate* unmanaged<uint, nint, nint, void*, void> _glGetBufferSubData = null;
    internal static delegate* unmanaged<uint, nint, nint, void*, void> _glBufferSubData = null;
    internal static delegate* unmanaged<uint, nint, void*, uint, void> _glBufferData = null;
    internal static delegate* unmanaged<uint, bool> _glIsBuffer = null;
    internal static delegate* unmanaged<int, uint*, void> _glGenBuffers = null;
    internal static delegate* unmanaged<int, uint*, void> _glDeleteBuffers = null;
    internal static delegate* unmanaged<uint, uint, void> _glBindBuffer = null;
    internal static delegate* unmanaged<uint, uint, uint*, void> _glGetQueryObjectuiv = null;
    internal static delegate* unmanaged<uint, uint, int*, void> _glGetQueryObjectiv = null;
    internal static delegate* unmanaged<uint, uint, int*, void> _glGetQueryiv = null;
    internal static delegate* unmanaged<uint, void> _glEndQuery = null;
    internal static delegate* unmanaged<uint, uint, void> _glBeginQuery = null;
    internal static delegate* unmanaged<uint, bool> _glIsQuery = null;
    internal static delegate* unmanaged<int, uint*, void> _glDeleteQueries = null;
    internal static delegate* unmanaged<int, uint*, void> _glGenQueries = null;

    internal static void Load()
    {
        _glGetBufferPointerv = (delegate* unmanaged<uint, uint, void**, void>)QuickGL.GetGLProcAddress("glGetBufferPointerv");
        _glGetBufferParameteriv = (delegate* unmanaged<uint, uint, int*, void>)QuickGL.GetGLProcAddress("glGetBufferParameteriv");
        _glUnmapBuffer = (delegate* unmanaged<uint, bool>)QuickGL.GetGLProcAddress("glUnmapBuffer");
        _glMapBuffer = (delegate* unmanaged<uint, uint, void*>)QuickGL.GetGLProcAddress("glMapBuffer");
        _glGetBufferSubData = (delegate* unmanaged<uint, nint, nint, void*, void>)QuickGL.GetGLProcAddress("glGetBufferSubData");
        _glBufferSubData = (delegate* unmanaged<uint, nint, nint, void*, void>)QuickGL.GetGLProcAddress("glBufferSubData");
        _glBufferData = (delegate* unmanaged<uint, nint, void*, uint, void>)QuickGL.GetGLProcAddress("glBufferData");
        _glIsBuffer = (delegate* unmanaged<uint, bool>)QuickGL.GetGLProcAddress("glIsBuffer");
        _glGenBuffers = (delegate* unmanaged<int, uint*, void>)QuickGL.GetGLProcAddress("glGenBuffers");
        _glDeleteBuffers = (delegate* unmanaged<int, uint*, void>)QuickGL.GetGLProcAddress("glDeleteBuffers");
        _glBindBuffer = (delegate* unmanaged<uint, uint, void>)QuickGL.GetGLProcAddress("glBindBuffer");
        _glGetQueryObjectuiv = (delegate* unmanaged<uint, uint, uint*, void>)QuickGL.GetGLProcAddress("glGetQueryObjectuiv");
        _glGetQueryObjectiv = (delegate* unmanaged<uint, uint, int*, void>)QuickGL.GetGLProcAddress("glGetQueryObjectiv");
        _glGetQueryiv = (delegate* unmanaged<uint, uint, int*, void>)QuickGL.GetGLProcAddress("glGetQueryiv");
        _glEndQuery = (delegate* unmanaged<uint, void>)QuickGL.GetGLProcAddress("glEndQuery");
        _glBeginQuery = (delegate* unmanaged<uint, uint, void>)QuickGL.GetGLProcAddress("glBeginQuery");
        _glIsQuery = (delegate* unmanaged<uint, bool>)QuickGL.GetGLProcAddress("glIsQuery");
        _glDeleteQueries = (delegate* unmanaged<int, uint*, void>)QuickGL.GetGLProcAddress("glDeleteQueries");
        _glGenQueries = (delegate* unmanaged<int, uint*, void>)QuickGL.GetGLProcAddress("glGenQueries");
    }

    internal static void Unload()
    {
        _glGetBufferPointerv = null;
        _glGetBufferParameteriv = null;
        _glUnmapBuffer = null;
        _glMapBuffer = null;
        _glGetBufferSubData = null;
        _glBufferSubData = null;
        _glBufferData = null;
        _glIsBuffer = null;
        _glGenBuffers = null;
        _glDeleteBuffers = null;
        _glBindBuffer = null;
        _glGetQueryObjectuiv = null;
        _glGetQueryObjectiv = null;
        _glGetQueryiv = null;
        _glEndQuery = null;
        _glBeginQuery = null;
        _glIsQuery = null;
        _glDeleteQueries = null;
        _glGenQueries = null;
    }
    #endregion

    #region Function wrappers
    public static void glGetBufferPointerv(uint target, uint pname, void** @params) { QGLFeature.VerifyFunc((nint)_glGetBufferPointerv); _glGetBufferPointerv(target, pname, @params); }
    public static void glGetBufferParameteriv(uint target, uint pname, int* @params) { QGLFeature.VerifyFunc((nint)_glGetBufferParameteriv); _glGetBufferParameteriv(target, pname, @params); }
    public static bool glUnmapBuffer(uint target) { QGLFeature.VerifyFunc((nint)_glUnmapBuffer); return _glUnmapBuffer(target); }
    public static void* glMapBuffer(uint target, uint access) { QGLFeature.VerifyFunc((nint)_glMapBuffer); return _glMapBuffer(target, access); }
    public static void glGetBufferSubData(uint target, nint offset, nint size, void* data) { QGLFeature.VerifyFunc((nint)_glGetBufferSubData); _glGetBufferSubData(target, offset, size, data); }
    public static void glBufferSubData(uint target, nint offset, nint size, void* data) { QGLFeature.VerifyFunc((nint)_glBufferSubData); _glBufferSubData(target, offset, size, data); }
    public static void glBufferData(uint target, nint size, void* data, uint usage) { QGLFeature.VerifyFunc((nint)_glBufferData); _glBufferData(target, size, data, usage); }
    public static bool glIsBuffer(uint buffer) { QGLFeature.VerifyFunc((nint)_glIsBuffer); return _glIsBuffer(buffer); }
    public static void glGenBuffers(int n, uint* buffers) { QGLFeature.VerifyFunc((nint)_glGenBuffers); _glGenBuffers(n, buffers); }
    public static void glDeleteBuffers(int n, uint* buffers) { QGLFeature.VerifyFunc((nint)_glDeleteBuffers); _glDeleteBuffers(n, buffers); }
    public static void glBindBuffer(uint target, uint buffer) { QGLFeature.VerifyFunc((nint)_glBindBuffer); _glBindBuffer(target, buffer); }
    public static void glGetQueryObjectuiv(uint id, uint pname, uint* @params) { QGLFeature.VerifyFunc((nint)_glGetQueryObjectuiv); _glGetQueryObjectuiv(id, pname, @params); }
    public static void glGetQueryObjectiv(uint id, uint pname, int* @params) { QGLFeature.VerifyFunc((nint)_glGetQueryObjectiv); _glGetQueryObjectiv(id, pname, @params); }
    public static void glGetQueryiv(uint target, uint pname, int* @params) { QGLFeature.VerifyFunc((nint)_glGetQueryiv); _glGetQueryiv(target, pname, @params); }
    public static void glEndQuery(uint target) { QGLFeature.VerifyFunc((nint)_glEndQuery); _glEndQuery(target); }
    public static void glBeginQuery(uint target, uint id) { QGLFeature.VerifyFunc((nint)_glBeginQuery); _glBeginQuery(target, id); }
    public static bool glIsQuery(uint id) { QGLFeature.VerifyFunc((nint)_glIsQuery); return _glIsQuery(id); }
    public static void glDeleteQueries(int n, uint* ids) { QGLFeature.VerifyFunc((nint)_glDeleteQueries); _glDeleteQueries(n, ids); }
    public static void glGenQueries(int n, uint* ids) { QGLFeature.VerifyFunc((nint)_glGenQueries); _glGenQueries(n, ids); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_VERSION_1_5", false, false);
}
