// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T20:04:55.6664792Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings;

public static unsafe class GL43
{
    #region Constants
    public const int GL_NUM_SHADING_LANGUAGE_VERSIONS = 0x000082E9;
    public const int GL_VERTEX_ATTRIB_ARRAY_LONG = 0x0000874E;
    public const int GL_COMPRESSED_RGB8_ETC2 = 0x00009274;
    public const int GL_COMPRESSED_SRGB8_ETC2 = 0x00009275;
    public const int GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x00009276;
    public const int GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x00009277;
    public const int GL_COMPRESSED_RGBA8_ETC2_EAC = 0x00009278;
    public const int GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC = 0x00009279;
    public const int GL_COMPRESSED_R11_EAC = 0x00009270;
    public const int GL_COMPRESSED_SIGNED_R11_EAC = 0x00009271;
    public const int GL_COMPRESSED_RG11_EAC = 0x00009272;
    public const int GL_COMPRESSED_SIGNED_RG11_EAC = 0x00009273;
    public const int GL_PRIMITIVE_RESTART_FIXED_INDEX = 0x00008D69;
    public const int GL_ANY_SAMPLES_PASSED_CONSERVATIVE = 0x00008D6A;
    public const int GL_MAX_ELEMENT_INDEX = 0x00008D6B;
    public const int GL_COMPUTE_SHADER = 0x000091B9;
    public const int GL_MAX_COMPUTE_UNIFORM_BLOCKS = 0x000091BB;
    public const int GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS = 0x000091BC;
    public const int GL_MAX_COMPUTE_IMAGE_UNIFORMS = 0x000091BD;
    public const int GL_MAX_COMPUTE_SHARED_MEMORY_SIZE = 0x00008262;
    public const int GL_MAX_COMPUTE_UNIFORM_COMPONENTS = 0x00008263;
    public const int GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS = 0x00008264;
    public const int GL_MAX_COMPUTE_ATOMIC_COUNTERS = 0x00008265;
    public const int GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS = 0x00008266;
    public const int GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS = 0x000090EB;
    public const int GL_MAX_COMPUTE_WORK_GROUP_COUNT = 0x000091BE;
    public const int GL_MAX_COMPUTE_WORK_GROUP_SIZE = 0x000091BF;
    public const int GL_COMPUTE_WORK_GROUP_SIZE = 0x00008267;
    public const int GL_UNIFORM_BLOCK_REFERENCED_BY_COMPUTE_SHADER = 0x000090EC;
    public const int GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_COMPUTE_SHADER = 0x000090ED;
    public const int GL_DISPATCH_INDIRECT_BUFFER = 0x000090EE;
    public const int GL_DISPATCH_INDIRECT_BUFFER_BINDING = 0x000090EF;
    public const int GL_COMPUTE_SHADER_BIT = 0x00000020;
    public const int GL_DEBUG_OUTPUT_SYNCHRONOUS = 0x00008242;
    public const int GL_DEBUG_NEXT_LOGGED_MESSAGE_LENGTH = 0x00008243;
    public const int GL_DEBUG_CALLBACK_FUNCTION = 0x00008244;
    public const int GL_DEBUG_CALLBACK_USER_PARAM = 0x00008245;
    public const int GL_DEBUG_SOURCE_API = 0x00008246;
    public const int GL_DEBUG_SOURCE_WINDOW_SYSTEM = 0x00008247;
    public const int GL_DEBUG_SOURCE_SHADER_COMPILER = 0x00008248;
    public const int GL_DEBUG_SOURCE_THIRD_PARTY = 0x00008249;
    public const int GL_DEBUG_SOURCE_APPLICATION = 0x0000824A;
    public const int GL_DEBUG_SOURCE_OTHER = 0x0000824B;
    public const int GL_DEBUG_TYPE_ERROR = 0x0000824C;
    public const int GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR = 0x0000824D;
    public const int GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR = 0x0000824E;
    public const int GL_DEBUG_TYPE_PORTABILITY = 0x0000824F;
    public const int GL_DEBUG_TYPE_PERFORMANCE = 0x00008250;
    public const int GL_DEBUG_TYPE_OTHER = 0x00008251;
    public const int GL_MAX_DEBUG_MESSAGE_LENGTH = 0x00009143;
    public const int GL_MAX_DEBUG_LOGGED_MESSAGES = 0x00009144;
    public const int GL_DEBUG_LOGGED_MESSAGES = 0x00009145;
    public const int GL_DEBUG_SEVERITY_HIGH = 0x00009146;
    public const int GL_DEBUG_SEVERITY_MEDIUM = 0x00009147;
    public const int GL_DEBUG_SEVERITY_LOW = 0x00009148;
    public const int GL_DEBUG_TYPE_MARKER = 0x00008268;
    public const int GL_DEBUG_TYPE_PUSH_GROUP = 0x00008269;
    public const int GL_DEBUG_TYPE_POP_GROUP = 0x0000826A;
    public const int GL_DEBUG_SEVERITY_NOTIFICATION = 0x0000826B;
    public const int GL_MAX_DEBUG_GROUP_STACK_DEPTH = 0x0000826C;
    public const int GL_DEBUG_GROUP_STACK_DEPTH = 0x0000826D;
    public const int GL_BUFFER = 0x000082E0;
    public const int GL_SHADER = 0x000082E1;
    public const int GL_PROGRAM = 0x000082E2;
    public const int GL_VERTEX_ARRAY = 0x00008074;
    public const int GL_QUERY = 0x000082E3;
    public const int GL_PROGRAM_PIPELINE = 0x000082E4;
    public const int GL_SAMPLER = 0x000082E6;
    public const int GL_MAX_LABEL_LENGTH = 0x000082E8;
    public const int GL_DEBUG_OUTPUT = 0x000092E0;
    public const int GL_CONTEXT_FLAG_DEBUG_BIT = 0x00000002;
    public const int GL_MAX_UNIFORM_LOCATIONS = 0x0000826E;
    public const int GL_FRAMEBUFFER_DEFAULT_WIDTH = 0x00009310;
    public const int GL_FRAMEBUFFER_DEFAULT_HEIGHT = 0x00009311;
    public const int GL_FRAMEBUFFER_DEFAULT_LAYERS = 0x00009312;
    public const int GL_FRAMEBUFFER_DEFAULT_SAMPLES = 0x00009313;
    public const int GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS = 0x00009314;
    public const int GL_MAX_FRAMEBUFFER_WIDTH = 0x00009315;
    public const int GL_MAX_FRAMEBUFFER_HEIGHT = 0x00009316;
    public const int GL_MAX_FRAMEBUFFER_LAYERS = 0x00009317;
    public const int GL_MAX_FRAMEBUFFER_SAMPLES = 0x00009318;
    public const int GL_INTERNALFORMAT_SUPPORTED = 0x0000826F;
    public const int GL_INTERNALFORMAT_PREFERRED = 0x00008270;
    public const int GL_INTERNALFORMAT_RED_SIZE = 0x00008271;
    public const int GL_INTERNALFORMAT_GREEN_SIZE = 0x00008272;
    public const int GL_INTERNALFORMAT_BLUE_SIZE = 0x00008273;
    public const int GL_INTERNALFORMAT_ALPHA_SIZE = 0x00008274;
    public const int GL_INTERNALFORMAT_DEPTH_SIZE = 0x00008275;
    public const int GL_INTERNALFORMAT_STENCIL_SIZE = 0x00008276;
    public const int GL_INTERNALFORMAT_SHARED_SIZE = 0x00008277;
    public const int GL_INTERNALFORMAT_RED_TYPE = 0x00008278;
    public const int GL_INTERNALFORMAT_GREEN_TYPE = 0x00008279;
    public const int GL_INTERNALFORMAT_BLUE_TYPE = 0x0000827A;
    public const int GL_INTERNALFORMAT_ALPHA_TYPE = 0x0000827B;
    public const int GL_INTERNALFORMAT_DEPTH_TYPE = 0x0000827C;
    public const int GL_INTERNALFORMAT_STENCIL_TYPE = 0x0000827D;
    public const int GL_MAX_WIDTH = 0x0000827E;
    public const int GL_MAX_HEIGHT = 0x0000827F;
    public const int GL_MAX_DEPTH = 0x00008280;
    public const int GL_MAX_LAYERS = 0x00008281;
    public const int GL_MAX_COMBINED_DIMENSIONS = 0x00008282;
    public const int GL_COLOR_COMPONENTS = 0x00008283;
    public const int GL_DEPTH_COMPONENTS = 0x00008284;
    public const int GL_STENCIL_COMPONENTS = 0x00008285;
    public const int GL_COLOR_RENDERABLE = 0x00008286;
    public const int GL_DEPTH_RENDERABLE = 0x00008287;
    public const int GL_STENCIL_RENDERABLE = 0x00008288;
    public const int GL_FRAMEBUFFER_RENDERABLE = 0x00008289;
    public const int GL_FRAMEBUFFER_RENDERABLE_LAYERED = 0x0000828A;
    public const int GL_FRAMEBUFFER_BLEND = 0x0000828B;
    public const int GL_READ_PIXELS = 0x0000828C;
    public const int GL_READ_PIXELS_FORMAT = 0x0000828D;
    public const int GL_READ_PIXELS_TYPE = 0x0000828E;
    public const int GL_TEXTURE_IMAGE_FORMAT = 0x0000828F;
    public const int GL_TEXTURE_IMAGE_TYPE = 0x00008290;
    public const int GL_GET_TEXTURE_IMAGE_FORMAT = 0x00008291;
    public const int GL_GET_TEXTURE_IMAGE_TYPE = 0x00008292;
    public const int GL_MIPMAP = 0x00008293;
    public const int GL_MANUAL_GENERATE_MIPMAP = 0x00008294;
    public const int GL_AUTO_GENERATE_MIPMAP = 0x00008295;
    public const int GL_COLOR_ENCODING = 0x00008296;
    public const int GL_SRGB_READ = 0x00008297;
    public const int GL_SRGB_WRITE = 0x00008298;
    public const int GL_FILTER = 0x0000829A;
    public const int GL_VERTEX_TEXTURE = 0x0000829B;
    public const int GL_TESS_CONTROL_TEXTURE = 0x0000829C;
    public const int GL_TESS_EVALUATION_TEXTURE = 0x0000829D;
    public const int GL_GEOMETRY_TEXTURE = 0x0000829E;
    public const int GL_FRAGMENT_TEXTURE = 0x0000829F;
    public const int GL_COMPUTE_TEXTURE = 0x000082A0;
    public const int GL_TEXTURE_SHADOW = 0x000082A1;
    public const int GL_TEXTURE_GATHER = 0x000082A2;
    public const int GL_TEXTURE_GATHER_SHADOW = 0x000082A3;
    public const int GL_SHADER_IMAGE_LOAD = 0x000082A4;
    public const int GL_SHADER_IMAGE_STORE = 0x000082A5;
    public const int GL_SHADER_IMAGE_ATOMIC = 0x000082A6;
    public const int GL_IMAGE_TEXEL_SIZE = 0x000082A7;
    public const int GL_IMAGE_COMPATIBILITY_CLASS = 0x000082A8;
    public const int GL_IMAGE_PIXEL_FORMAT = 0x000082A9;
    public const int GL_IMAGE_PIXEL_TYPE = 0x000082AA;
    public const int GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_TEST = 0x000082AC;
    public const int GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_TEST = 0x000082AD;
    public const int GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_WRITE = 0x000082AE;
    public const int GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_WRITE = 0x000082AF;
    public const int GL_TEXTURE_COMPRESSED_BLOCK_WIDTH = 0x000082B1;
    public const int GL_TEXTURE_COMPRESSED_BLOCK_HEIGHT = 0x000082B2;
    public const int GL_TEXTURE_COMPRESSED_BLOCK_SIZE = 0x000082B3;
    public const int GL_CLEAR_BUFFER = 0x000082B4;
    public const int GL_TEXTURE_VIEW = 0x000082B5;
    public const int GL_VIEW_COMPATIBILITY_CLASS = 0x000082B6;
    public const int GL_FULL_SUPPORT = 0x000082B7;
    public const int GL_CAVEAT_SUPPORT = 0x000082B8;
    public const int GL_IMAGE_CLASS_4_X_32 = 0x000082B9;
    public const int GL_IMAGE_CLASS_2_X_32 = 0x000082BA;
    public const int GL_IMAGE_CLASS_1_X_32 = 0x000082BB;
    public const int GL_IMAGE_CLASS_4_X_16 = 0x000082BC;
    public const int GL_IMAGE_CLASS_2_X_16 = 0x000082BD;
    public const int GL_IMAGE_CLASS_1_X_16 = 0x000082BE;
    public const int GL_IMAGE_CLASS_4_X_8 = 0x000082BF;
    public const int GL_IMAGE_CLASS_2_X_8 = 0x000082C0;
    public const int GL_IMAGE_CLASS_1_X_8 = 0x000082C1;
    public const int GL_IMAGE_CLASS_11_11_10 = 0x000082C2;
    public const int GL_IMAGE_CLASS_10_10_10_2 = 0x000082C3;
    public const int GL_VIEW_CLASS_128_BITS = 0x000082C4;
    public const int GL_VIEW_CLASS_96_BITS = 0x000082C5;
    public const int GL_VIEW_CLASS_64_BITS = 0x000082C6;
    public const int GL_VIEW_CLASS_48_BITS = 0x000082C7;
    public const int GL_VIEW_CLASS_32_BITS = 0x000082C8;
    public const int GL_VIEW_CLASS_24_BITS = 0x000082C9;
    public const int GL_VIEW_CLASS_16_BITS = 0x000082CA;
    public const int GL_VIEW_CLASS_8_BITS = 0x000082CB;
    public const int GL_VIEW_CLASS_S3TC_DXT1_RGB = 0x000082CC;
    public const int GL_VIEW_CLASS_S3TC_DXT1_RGBA = 0x000082CD;
    public const int GL_VIEW_CLASS_S3TC_DXT3_RGBA = 0x000082CE;
    public const int GL_VIEW_CLASS_S3TC_DXT5_RGBA = 0x000082CF;
    public const int GL_VIEW_CLASS_RGTC1_RED = 0x000082D0;
    public const int GL_VIEW_CLASS_RGTC2_RG = 0x000082D1;
    public const int GL_VIEW_CLASS_BPTC_UNORM = 0x000082D2;
    public const int GL_VIEW_CLASS_BPTC_FLOAT = 0x000082D3;
    public const int GL_UNIFORM = 0x000092E1;
    public const int GL_UNIFORM_BLOCK = 0x000092E2;
    public const int GL_PROGRAM_INPUT = 0x000092E3;
    public const int GL_PROGRAM_OUTPUT = 0x000092E4;
    public const int GL_BUFFER_VARIABLE = 0x000092E5;
    public const int GL_SHADER_STORAGE_BLOCK = 0x000092E6;
    public const int GL_VERTEX_SUBROUTINE = 0x000092E8;
    public const int GL_TESS_CONTROL_SUBROUTINE = 0x000092E9;
    public const int GL_TESS_EVALUATION_SUBROUTINE = 0x000092EA;
    public const int GL_GEOMETRY_SUBROUTINE = 0x000092EB;
    public const int GL_FRAGMENT_SUBROUTINE = 0x000092EC;
    public const int GL_COMPUTE_SUBROUTINE = 0x000092ED;
    public const int GL_VERTEX_SUBROUTINE_UNIFORM = 0x000092EE;
    public const int GL_TESS_CONTROL_SUBROUTINE_UNIFORM = 0x000092EF;
    public const int GL_TESS_EVALUATION_SUBROUTINE_UNIFORM = 0x000092F0;
    public const int GL_GEOMETRY_SUBROUTINE_UNIFORM = 0x000092F1;
    public const int GL_FRAGMENT_SUBROUTINE_UNIFORM = 0x000092F2;
    public const int GL_COMPUTE_SUBROUTINE_UNIFORM = 0x000092F3;
    public const int GL_TRANSFORM_FEEDBACK_VARYING = 0x000092F4;
    public const int GL_ACTIVE_RESOURCES = 0x000092F5;
    public const int GL_MAX_NAME_LENGTH = 0x000092F6;
    public const int GL_MAX_NUM_ACTIVE_VARIABLES = 0x000092F7;
    public const int GL_MAX_NUM_COMPATIBLE_SUBROUTINES = 0x000092F8;
    public const int GL_NAME_LENGTH = 0x000092F9;
    public const int GL_TYPE = 0x000092FA;
    public const int GL_ARRAY_SIZE = 0x000092FB;
    public const int GL_OFFSET = 0x000092FC;
    public const int GL_BLOCK_INDEX = 0x000092FD;
    public const int GL_ARRAY_STRIDE = 0x000092FE;
    public const int GL_MATRIX_STRIDE = 0x000092FF;
    public const int GL_IS_ROW_MAJOR = 0x00009300;
    public const int GL_ATOMIC_COUNTER_BUFFER_INDEX = 0x00009301;
    public const int GL_BUFFER_BINDING = 0x00009302;
    public const int GL_BUFFER_DATA_SIZE = 0x00009303;
    public const int GL_NUM_ACTIVE_VARIABLES = 0x00009304;
    public const int GL_ACTIVE_VARIABLES = 0x00009305;
    public const int GL_REFERENCED_BY_VERTEX_SHADER = 0x00009306;
    public const int GL_REFERENCED_BY_TESS_CONTROL_SHADER = 0x00009307;
    public const int GL_REFERENCED_BY_TESS_EVALUATION_SHADER = 0x00009308;
    public const int GL_REFERENCED_BY_GEOMETRY_SHADER = 0x00009309;
    public const int GL_REFERENCED_BY_FRAGMENT_SHADER = 0x0000930A;
    public const int GL_REFERENCED_BY_COMPUTE_SHADER = 0x0000930B;
    public const int GL_TOP_LEVEL_ARRAY_SIZE = 0x0000930C;
    public const int GL_TOP_LEVEL_ARRAY_STRIDE = 0x0000930D;
    public const int GL_LOCATION = 0x0000930E;
    public const int GL_LOCATION_INDEX = 0x0000930F;
    public const int GL_IS_PER_PATCH = 0x000092E7;
    public const int GL_SHADER_STORAGE_BUFFER = 0x000090D2;
    public const int GL_SHADER_STORAGE_BUFFER_BINDING = 0x000090D3;
    public const int GL_SHADER_STORAGE_BUFFER_START = 0x000090D4;
    public const int GL_SHADER_STORAGE_BUFFER_SIZE = 0x000090D5;
    public const int GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS = 0x000090D6;
    public const int GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS = 0x000090D7;
    public const int GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS = 0x000090D8;
    public const int GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS = 0x000090D9;
    public const int GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS = 0x000090DA;
    public const int GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS = 0x000090DB;
    public const int GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS = 0x000090DC;
    public const int GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS = 0x000090DD;
    public const int GL_MAX_SHADER_STORAGE_BLOCK_SIZE = 0x000090DE;
    public const int GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT = 0x000090DF;
    public const int GL_SHADER_STORAGE_BARRIER_BIT = 0x00002000;
    public const int GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES = 0x00008F39;
    public const int GL_DEPTH_STENCIL_TEXTURE_MODE = 0x000090EA;
    public const int GL_TEXTURE_BUFFER_OFFSET = 0x0000919D;
    public const int GL_TEXTURE_BUFFER_SIZE = 0x0000919E;
    public const int GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT = 0x0000919F;
    public const int GL_TEXTURE_VIEW_MIN_LEVEL = 0x000082DB;
    public const int GL_TEXTURE_VIEW_NUM_LEVELS = 0x000082DC;
    public const int GL_TEXTURE_VIEW_MIN_LAYER = 0x000082DD;
    public const int GL_TEXTURE_VIEW_NUM_LAYERS = 0x000082DE;
    public const int GL_TEXTURE_IMMUTABLE_LEVELS = 0x000082DF;
    public const int GL_VERTEX_ATTRIB_BINDING = 0x000082D4;
    public const int GL_VERTEX_ATTRIB_RELATIVE_OFFSET = 0x000082D5;
    public const int GL_VERTEX_BINDING_DIVISOR = 0x000082D6;
    public const int GL_VERTEX_BINDING_OFFSET = 0x000082D7;
    public const int GL_VERTEX_BINDING_STRIDE = 0x000082D8;
    public const int GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET = 0x000082D9;
    public const int GL_MAX_VERTEX_ATTRIB_BINDINGS = 0x000082DA;
    public const int GL_VERTEX_BINDING_BUFFER = 0x00008F4F;
    public const int GL_DISPLAY_LIST = 0x000082E7;
    public const int GL_STACK_UNDERFLOW = 0x00000504;
    public const int GL_STACK_OVERFLOW = 0x00000503;
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, uint, uint, uint, void*, void> _glClearBufferData = null;
    internal static delegate* unmanaged<uint, uint, nint, nint, uint, uint, void*, void> _glClearBufferSubData = null;
    internal static delegate* unmanaged<uint, uint, uint, void> _glDispatchCompute = null;
    internal static delegate* unmanaged<nint, void> _glDispatchComputeIndirect = null;
    internal static delegate* unmanaged<uint, uint, int, int, int, int, uint, uint, int, int, int, int, int, int, int, void> _glCopyImageSubData = null;
    internal static delegate* unmanaged<uint, uint, int, void> _glFramebufferParameteri = null;
    internal static delegate* unmanaged<uint, uint, int*, void> _glGetFramebufferParameteriv = null;
    internal static delegate* unmanaged<uint, uint, uint, int, long*, void> _glGetInternalformati64v = null;
    internal static delegate* unmanaged<uint, int, int, int, int, int, int, int, void> _glInvalidateTexSubImage = null;
    internal static delegate* unmanaged<uint, int, void> _glInvalidateTexImage = null;
    internal static delegate* unmanaged<uint, nint, nint, void> _glInvalidateBufferSubData = null;
    internal static delegate* unmanaged<uint, void> _glInvalidateBufferData = null;
    internal static delegate* unmanaged<uint, int, uint*, void> _glInvalidateFramebuffer = null;
    internal static delegate* unmanaged<uint, int, uint*, int, int, int, int, void> _glInvalidateSubFramebuffer = null;
    internal static delegate* unmanaged<uint, void*, int, int, void> _glMultiDrawArraysIndirect = null;
    internal static delegate* unmanaged<uint, uint, void*, int, int, void> _glMultiDrawElementsIndirect = null;
    internal static delegate* unmanaged<uint, uint, uint, int*, void> _glGetProgramInterfaceiv = null;
    internal static delegate* unmanaged<uint, uint, byte*, uint> _glGetProgramResourceIndex = null;
    internal static delegate* unmanaged<uint, uint, uint, int, int*, byte*, void> _glGetProgramResourceName = null;
    internal static delegate* unmanaged<uint, uint, uint, int, uint*, int, int*, int*, void> _glGetProgramResourceiv = null;
    internal static delegate* unmanaged<uint, uint, byte*, int> _glGetProgramResourceLocation = null;
    internal static delegate* unmanaged<uint, uint, byte*, int> _glGetProgramResourceLocationIndex = null;
    internal static delegate* unmanaged<uint, uint, uint, void> _glShaderStorageBlockBinding = null;
    internal static delegate* unmanaged<uint, uint, uint, nint, nint, void> _glTexBufferRange = null;
    internal static delegate* unmanaged<uint, int, uint, int, int, bool, void> _glTexStorage2DMultisample = null;
    internal static delegate* unmanaged<uint, int, uint, int, int, int, bool, void> _glTexStorage3DMultisample = null;
    internal static delegate* unmanaged<uint, uint, uint, uint, uint, uint, uint, uint, void> _glTextureView = null;
    internal static delegate* unmanaged<uint, uint, nint, int, void> _glBindVertexBuffer = null;
    internal static delegate* unmanaged<uint, int, uint, bool, uint, void> _glVertexAttribFormat = null;
    internal static delegate* unmanaged<uint, int, uint, uint, void> _glVertexAttribIFormat = null;
    internal static delegate* unmanaged<uint, int, uint, uint, void> _glVertexAttribLFormat = null;
    internal static delegate* unmanaged<uint, uint, void> _glVertexAttribBinding = null;
    internal static delegate* unmanaged<uint, uint, void> _glVertexBindingDivisor = null;
    internal static delegate* unmanaged<uint, uint, uint, int, uint*, bool, void> _glDebugMessageControl = null;
    internal static delegate* unmanaged<uint, uint, uint, uint, int, byte*, void> _glDebugMessageInsert = null;
    internal static delegate* unmanaged<nint, void*, void> _glDebugMessageCallback = null;
    internal static delegate* unmanaged<uint, int, uint*, uint*, uint*, uint*, int*, byte*, uint> _glGetDebugMessageLog = null;
    internal static delegate* unmanaged<uint, uint, int, byte*, void> _glPushDebugGroup = null;
    internal static delegate* unmanaged<void> _glPopDebugGroup = null;
    internal static delegate* unmanaged<uint, uint, int, byte*, void> _glObjectLabel = null;
    internal static delegate* unmanaged<uint, uint, int, int*, byte*, void> _glGetObjectLabel = null;
    internal static delegate* unmanaged<void*, int, byte*, void> _glObjectPtrLabel = null;
    internal static delegate* unmanaged<void*, int, int*, byte*, void> _glGetObjectPtrLabel = null;
    internal static delegate* unmanaged<uint, void**, void> _glGetPointerv = null;

    internal static void Load()
    {
        _glClearBufferData = (delegate* unmanaged<uint, uint, uint, uint, void*, void>)QuickGL.GetGLProcAddress("glClearBufferData");
        _glClearBufferSubData = (delegate* unmanaged<uint, uint, nint, nint, uint, uint, void*, void>)QuickGL.GetGLProcAddress("glClearBufferSubData");
        _glDispatchCompute = (delegate* unmanaged<uint, uint, uint, void>)QuickGL.GetGLProcAddress("glDispatchCompute");
        _glDispatchComputeIndirect = (delegate* unmanaged<nint, void>)QuickGL.GetGLProcAddress("glDispatchComputeIndirect");
        _glCopyImageSubData = (delegate* unmanaged<uint, uint, int, int, int, int, uint, uint, int, int, int, int, int, int, int, void>)QuickGL.GetGLProcAddress("glCopyImageSubData");
        _glFramebufferParameteri = (delegate* unmanaged<uint, uint, int, void>)QuickGL.GetGLProcAddress("glFramebufferParameteri");
        _glGetFramebufferParameteriv = (delegate* unmanaged<uint, uint, int*, void>)QuickGL.GetGLProcAddress("glGetFramebufferParameteriv");
        _glGetInternalformati64v = (delegate* unmanaged<uint, uint, uint, int, long*, void>)QuickGL.GetGLProcAddress("glGetInternalformati64v");
        _glInvalidateTexSubImage = (delegate* unmanaged<uint, int, int, int, int, int, int, int, void>)QuickGL.GetGLProcAddress("glInvalidateTexSubImage");
        _glInvalidateTexImage = (delegate* unmanaged<uint, int, void>)QuickGL.GetGLProcAddress("glInvalidateTexImage");
        _glInvalidateBufferSubData = (delegate* unmanaged<uint, nint, nint, void>)QuickGL.GetGLProcAddress("glInvalidateBufferSubData");
        _glInvalidateBufferData = (delegate* unmanaged<uint, void>)QuickGL.GetGLProcAddress("glInvalidateBufferData");
        _glInvalidateFramebuffer = (delegate* unmanaged<uint, int, uint*, void>)QuickGL.GetGLProcAddress("glInvalidateFramebuffer");
        _glInvalidateSubFramebuffer = (delegate* unmanaged<uint, int, uint*, int, int, int, int, void>)QuickGL.GetGLProcAddress("glInvalidateSubFramebuffer");
        _glMultiDrawArraysIndirect = (delegate* unmanaged<uint, void*, int, int, void>)QuickGL.GetGLProcAddress("glMultiDrawArraysIndirect");
        _glMultiDrawElementsIndirect = (delegate* unmanaged<uint, uint, void*, int, int, void>)QuickGL.GetGLProcAddress("glMultiDrawElementsIndirect");
        _glGetProgramInterfaceiv = (delegate* unmanaged<uint, uint, uint, int*, void>)QuickGL.GetGLProcAddress("glGetProgramInterfaceiv");
        _glGetProgramResourceIndex = (delegate* unmanaged<uint, uint, byte*, uint>)QuickGL.GetGLProcAddress("glGetProgramResourceIndex");
        _glGetProgramResourceName = (delegate* unmanaged<uint, uint, uint, int, int*, byte*, void>)QuickGL.GetGLProcAddress("glGetProgramResourceName");
        _glGetProgramResourceiv = (delegate* unmanaged<uint, uint, uint, int, uint*, int, int*, int*, void>)QuickGL.GetGLProcAddress("glGetProgramResourceiv");
        _glGetProgramResourceLocation = (delegate* unmanaged<uint, uint, byte*, int>)QuickGL.GetGLProcAddress("glGetProgramResourceLocation");
        _glGetProgramResourceLocationIndex = (delegate* unmanaged<uint, uint, byte*, int>)QuickGL.GetGLProcAddress("glGetProgramResourceLocationIndex");
        _glShaderStorageBlockBinding = (delegate* unmanaged<uint, uint, uint, void>)QuickGL.GetGLProcAddress("glShaderStorageBlockBinding");
        _glTexBufferRange = (delegate* unmanaged<uint, uint, uint, nint, nint, void>)QuickGL.GetGLProcAddress("glTexBufferRange");
        _glTexStorage2DMultisample = (delegate* unmanaged<uint, int, uint, int, int, bool, void>)QuickGL.GetGLProcAddress("glTexStorage2DMultisample");
        _glTexStorage3DMultisample = (delegate* unmanaged<uint, int, uint, int, int, int, bool, void>)QuickGL.GetGLProcAddress("glTexStorage3DMultisample");
        _glTextureView = (delegate* unmanaged<uint, uint, uint, uint, uint, uint, uint, uint, void>)QuickGL.GetGLProcAddress("glTextureView");
        _glBindVertexBuffer = (delegate* unmanaged<uint, uint, nint, int, void>)QuickGL.GetGLProcAddress("glBindVertexBuffer");
        _glVertexAttribFormat = (delegate* unmanaged<uint, int, uint, bool, uint, void>)QuickGL.GetGLProcAddress("glVertexAttribFormat");
        _glVertexAttribIFormat = (delegate* unmanaged<uint, int, uint, uint, void>)QuickGL.GetGLProcAddress("glVertexAttribIFormat");
        _glVertexAttribLFormat = (delegate* unmanaged<uint, int, uint, uint, void>)QuickGL.GetGLProcAddress("glVertexAttribLFormat");
        _glVertexAttribBinding = (delegate* unmanaged<uint, uint, void>)QuickGL.GetGLProcAddress("glVertexAttribBinding");
        _glVertexBindingDivisor = (delegate* unmanaged<uint, uint, void>)QuickGL.GetGLProcAddress("glVertexBindingDivisor");
        _glDebugMessageControl = (delegate* unmanaged<uint, uint, uint, int, uint*, bool, void>)QuickGL.GetGLProcAddress("glDebugMessageControl");
        _glDebugMessageInsert = (delegate* unmanaged<uint, uint, uint, uint, int, byte*, void>)QuickGL.GetGLProcAddress("glDebugMessageInsert");
        _glDebugMessageCallback = (delegate* unmanaged<nint, void*, void>)QuickGL.GetGLProcAddress("glDebugMessageCallback");
        _glGetDebugMessageLog = (delegate* unmanaged<uint, int, uint*, uint*, uint*, uint*, int*, byte*, uint>)QuickGL.GetGLProcAddress("glGetDebugMessageLog");
        _glPushDebugGroup = (delegate* unmanaged<uint, uint, int, byte*, void>)QuickGL.GetGLProcAddress("glPushDebugGroup");
        _glPopDebugGroup = (delegate* unmanaged<void>)QuickGL.GetGLProcAddress("glPopDebugGroup");
        _glObjectLabel = (delegate* unmanaged<uint, uint, int, byte*, void>)QuickGL.GetGLProcAddress("glObjectLabel");
        _glGetObjectLabel = (delegate* unmanaged<uint, uint, int, int*, byte*, void>)QuickGL.GetGLProcAddress("glGetObjectLabel");
        _glObjectPtrLabel = (delegate* unmanaged<void*, int, byte*, void>)QuickGL.GetGLProcAddress("glObjectPtrLabel");
        _glGetObjectPtrLabel = (delegate* unmanaged<void*, int, int*, byte*, void>)QuickGL.GetGLProcAddress("glGetObjectPtrLabel");
        _glGetPointerv = (delegate* unmanaged<uint, void**, void>)QuickGL.GetGLProcAddress("glGetPointerv");
    }

    internal static void Unload()
    {
        _glClearBufferData = null;
        _glClearBufferSubData = null;
        _glDispatchCompute = null;
        _glDispatchComputeIndirect = null;
        _glCopyImageSubData = null;
        _glFramebufferParameteri = null;
        _glGetFramebufferParameteriv = null;
        _glGetInternalformati64v = null;
        _glInvalidateTexSubImage = null;
        _glInvalidateTexImage = null;
        _glInvalidateBufferSubData = null;
        _glInvalidateBufferData = null;
        _glInvalidateFramebuffer = null;
        _glInvalidateSubFramebuffer = null;
        _glMultiDrawArraysIndirect = null;
        _glMultiDrawElementsIndirect = null;
        _glGetProgramInterfaceiv = null;
        _glGetProgramResourceIndex = null;
        _glGetProgramResourceName = null;
        _glGetProgramResourceiv = null;
        _glGetProgramResourceLocation = null;
        _glGetProgramResourceLocationIndex = null;
        _glShaderStorageBlockBinding = null;
        _glTexBufferRange = null;
        _glTexStorage2DMultisample = null;
        _glTexStorage3DMultisample = null;
        _glTextureView = null;
        _glBindVertexBuffer = null;
        _glVertexAttribFormat = null;
        _glVertexAttribIFormat = null;
        _glVertexAttribLFormat = null;
        _glVertexAttribBinding = null;
        _glVertexBindingDivisor = null;
        _glDebugMessageControl = null;
        _glDebugMessageInsert = null;
        _glDebugMessageCallback = null;
        _glGetDebugMessageLog = null;
        _glPushDebugGroup = null;
        _glPopDebugGroup = null;
        _glObjectLabel = null;
        _glGetObjectLabel = null;
        _glObjectPtrLabel = null;
        _glGetObjectPtrLabel = null;
        _glGetPointerv = null;
    }
    #endregion

    #region Function wrappers
    public static void glClearBufferData(uint target, uint internalformat, uint format, uint type, void* data) { QGLFeature.VerifyFunc((nint)_glClearBufferData); _glClearBufferData(target, internalformat, format, type, data); }
    public static void glClearBufferSubData(uint target, uint internalformat, nint offset, nint size, uint format, uint type, void* data) { QGLFeature.VerifyFunc((nint)_glClearBufferSubData); _glClearBufferSubData(target, internalformat, offset, size, format, type, data); }
    public static void glDispatchCompute(uint num_groups_x, uint num_groups_y, uint num_groups_z) { QGLFeature.VerifyFunc((nint)_glDispatchCompute); _glDispatchCompute(num_groups_x, num_groups_y, num_groups_z); }
    public static void glDispatchComputeIndirect(nint indirect) { QGLFeature.VerifyFunc((nint)_glDispatchComputeIndirect); _glDispatchComputeIndirect(indirect); }
    public static void glCopyImageSubData(uint srcName, uint srcTarget, int srcLevel, int srcX, int srcY, int srcZ, uint dstName, uint dstTarget, int dstLevel, int dstX, int dstY, int dstZ, int srcWidth, int srcHeight, int srcDepth) { QGLFeature.VerifyFunc((nint)_glCopyImageSubData); _glCopyImageSubData(srcName, srcTarget, srcLevel, srcX, srcY, srcZ, dstName, dstTarget, dstLevel, dstX, dstY, dstZ, srcWidth, srcHeight, srcDepth); }
    public static void glFramebufferParameteri(uint target, uint pname, int param) { QGLFeature.VerifyFunc((nint)_glFramebufferParameteri); _glFramebufferParameteri(target, pname, param); }
    public static void glGetFramebufferParameteriv(uint target, uint pname, int* @params) { QGLFeature.VerifyFunc((nint)_glGetFramebufferParameteriv); _glGetFramebufferParameteriv(target, pname, @params); }
    public static void glGetInternalformati64v(uint target, uint internalformat, uint pname, int count, long* @params) { QGLFeature.VerifyFunc((nint)_glGetInternalformati64v); _glGetInternalformati64v(target, internalformat, pname, count, @params); }
    public static void glInvalidateTexSubImage(uint texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth) { QGLFeature.VerifyFunc((nint)_glInvalidateTexSubImage); _glInvalidateTexSubImage(texture, level, xoffset, yoffset, zoffset, width, height, depth); }
    public static void glInvalidateTexImage(uint texture, int level) { QGLFeature.VerifyFunc((nint)_glInvalidateTexImage); _glInvalidateTexImage(texture, level); }
    public static void glInvalidateBufferSubData(uint buffer, nint offset, nint length) { QGLFeature.VerifyFunc((nint)_glInvalidateBufferSubData); _glInvalidateBufferSubData(buffer, offset, length); }
    public static void glInvalidateBufferData(uint buffer) { QGLFeature.VerifyFunc((nint)_glInvalidateBufferData); _glInvalidateBufferData(buffer); }
    public static void glInvalidateFramebuffer(uint target, int numAttachments, uint* attachments) { QGLFeature.VerifyFunc((nint)_glInvalidateFramebuffer); _glInvalidateFramebuffer(target, numAttachments, attachments); }
    public static void glInvalidateSubFramebuffer(uint target, int numAttachments, uint* attachments, int x, int y, int width, int height) { QGLFeature.VerifyFunc((nint)_glInvalidateSubFramebuffer); _glInvalidateSubFramebuffer(target, numAttachments, attachments, x, y, width, height); }
    public static void glMultiDrawArraysIndirect(uint mode, void* indirect, int drawcount, int stride) { QGLFeature.VerifyFunc((nint)_glMultiDrawArraysIndirect); _glMultiDrawArraysIndirect(mode, indirect, drawcount, stride); }
    public static void glMultiDrawElementsIndirect(uint mode, uint type, void* indirect, int drawcount, int stride) { QGLFeature.VerifyFunc((nint)_glMultiDrawElementsIndirect); _glMultiDrawElementsIndirect(mode, type, indirect, drawcount, stride); }
    public static void glGetProgramInterfaceiv(uint program, uint programInterface, uint pname, int* @params) { QGLFeature.VerifyFunc((nint)_glGetProgramInterfaceiv); _glGetProgramInterfaceiv(program, programInterface, pname, @params); }
    public static uint glGetProgramResourceIndex(uint program, uint programInterface, byte* name) { QGLFeature.VerifyFunc((nint)_glGetProgramResourceIndex); return _glGetProgramResourceIndex(program, programInterface, name); }
    public static void glGetProgramResourceName(uint program, uint programInterface, uint index, int bufSize, int* length, byte* name) { QGLFeature.VerifyFunc((nint)_glGetProgramResourceName); _glGetProgramResourceName(program, programInterface, index, bufSize, length, name); }
    public static void glGetProgramResourceiv(uint program, uint programInterface, uint index, int propCount, uint* props, int count, int* length, int* @params) { QGLFeature.VerifyFunc((nint)_glGetProgramResourceiv); _glGetProgramResourceiv(program, programInterface, index, propCount, props, count, length, @params); }
    public static int glGetProgramResourceLocation(uint program, uint programInterface, byte* name) { QGLFeature.VerifyFunc((nint)_glGetProgramResourceLocation); return _glGetProgramResourceLocation(program, programInterface, name); }
    public static int glGetProgramResourceLocationIndex(uint program, uint programInterface, byte* name) { QGLFeature.VerifyFunc((nint)_glGetProgramResourceLocationIndex); return _glGetProgramResourceLocationIndex(program, programInterface, name); }
    public static void glShaderStorageBlockBinding(uint program, uint storageBlockIndex, uint storageBlockBinding) { QGLFeature.VerifyFunc((nint)_glShaderStorageBlockBinding); _glShaderStorageBlockBinding(program, storageBlockIndex, storageBlockBinding); }
    public static void glTexBufferRange(uint target, uint internalformat, uint buffer, nint offset, nint size) { QGLFeature.VerifyFunc((nint)_glTexBufferRange); _glTexBufferRange(target, internalformat, buffer, offset, size); }
    public static void glTexStorage2DMultisample(uint target, int samples, uint internalformat, int width, int height, bool fixedsamplelocations) { QGLFeature.VerifyFunc((nint)_glTexStorage2DMultisample); _glTexStorage2DMultisample(target, samples, internalformat, width, height, fixedsamplelocations); }
    public static void glTexStorage3DMultisample(uint target, int samples, uint internalformat, int width, int height, int depth, bool fixedsamplelocations) { QGLFeature.VerifyFunc((nint)_glTexStorage3DMultisample); _glTexStorage3DMultisample(target, samples, internalformat, width, height, depth, fixedsamplelocations); }
    public static void glTextureView(uint texture, uint target, uint origtexture, uint internalformat, uint minlevel, uint numlevels, uint minlayer, uint numlayers) { QGLFeature.VerifyFunc((nint)_glTextureView); _glTextureView(texture, target, origtexture, internalformat, minlevel, numlevels, minlayer, numlayers); }
    public static void glBindVertexBuffer(uint bindingindex, uint buffer, nint offset, int stride) { QGLFeature.VerifyFunc((nint)_glBindVertexBuffer); _glBindVertexBuffer(bindingindex, buffer, offset, stride); }
    public static void glVertexAttribFormat(uint attribindex, int size, uint type, bool normalized, uint relativeoffset) { QGLFeature.VerifyFunc((nint)_glVertexAttribFormat); _glVertexAttribFormat(attribindex, size, type, normalized, relativeoffset); }
    public static void glVertexAttribIFormat(uint attribindex, int size, uint type, uint relativeoffset) { QGLFeature.VerifyFunc((nint)_glVertexAttribIFormat); _glVertexAttribIFormat(attribindex, size, type, relativeoffset); }
    public static void glVertexAttribLFormat(uint attribindex, int size, uint type, uint relativeoffset) { QGLFeature.VerifyFunc((nint)_glVertexAttribLFormat); _glVertexAttribLFormat(attribindex, size, type, relativeoffset); }
    public static void glVertexAttribBinding(uint attribindex, uint bindingindex) { QGLFeature.VerifyFunc((nint)_glVertexAttribBinding); _glVertexAttribBinding(attribindex, bindingindex); }
    public static void glVertexBindingDivisor(uint bindingindex, uint divisor) { QGLFeature.VerifyFunc((nint)_glVertexBindingDivisor); _glVertexBindingDivisor(bindingindex, divisor); }
    public static void glDebugMessageControl(uint source, uint type, uint severity, int count, uint* ids, bool enabled) { QGLFeature.VerifyFunc((nint)_glDebugMessageControl); _glDebugMessageControl(source, type, severity, count, ids, enabled); }
    public static void glDebugMessageInsert(uint source, uint type, uint id, uint severity, int length, byte* buf) { QGLFeature.VerifyFunc((nint)_glDebugMessageInsert); _glDebugMessageInsert(source, type, id, severity, length, buf); }
    public static void glDebugMessageCallback(nint callback, void* userParam) { QGLFeature.VerifyFunc((nint)_glDebugMessageCallback); _glDebugMessageCallback(callback, userParam); }
    public static uint glGetDebugMessageLog(uint count, int bufSize, uint* sources, uint* types, uint* ids, uint* severities, int* lengths, byte* messageLog) { QGLFeature.VerifyFunc((nint)_glGetDebugMessageLog); return _glGetDebugMessageLog(count, bufSize, sources, types, ids, severities, lengths, messageLog); }
    public static void glPushDebugGroup(uint source, uint id, int length, byte* message) { QGLFeature.VerifyFunc((nint)_glPushDebugGroup); _glPushDebugGroup(source, id, length, message); }
    public static void glPopDebugGroup() { QGLFeature.VerifyFunc((nint)_glPopDebugGroup); _glPopDebugGroup(); }
    public static void glObjectLabel(uint identifier, uint name, int length, byte* label) { QGLFeature.VerifyFunc((nint)_glObjectLabel); _glObjectLabel(identifier, name, length, label); }
    public static void glGetObjectLabel(uint identifier, uint name, int bufSize, int* length, byte* label) { QGLFeature.VerifyFunc((nint)_glGetObjectLabel); _glGetObjectLabel(identifier, name, bufSize, length, label); }
    public static void glObjectPtrLabel(void* ptr, int length, byte* label) { QGLFeature.VerifyFunc((nint)_glObjectPtrLabel); _glObjectPtrLabel(ptr, length, label); }
    public static void glGetObjectPtrLabel(void* ptr, int bufSize, int* length, byte* label) { QGLFeature.VerifyFunc((nint)_glGetObjectPtrLabel); _glGetObjectPtrLabel(ptr, bufSize, length, label); }
    public static void glGetPointerv(uint pname, void** @params) { QGLFeature.VerifyFunc((nint)_glGetPointerv); _glGetPointerv(pname, @params); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_VERSION_4_3", false, false);
}
