// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:43:43.7403347Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings;

public static unsafe class GLES30
{
    #region Constants
    public const int GL_READ_BUFFER = 0x00000C02;
    public const int GL_UNPACK_ROW_LENGTH = 0x00000CF2;
    public const int GL_UNPACK_SKIP_ROWS = 0x00000CF3;
    public const int GL_UNPACK_SKIP_PIXELS = 0x00000CF4;
    public const int GL_PACK_ROW_LENGTH = 0x00000D02;
    public const int GL_PACK_SKIP_ROWS = 0x00000D03;
    public const int GL_PACK_SKIP_PIXELS = 0x00000D04;
    public const int GL_COLOR = 0x00001800;
    public const int GL_DEPTH = 0x00001801;
    public const int GL_STENCIL = 0x00001802;
    public const int GL_RED = 0x00001903;
    public const int GL_RGB8 = 0x00008051;
    public const int GL_RGBA8 = 0x00008058;
    public const int GL_RGB10_A2 = 0x00008059;
    public const int GL_TEXTURE_BINDING_3D = 0x0000806A;
    public const int GL_UNPACK_SKIP_IMAGES = 0x0000806D;
    public const int GL_UNPACK_IMAGE_HEIGHT = 0x0000806E;
    public const int GL_TEXTURE_3D = 0x0000806F;
    public const int GL_TEXTURE_WRAP_R = 0x00008072;
    public const int GL_MAX_3D_TEXTURE_SIZE = 0x00008073;
    public const int GL_UNSIGNED_INT_2_10_10_10_REV = 0x00008368;
    public const int GL_MAX_ELEMENTS_VERTICES = 0x000080E8;
    public const int GL_MAX_ELEMENTS_INDICES = 0x000080E9;
    public const int GL_TEXTURE_MIN_LOD = 0x0000813A;
    public const int GL_TEXTURE_MAX_LOD = 0x0000813B;
    public const int GL_TEXTURE_BASE_LEVEL = 0x0000813C;
    public const int GL_TEXTURE_MAX_LEVEL = 0x0000813D;
    public const int GL_MIN = 0x00008007;
    public const int GL_MAX = 0x00008008;
    public const int GL_DEPTH_COMPONENT24 = 0x000081A6;
    public const int GL_MAX_TEXTURE_LOD_BIAS = 0x000084FD;
    public const int GL_TEXTURE_COMPARE_MODE = 0x0000884C;
    public const int GL_TEXTURE_COMPARE_FUNC = 0x0000884D;
    public const int GL_CURRENT_QUERY = 0x00008865;
    public const int GL_QUERY_RESULT = 0x00008866;
    public const int GL_QUERY_RESULT_AVAILABLE = 0x00008867;
    public const int GL_BUFFER_MAPPED = 0x000088BC;
    public const int GL_BUFFER_MAP_POINTER = 0x000088BD;
    public const int GL_STREAM_READ = 0x000088E1;
    public const int GL_STREAM_COPY = 0x000088E2;
    public const int GL_STATIC_READ = 0x000088E5;
    public const int GL_STATIC_COPY = 0x000088E6;
    public const int GL_DYNAMIC_READ = 0x000088E9;
    public const int GL_DYNAMIC_COPY = 0x000088EA;
    public const int GL_MAX_DRAW_BUFFERS = 0x00008824;
    public const int GL_DRAW_BUFFER0 = 0x00008825;
    public const int GL_DRAW_BUFFER1 = 0x00008826;
    public const int GL_DRAW_BUFFER2 = 0x00008827;
    public const int GL_DRAW_BUFFER3 = 0x00008828;
    public const int GL_DRAW_BUFFER4 = 0x00008829;
    public const int GL_DRAW_BUFFER5 = 0x0000882A;
    public const int GL_DRAW_BUFFER6 = 0x0000882B;
    public const int GL_DRAW_BUFFER7 = 0x0000882C;
    public const int GL_DRAW_BUFFER8 = 0x0000882D;
    public const int GL_DRAW_BUFFER9 = 0x0000882E;
    public const int GL_DRAW_BUFFER10 = 0x0000882F;
    public const int GL_DRAW_BUFFER11 = 0x00008830;
    public const int GL_DRAW_BUFFER12 = 0x00008831;
    public const int GL_DRAW_BUFFER13 = 0x00008832;
    public const int GL_DRAW_BUFFER14 = 0x00008833;
    public const int GL_DRAW_BUFFER15 = 0x00008834;
    public const int GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 0x00008B49;
    public const int GL_MAX_VERTEX_UNIFORM_COMPONENTS = 0x00008B4A;
    public const int GL_SAMPLER_3D = 0x00008B5F;
    public const int GL_SAMPLER_2D_SHADOW = 0x00008B62;
    public const int GL_FRAGMENT_SHADER_DERIVATIVE_HINT = 0x00008B8B;
    public const int GL_PIXEL_PACK_BUFFER = 0x000088EB;
    public const int GL_PIXEL_UNPACK_BUFFER = 0x000088EC;
    public const int GL_PIXEL_PACK_BUFFER_BINDING = 0x000088ED;
    public const int GL_PIXEL_UNPACK_BUFFER_BINDING = 0x000088EF;
    public const int GL_FLOAT_MAT2x3 = 0x00008B65;
    public const int GL_FLOAT_MAT2x4 = 0x00008B66;
    public const int GL_FLOAT_MAT3x2 = 0x00008B67;
    public const int GL_FLOAT_MAT3x4 = 0x00008B68;
    public const int GL_FLOAT_MAT4x2 = 0x00008B69;
    public const int GL_FLOAT_MAT4x3 = 0x00008B6A;
    public const int GL_SRGB = 0x00008C40;
    public const int GL_SRGB8 = 0x00008C41;
    public const int GL_SRGB8_ALPHA8 = 0x00008C43;
    public const int GL_COMPARE_REF_TO_TEXTURE = 0x0000884E;
    public const int GL_MAJOR_VERSION = 0x0000821B;
    public const int GL_MINOR_VERSION = 0x0000821C;
    public const int GL_NUM_EXTENSIONS = 0x0000821D;
    public const int GL_RGBA32F = 0x00008814;
    public const int GL_RGB32F = 0x00008815;
    public const int GL_RGBA16F = 0x0000881A;
    public const int GL_RGB16F = 0x0000881B;
    public const int GL_VERTEX_ATTRIB_ARRAY_INTEGER = 0x000088FD;
    public const int GL_MAX_ARRAY_TEXTURE_LAYERS = 0x000088FF;
    public const int GL_MIN_PROGRAM_TEXEL_OFFSET = 0x00008904;
    public const int GL_MAX_PROGRAM_TEXEL_OFFSET = 0x00008905;
    public const int GL_MAX_VARYING_COMPONENTS = 0x00008B4B;
    public const int GL_TEXTURE_2D_ARRAY = 0x00008C1A;
    public const int GL_TEXTURE_BINDING_2D_ARRAY = 0x00008C1D;
    public const int GL_R11F_G11F_B10F = 0x00008C3A;
    public const int GL_UNSIGNED_INT_10F_11F_11F_REV = 0x00008C3B;
    public const int GL_RGB9_E5 = 0x00008C3D;
    public const int GL_UNSIGNED_INT_5_9_9_9_REV = 0x00008C3E;
    public const int GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH = 0x00008C76;
    public const int GL_TRANSFORM_FEEDBACK_BUFFER_MODE = 0x00008C7F;
    public const int GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS = 0x00008C80;
    public const int GL_TRANSFORM_FEEDBACK_VARYINGS = 0x00008C83;
    public const int GL_TRANSFORM_FEEDBACK_BUFFER_START = 0x00008C84;
    public const int GL_TRANSFORM_FEEDBACK_BUFFER_SIZE = 0x00008C85;
    public const int GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = 0x00008C88;
    public const int GL_RASTERIZER_DISCARD = 0x00008C89;
    public const int GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = 0x00008C8A;
    public const int GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS = 0x00008C8B;
    public const int GL_INTERLEAVED_ATTRIBS = 0x00008C8C;
    public const int GL_SEPARATE_ATTRIBS = 0x00008C8D;
    public const int GL_TRANSFORM_FEEDBACK_BUFFER = 0x00008C8E;
    public const int GL_TRANSFORM_FEEDBACK_BUFFER_BINDING = 0x00008C8F;
    public const int GL_RGBA32UI = 0x00008D70;
    public const int GL_RGB32UI = 0x00008D71;
    public const int GL_RGBA16UI = 0x00008D76;
    public const int GL_RGB16UI = 0x00008D77;
    public const int GL_RGBA8UI = 0x00008D7C;
    public const int GL_RGB8UI = 0x00008D7D;
    public const int GL_RGBA32I = 0x00008D82;
    public const int GL_RGB32I = 0x00008D83;
    public const int GL_RGBA16I = 0x00008D88;
    public const int GL_RGB16I = 0x00008D89;
    public const int GL_RGBA8I = 0x00008D8E;
    public const int GL_RGB8I = 0x00008D8F;
    public const int GL_RED_INTEGER = 0x00008D94;
    public const int GL_RGB_INTEGER = 0x00008D98;
    public const int GL_RGBA_INTEGER = 0x00008D99;
    public const int GL_SAMPLER_2D_ARRAY = 0x00008DC1;
    public const int GL_SAMPLER_2D_ARRAY_SHADOW = 0x00008DC4;
    public const int GL_SAMPLER_CUBE_SHADOW = 0x00008DC5;
    public const int GL_UNSIGNED_INT_VEC2 = 0x00008DC6;
    public const int GL_UNSIGNED_INT_VEC3 = 0x00008DC7;
    public const int GL_UNSIGNED_INT_VEC4 = 0x00008DC8;
    public const int GL_INT_SAMPLER_2D = 0x00008DCA;
    public const int GL_INT_SAMPLER_3D = 0x00008DCB;
    public const int GL_INT_SAMPLER_CUBE = 0x00008DCC;
    public const int GL_INT_SAMPLER_2D_ARRAY = 0x00008DCF;
    public const int GL_UNSIGNED_INT_SAMPLER_2D = 0x00008DD2;
    public const int GL_UNSIGNED_INT_SAMPLER_3D = 0x00008DD3;
    public const int GL_UNSIGNED_INT_SAMPLER_CUBE = 0x00008DD4;
    public const int GL_UNSIGNED_INT_SAMPLER_2D_ARRAY = 0x00008DD7;
    public const int GL_BUFFER_ACCESS_FLAGS = 0x0000911F;
    public const int GL_BUFFER_MAP_LENGTH = 0x00009120;
    public const int GL_BUFFER_MAP_OFFSET = 0x00009121;
    public const int GL_DEPTH_COMPONENT32F = 0x00008CAC;
    public const int GL_DEPTH32F_STENCIL8 = 0x00008CAD;
    public const int GL_FLOAT_32_UNSIGNED_INT_24_8_REV = 0x00008DAD;
    public const int GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = 0x00008210;
    public const int GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = 0x00008211;
    public const int GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE = 0x00008212;
    public const int GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = 0x00008213;
    public const int GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = 0x00008214;
    public const int GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = 0x00008215;
    public const int GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = 0x00008216;
    public const int GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = 0x00008217;
    public const int GL_FRAMEBUFFER_DEFAULT = 0x00008218;
    public const int GL_FRAMEBUFFER_UNDEFINED = 0x00008219;
    public const int GL_DEPTH_STENCIL_ATTACHMENT = 0x0000821A;
    public const int GL_DEPTH_STENCIL = 0x000084F9;
    public const int GL_UNSIGNED_INT_24_8 = 0x000084FA;
    public const int GL_DEPTH24_STENCIL8 = 0x000088F0;
    public const int GL_UNSIGNED_NORMALIZED = 0x00008C17;
    public const int GL_DRAW_FRAMEBUFFER_BINDING = 0x00008CA6;
    public const int GL_READ_FRAMEBUFFER = 0x00008CA8;
    public const int GL_DRAW_FRAMEBUFFER = 0x00008CA9;
    public const int GL_READ_FRAMEBUFFER_BINDING = 0x00008CAA;
    public const int GL_RENDERBUFFER_SAMPLES = 0x00008CAB;
    public const int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = 0x00008CD4;
    public const int GL_MAX_COLOR_ATTACHMENTS = 0x00008CDF;
    public const int GL_COLOR_ATTACHMENT1 = 0x00008CE1;
    public const int GL_COLOR_ATTACHMENT2 = 0x00008CE2;
    public const int GL_COLOR_ATTACHMENT3 = 0x00008CE3;
    public const int GL_COLOR_ATTACHMENT4 = 0x00008CE4;
    public const int GL_COLOR_ATTACHMENT5 = 0x00008CE5;
    public const int GL_COLOR_ATTACHMENT6 = 0x00008CE6;
    public const int GL_COLOR_ATTACHMENT7 = 0x00008CE7;
    public const int GL_COLOR_ATTACHMENT8 = 0x00008CE8;
    public const int GL_COLOR_ATTACHMENT9 = 0x00008CE9;
    public const int GL_COLOR_ATTACHMENT10 = 0x00008CEA;
    public const int GL_COLOR_ATTACHMENT11 = 0x00008CEB;
    public const int GL_COLOR_ATTACHMENT12 = 0x00008CEC;
    public const int GL_COLOR_ATTACHMENT13 = 0x00008CED;
    public const int GL_COLOR_ATTACHMENT14 = 0x00008CEE;
    public const int GL_COLOR_ATTACHMENT15 = 0x00008CEF;
    public const int GL_COLOR_ATTACHMENT16 = 0x00008CF0;
    public const int GL_COLOR_ATTACHMENT17 = 0x00008CF1;
    public const int GL_COLOR_ATTACHMENT18 = 0x00008CF2;
    public const int GL_COLOR_ATTACHMENT19 = 0x00008CF3;
    public const int GL_COLOR_ATTACHMENT20 = 0x00008CF4;
    public const int GL_COLOR_ATTACHMENT21 = 0x00008CF5;
    public const int GL_COLOR_ATTACHMENT22 = 0x00008CF6;
    public const int GL_COLOR_ATTACHMENT23 = 0x00008CF7;
    public const int GL_COLOR_ATTACHMENT24 = 0x00008CF8;
    public const int GL_COLOR_ATTACHMENT25 = 0x00008CF9;
    public const int GL_COLOR_ATTACHMENT26 = 0x00008CFA;
    public const int GL_COLOR_ATTACHMENT27 = 0x00008CFB;
    public const int GL_COLOR_ATTACHMENT28 = 0x00008CFC;
    public const int GL_COLOR_ATTACHMENT29 = 0x00008CFD;
    public const int GL_COLOR_ATTACHMENT30 = 0x00008CFE;
    public const int GL_COLOR_ATTACHMENT31 = 0x00008CFF;
    public const int GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = 0x00008D56;
    public const int GL_MAX_SAMPLES = 0x00008D57;
    public const int GL_HALF_FLOAT = 0x0000140B;
    public const int GL_MAP_READ_BIT = 0x00000001;
    public const int GL_MAP_WRITE_BIT = 0x00000002;
    public const int GL_MAP_INVALIDATE_RANGE_BIT = 0x00000004;
    public const int GL_MAP_INVALIDATE_BUFFER_BIT = 0x00000008;
    public const int GL_MAP_FLUSH_EXPLICIT_BIT = 0x00000010;
    public const int GL_MAP_UNSYNCHRONIZED_BIT = 0x00000020;
    public const int GL_RG = 0x00008227;
    public const int GL_RG_INTEGER = 0x00008228;
    public const int GL_R8 = 0x00008229;
    public const int GL_RG8 = 0x0000822B;
    public const int GL_R16F = 0x0000822D;
    public const int GL_R32F = 0x0000822E;
    public const int GL_RG16F = 0x0000822F;
    public const int GL_RG32F = 0x00008230;
    public const int GL_R8I = 0x00008231;
    public const int GL_R8UI = 0x00008232;
    public const int GL_R16I = 0x00008233;
    public const int GL_R16UI = 0x00008234;
    public const int GL_R32I = 0x00008235;
    public const int GL_R32UI = 0x00008236;
    public const int GL_RG8I = 0x00008237;
    public const int GL_RG8UI = 0x00008238;
    public const int GL_RG16I = 0x00008239;
    public const int GL_RG16UI = 0x0000823A;
    public const int GL_RG32I = 0x0000823B;
    public const int GL_RG32UI = 0x0000823C;
    public const int GL_VERTEX_ARRAY_BINDING = 0x000085B5;
    public const int GL_R8_SNORM = 0x00008F94;
    public const int GL_RG8_SNORM = 0x00008F95;
    public const int GL_RGB8_SNORM = 0x00008F96;
    public const int GL_RGBA8_SNORM = 0x00008F97;
    public const int GL_SIGNED_NORMALIZED = 0x00008F9C;
    public const int GL_PRIMITIVE_RESTART_FIXED_INDEX = 0x00008D69;
    public const int GL_COPY_READ_BUFFER = 0x00008F36;
    public const int GL_COPY_WRITE_BUFFER = 0x00008F37;
    public const int GL_COPY_READ_BUFFER_BINDING = 0x00008F36;
    public const int GL_COPY_WRITE_BUFFER_BINDING = 0x00008F37;
    public const int GL_UNIFORM_BUFFER = 0x00008A11;
    public const int GL_UNIFORM_BUFFER_BINDING = 0x00008A28;
    public const int GL_UNIFORM_BUFFER_START = 0x00008A29;
    public const int GL_UNIFORM_BUFFER_SIZE = 0x00008A2A;
    public const int GL_MAX_VERTEX_UNIFORM_BLOCKS = 0x00008A2B;
    public const int GL_MAX_FRAGMENT_UNIFORM_BLOCKS = 0x00008A2D;
    public const int GL_MAX_COMBINED_UNIFORM_BLOCKS = 0x00008A2E;
    public const int GL_MAX_UNIFORM_BUFFER_BINDINGS = 0x00008A2F;
    public const int GL_MAX_UNIFORM_BLOCK_SIZE = 0x00008A30;
    public const int GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS = 0x00008A31;
    public const int GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS = 0x00008A33;
    public const int GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT = 0x00008A34;
    public const int GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH = 0x00008A35;
    public const int GL_ACTIVE_UNIFORM_BLOCKS = 0x00008A36;
    public const int GL_UNIFORM_TYPE = 0x00008A37;
    public const int GL_UNIFORM_SIZE = 0x00008A38;
    public const int GL_UNIFORM_NAME_LENGTH = 0x00008A39;
    public const int GL_UNIFORM_BLOCK_INDEX = 0x00008A3A;
    public const int GL_UNIFORM_OFFSET = 0x00008A3B;
    public const int GL_UNIFORM_ARRAY_STRIDE = 0x00008A3C;
    public const int GL_UNIFORM_MATRIX_STRIDE = 0x00008A3D;
    public const int GL_UNIFORM_IS_ROW_MAJOR = 0x00008A3E;
    public const int GL_UNIFORM_BLOCK_BINDING = 0x00008A3F;
    public const int GL_UNIFORM_BLOCK_DATA_SIZE = 0x00008A40;
    public const int GL_UNIFORM_BLOCK_NAME_LENGTH = 0x00008A41;
    public const int GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS = 0x00008A42;
    public const int GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES = 0x00008A43;
    public const int GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER = 0x00008A44;
    public const int GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER = 0x00008A46;
    public const uint GL_INVALID_INDEX = 0xFFFFFFFF;
    public const int GL_MAX_VERTEX_OUTPUT_COMPONENTS = 0x00009122;
    public const int GL_MAX_FRAGMENT_INPUT_COMPONENTS = 0x00009125;
    public const int GL_MAX_SERVER_WAIT_TIMEOUT = 0x00009111;
    public const int GL_OBJECT_TYPE = 0x00009112;
    public const int GL_SYNC_CONDITION = 0x00009113;
    public const int GL_SYNC_STATUS = 0x00009114;
    public const int GL_SYNC_FLAGS = 0x00009115;
    public const int GL_SYNC_FENCE = 0x00009116;
    public const int GL_SYNC_GPU_COMMANDS_COMPLETE = 0x00009117;
    public const int GL_UNSIGNALED = 0x00009118;
    public const int GL_SIGNALED = 0x00009119;
    public const int GL_ALREADY_SIGNALED = 0x0000911A;
    public const int GL_TIMEOUT_EXPIRED = 0x0000911B;
    public const int GL_CONDITION_SATISFIED = 0x0000911C;
    public const int GL_WAIT_FAILED = 0x0000911D;
    public const int GL_SYNC_FLUSH_COMMANDS_BIT = 0x00000001;
    public const ulong GL_TIMEOUT_IGNORED = 0xFFFFFFFFFFFFFFFF;
    public const int GL_VERTEX_ATTRIB_ARRAY_DIVISOR = 0x000088FE;
    public const int GL_ANY_SAMPLES_PASSED = 0x00008C2F;
    public const int GL_ANY_SAMPLES_PASSED_CONSERVATIVE = 0x00008D6A;
    public const int GL_SAMPLER_BINDING = 0x00008919;
    public const int GL_RGB10_A2UI = 0x0000906F;
    public const int GL_TEXTURE_SWIZZLE_R = 0x00008E42;
    public const int GL_TEXTURE_SWIZZLE_G = 0x00008E43;
    public const int GL_TEXTURE_SWIZZLE_B = 0x00008E44;
    public const int GL_TEXTURE_SWIZZLE_A = 0x00008E45;
    public const int GL_GREEN = 0x00001904;
    public const int GL_BLUE = 0x00001905;
    public const int GL_INT_2_10_10_10_REV = 0x00008D9F;
    public const int GL_TRANSFORM_FEEDBACK = 0x00008E22;
    public const int GL_TRANSFORM_FEEDBACK_PAUSED = 0x00008E23;
    public const int GL_TRANSFORM_FEEDBACK_ACTIVE = 0x00008E24;
    public const int GL_TRANSFORM_FEEDBACK_BINDING = 0x00008E25;
    public const int GL_PROGRAM_BINARY_RETRIEVABLE_HINT = 0x00008257;
    public const int GL_PROGRAM_BINARY_LENGTH = 0x00008741;
    public const int GL_NUM_PROGRAM_BINARY_FORMATS = 0x000087FE;
    public const int GL_PROGRAM_BINARY_FORMATS = 0x000087FF;
    public const int GL_COMPRESSED_R11_EAC = 0x00009270;
    public const int GL_COMPRESSED_SIGNED_R11_EAC = 0x00009271;
    public const int GL_COMPRESSED_RG11_EAC = 0x00009272;
    public const int GL_COMPRESSED_SIGNED_RG11_EAC = 0x00009273;
    public const int GL_COMPRESSED_RGB8_ETC2 = 0x00009274;
    public const int GL_COMPRESSED_SRGB8_ETC2 = 0x00009275;
    public const int GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x00009276;
    public const int GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x00009277;
    public const int GL_COMPRESSED_RGBA8_ETC2_EAC = 0x00009278;
    public const int GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC = 0x00009279;
    public const int GL_TEXTURE_IMMUTABLE_FORMAT = 0x0000912F;
    public const int GL_MAX_ELEMENT_INDEX = 0x00008D6B;
    public const int GL_NUM_SAMPLE_COUNTS = 0x00009380;
    public const int GL_TEXTURE_IMMUTABLE_LEVELS = 0x000082DF;
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, void> _glReadBuffer = null;
    internal static delegate* unmanaged<uint, uint, uint, int, uint, void*, void> _glDrawRangeElements = null;
    internal static delegate* unmanaged<uint, int, int, int, int, int, int, uint, uint, void*, void> _glTexImage3D = null;
    internal static delegate* unmanaged<uint, int, int, int, int, int, int, int, uint, uint, void*, void> _glTexSubImage3D = null;
    internal static delegate* unmanaged<uint, int, int, int, int, int, int, int, int, void> _glCopyTexSubImage3D = null;
    internal static delegate* unmanaged<uint, int, uint, int, int, int, int, int, void*, void> _glCompressedTexImage3D = null;
    internal static delegate* unmanaged<uint, int, int, int, int, int, int, int, uint, int, void*, void> _glCompressedTexSubImage3D = null;
    internal static delegate* unmanaged<int, uint*, void> _glGenQueries = null;
    internal static delegate* unmanaged<int, uint*, void> _glDeleteQueries = null;
    internal static delegate* unmanaged<uint, bool> _glIsQuery = null;
    internal static delegate* unmanaged<uint, uint, void> _glBeginQuery = null;
    internal static delegate* unmanaged<uint, void> _glEndQuery = null;
    internal static delegate* unmanaged<uint, uint, int*, void> _glGetQueryiv = null;
    internal static delegate* unmanaged<uint, uint, uint*, void> _glGetQueryObjectuiv = null;
    internal static delegate* unmanaged<uint, bool> _glUnmapBuffer = null;
    internal static delegate* unmanaged<uint, uint, void**, void> _glGetBufferPointerv = null;
    internal static delegate* unmanaged<int, uint*, void> _glDrawBuffers = null;
    internal static delegate* unmanaged<int, int, bool, float*, void> _glUniformMatrix2x3fv = null;
    internal static delegate* unmanaged<int, int, bool, float*, void> _glUniformMatrix3x2fv = null;
    internal static delegate* unmanaged<int, int, bool, float*, void> _glUniformMatrix2x4fv = null;
    internal static delegate* unmanaged<int, int, bool, float*, void> _glUniformMatrix4x2fv = null;
    internal static delegate* unmanaged<int, int, bool, float*, void> _glUniformMatrix3x4fv = null;
    internal static delegate* unmanaged<int, int, bool, float*, void> _glUniformMatrix4x3fv = null;
    internal static delegate* unmanaged<int, int, int, int, int, int, int, int, uint, uint, void> _glBlitFramebuffer = null;
    internal static delegate* unmanaged<uint, int, uint, int, int, void> _glRenderbufferStorageMultisample = null;
    internal static delegate* unmanaged<uint, uint, uint, int, int, void> _glFramebufferTextureLayer = null;
    internal static delegate* unmanaged<uint, nint, nint, uint, void*> _glMapBufferRange = null;
    internal static delegate* unmanaged<uint, nint, nint, void> _glFlushMappedBufferRange = null;
    internal static delegate* unmanaged<uint, void> _glBindVertexArray = null;
    internal static delegate* unmanaged<int, uint*, void> _glDeleteVertexArrays = null;
    internal static delegate* unmanaged<int, uint*, void> _glGenVertexArrays = null;
    internal static delegate* unmanaged<uint, bool> _glIsVertexArray = null;
    internal static delegate* unmanaged<uint, uint, int*, void> _glGetIntegeri_v = null;
    internal static delegate* unmanaged<uint, void> _glBeginTransformFeedback = null;
    internal static delegate* unmanaged<void> _glEndTransformFeedback = null;
    internal static delegate* unmanaged<uint, uint, uint, nint, nint, void> _glBindBufferRange = null;
    internal static delegate* unmanaged<uint, uint, uint, void> _glBindBufferBase = null;
    internal static delegate* unmanaged<uint, int, nint, uint, void> _glTransformFeedbackVaryings = null;
    internal static delegate* unmanaged<uint, uint, int, int*, int*, uint*, byte*, void> _glGetTransformFeedbackVarying = null;
    internal static delegate* unmanaged<uint, int, uint, int, void*, void> _glVertexAttribIPointer = null;
    internal static delegate* unmanaged<uint, uint, int*, void> _glGetVertexAttribIiv = null;
    internal static delegate* unmanaged<uint, uint, uint*, void> _glGetVertexAttribIuiv = null;
    internal static delegate* unmanaged<uint, int, int, int, int, void> _glVertexAttribI4i = null;
    internal static delegate* unmanaged<uint, uint, uint, uint, uint, void> _glVertexAttribI4ui = null;
    internal static delegate* unmanaged<uint, int*, void> _glVertexAttribI4iv = null;
    internal static delegate* unmanaged<uint, uint*, void> _glVertexAttribI4uiv = null;
    internal static delegate* unmanaged<uint, int, uint*, void> _glGetUniformuiv = null;
    internal static delegate* unmanaged<uint, byte*, int> _glGetFragDataLocation = null;
    internal static delegate* unmanaged<int, uint, void> _glUniform1ui = null;
    internal static delegate* unmanaged<int, uint, uint, void> _glUniform2ui = null;
    internal static delegate* unmanaged<int, uint, uint, uint, void> _glUniform3ui = null;
    internal static delegate* unmanaged<int, uint, uint, uint, uint, void> _glUniform4ui = null;
    internal static delegate* unmanaged<int, int, uint*, void> _glUniform1uiv = null;
    internal static delegate* unmanaged<int, int, uint*, void> _glUniform2uiv = null;
    internal static delegate* unmanaged<int, int, uint*, void> _glUniform3uiv = null;
    internal static delegate* unmanaged<int, int, uint*, void> _glUniform4uiv = null;
    internal static delegate* unmanaged<uint, int, int*, void> _glClearBufferiv = null;
    internal static delegate* unmanaged<uint, int, uint*, void> _glClearBufferuiv = null;
    internal static delegate* unmanaged<uint, int, float*, void> _glClearBufferfv = null;
    internal static delegate* unmanaged<uint, int, float, int, void> _glClearBufferfi = null;
    internal static delegate* unmanaged<uint, uint, byte*> _glGetStringi = null;
    internal static delegate* unmanaged<uint, uint, nint, nint, nint, void> _glCopyBufferSubData = null;
    internal static delegate* unmanaged<uint, int, nint, uint*, void> _glGetUniformIndices = null;
    internal static delegate* unmanaged<uint, int, uint*, uint, int*, void> _glGetActiveUniformsiv = null;
    internal static delegate* unmanaged<uint, byte*, uint> _glGetUniformBlockIndex = null;
    internal static delegate* unmanaged<uint, uint, uint, int*, void> _glGetActiveUniformBlockiv = null;
    internal static delegate* unmanaged<uint, uint, int, int*, byte*, void> _glGetActiveUniformBlockName = null;
    internal static delegate* unmanaged<uint, uint, uint, void> _glUniformBlockBinding = null;
    internal static delegate* unmanaged<uint, int, int, int, void> _glDrawArraysInstanced = null;
    internal static delegate* unmanaged<uint, int, uint, void*, int, void> _glDrawElementsInstanced = null;
    internal static delegate* unmanaged<uint, uint, nint> _glFenceSync = null;
    internal static delegate* unmanaged<nint, bool> _glIsSync = null;
    internal static delegate* unmanaged<nint, void> _glDeleteSync = null;
    internal static delegate* unmanaged<nint, uint, ulong, uint> _glClientWaitSync = null;
    internal static delegate* unmanaged<nint, uint, ulong, void> _glWaitSync = null;
    internal static delegate* unmanaged<uint, long*, void> _glGetInteger64v = null;
    internal static delegate* unmanaged<nint, uint, int, int*, int*, void> _glGetSynciv = null;
    internal static delegate* unmanaged<uint, uint, long*, void> _glGetInteger64i_v = null;
    internal static delegate* unmanaged<uint, uint, long*, void> _glGetBufferParameteri64v = null;
    internal static delegate* unmanaged<int, uint*, void> _glGenSamplers = null;
    internal static delegate* unmanaged<int, uint*, void> _glDeleteSamplers = null;
    internal static delegate* unmanaged<uint, bool> _glIsSampler = null;
    internal static delegate* unmanaged<uint, uint, void> _glBindSampler = null;
    internal static delegate* unmanaged<uint, uint, int, void> _glSamplerParameteri = null;
    internal static delegate* unmanaged<uint, uint, int*, void> _glSamplerParameteriv = null;
    internal static delegate* unmanaged<uint, uint, float, void> _glSamplerParameterf = null;
    internal static delegate* unmanaged<uint, uint, float*, void> _glSamplerParameterfv = null;
    internal static delegate* unmanaged<uint, uint, int*, void> _glGetSamplerParameteriv = null;
    internal static delegate* unmanaged<uint, uint, float*, void> _glGetSamplerParameterfv = null;
    internal static delegate* unmanaged<uint, uint, void> _glVertexAttribDivisor = null;
    internal static delegate* unmanaged<uint, uint, void> _glBindTransformFeedback = null;
    internal static delegate* unmanaged<int, uint*, void> _glDeleteTransformFeedbacks = null;
    internal static delegate* unmanaged<int, uint*, void> _glGenTransformFeedbacks = null;
    internal static delegate* unmanaged<uint, bool> _glIsTransformFeedback = null;
    internal static delegate* unmanaged<void> _glPauseTransformFeedback = null;
    internal static delegate* unmanaged<void> _glResumeTransformFeedback = null;
    internal static delegate* unmanaged<uint, int, int*, uint*, void*, void> _glGetProgramBinary = null;
    internal static delegate* unmanaged<uint, uint, void*, int, void> _glProgramBinary = null;
    internal static delegate* unmanaged<uint, uint, int, void> _glProgramParameteri = null;
    internal static delegate* unmanaged<uint, int, uint*, void> _glInvalidateFramebuffer = null;
    internal static delegate* unmanaged<uint, int, uint*, int, int, int, int, void> _glInvalidateSubFramebuffer = null;
    internal static delegate* unmanaged<uint, int, uint, int, int, void> _glTexStorage2D = null;
    internal static delegate* unmanaged<uint, int, uint, int, int, int, void> _glTexStorage3D = null;
    internal static delegate* unmanaged<uint, uint, uint, int, int*, void> _glGetInternalformativ = null;

    internal static void Load()
    {
        _glReadBuffer = (delegate* unmanaged<uint, void>)QuickGL.GetGLProcAddress("glReadBuffer");
        _glDrawRangeElements = (delegate* unmanaged<uint, uint, uint, int, uint, void*, void>)QuickGL.GetGLProcAddress("glDrawRangeElements");
        _glTexImage3D = (delegate* unmanaged<uint, int, int, int, int, int, int, uint, uint, void*, void>)QuickGL.GetGLProcAddress("glTexImage3D");
        _glTexSubImage3D = (delegate* unmanaged<uint, int, int, int, int, int, int, int, uint, uint, void*, void>)QuickGL.GetGLProcAddress("glTexSubImage3D");
        _glCopyTexSubImage3D = (delegate* unmanaged<uint, int, int, int, int, int, int, int, int, void>)QuickGL.GetGLProcAddress("glCopyTexSubImage3D");
        _glCompressedTexImage3D = (delegate* unmanaged<uint, int, uint, int, int, int, int, int, void*, void>)QuickGL.GetGLProcAddress("glCompressedTexImage3D");
        _glCompressedTexSubImage3D = (delegate* unmanaged<uint, int, int, int, int, int, int, int, uint, int, void*, void>)QuickGL.GetGLProcAddress("glCompressedTexSubImage3D");
        _glGenQueries = (delegate* unmanaged<int, uint*, void>)QuickGL.GetGLProcAddress("glGenQueries");
        _glDeleteQueries = (delegate* unmanaged<int, uint*, void>)QuickGL.GetGLProcAddress("glDeleteQueries");
        _glIsQuery = (delegate* unmanaged<uint, bool>)QuickGL.GetGLProcAddress("glIsQuery");
        _glBeginQuery = (delegate* unmanaged<uint, uint, void>)QuickGL.GetGLProcAddress("glBeginQuery");
        _glEndQuery = (delegate* unmanaged<uint, void>)QuickGL.GetGLProcAddress("glEndQuery");
        _glGetQueryiv = (delegate* unmanaged<uint, uint, int*, void>)QuickGL.GetGLProcAddress("glGetQueryiv");
        _glGetQueryObjectuiv = (delegate* unmanaged<uint, uint, uint*, void>)QuickGL.GetGLProcAddress("glGetQueryObjectuiv");
        _glUnmapBuffer = (delegate* unmanaged<uint, bool>)QuickGL.GetGLProcAddress("glUnmapBuffer");
        _glGetBufferPointerv = (delegate* unmanaged<uint, uint, void**, void>)QuickGL.GetGLProcAddress("glGetBufferPointerv");
        _glDrawBuffers = (delegate* unmanaged<int, uint*, void>)QuickGL.GetGLProcAddress("glDrawBuffers");
        _glUniformMatrix2x3fv = (delegate* unmanaged<int, int, bool, float*, void>)QuickGL.GetGLProcAddress("glUniformMatrix2x3fv");
        _glUniformMatrix3x2fv = (delegate* unmanaged<int, int, bool, float*, void>)QuickGL.GetGLProcAddress("glUniformMatrix3x2fv");
        _glUniformMatrix2x4fv = (delegate* unmanaged<int, int, bool, float*, void>)QuickGL.GetGLProcAddress("glUniformMatrix2x4fv");
        _glUniformMatrix4x2fv = (delegate* unmanaged<int, int, bool, float*, void>)QuickGL.GetGLProcAddress("glUniformMatrix4x2fv");
        _glUniformMatrix3x4fv = (delegate* unmanaged<int, int, bool, float*, void>)QuickGL.GetGLProcAddress("glUniformMatrix3x4fv");
        _glUniformMatrix4x3fv = (delegate* unmanaged<int, int, bool, float*, void>)QuickGL.GetGLProcAddress("glUniformMatrix4x3fv");
        _glBlitFramebuffer = (delegate* unmanaged<int, int, int, int, int, int, int, int, uint, uint, void>)QuickGL.GetGLProcAddress("glBlitFramebuffer");
        _glRenderbufferStorageMultisample = (delegate* unmanaged<uint, int, uint, int, int, void>)QuickGL.GetGLProcAddress("glRenderbufferStorageMultisample");
        _glFramebufferTextureLayer = (delegate* unmanaged<uint, uint, uint, int, int, void>)QuickGL.GetGLProcAddress("glFramebufferTextureLayer");
        _glMapBufferRange = (delegate* unmanaged<uint, nint, nint, uint, void*>)QuickGL.GetGLProcAddress("glMapBufferRange");
        _glFlushMappedBufferRange = (delegate* unmanaged<uint, nint, nint, void>)QuickGL.GetGLProcAddress("glFlushMappedBufferRange");
        _glBindVertexArray = (delegate* unmanaged<uint, void>)QuickGL.GetGLProcAddress("glBindVertexArray");
        _glDeleteVertexArrays = (delegate* unmanaged<int, uint*, void>)QuickGL.GetGLProcAddress("glDeleteVertexArrays");
        _glGenVertexArrays = (delegate* unmanaged<int, uint*, void>)QuickGL.GetGLProcAddress("glGenVertexArrays");
        _glIsVertexArray = (delegate* unmanaged<uint, bool>)QuickGL.GetGLProcAddress("glIsVertexArray");
        _glGetIntegeri_v = (delegate* unmanaged<uint, uint, int*, void>)QuickGL.GetGLProcAddress("glGetIntegeri_v");
        _glBeginTransformFeedback = (delegate* unmanaged<uint, void>)QuickGL.GetGLProcAddress("glBeginTransformFeedback");
        _glEndTransformFeedback = (delegate* unmanaged<void>)QuickGL.GetGLProcAddress("glEndTransformFeedback");
        _glBindBufferRange = (delegate* unmanaged<uint, uint, uint, nint, nint, void>)QuickGL.GetGLProcAddress("glBindBufferRange");
        _glBindBufferBase = (delegate* unmanaged<uint, uint, uint, void>)QuickGL.GetGLProcAddress("glBindBufferBase");
        _glTransformFeedbackVaryings = (delegate* unmanaged<uint, int, nint, uint, void>)QuickGL.GetGLProcAddress("glTransformFeedbackVaryings");
        _glGetTransformFeedbackVarying = (delegate* unmanaged<uint, uint, int, int*, int*, uint*, byte*, void>)QuickGL.GetGLProcAddress("glGetTransformFeedbackVarying");
        _glVertexAttribIPointer = (delegate* unmanaged<uint, int, uint, int, void*, void>)QuickGL.GetGLProcAddress("glVertexAttribIPointer");
        _glGetVertexAttribIiv = (delegate* unmanaged<uint, uint, int*, void>)QuickGL.GetGLProcAddress("glGetVertexAttribIiv");
        _glGetVertexAttribIuiv = (delegate* unmanaged<uint, uint, uint*, void>)QuickGL.GetGLProcAddress("glGetVertexAttribIuiv");
        _glVertexAttribI4i = (delegate* unmanaged<uint, int, int, int, int, void>)QuickGL.GetGLProcAddress("glVertexAttribI4i");
        _glVertexAttribI4ui = (delegate* unmanaged<uint, uint, uint, uint, uint, void>)QuickGL.GetGLProcAddress("glVertexAttribI4ui");
        _glVertexAttribI4iv = (delegate* unmanaged<uint, int*, void>)QuickGL.GetGLProcAddress("glVertexAttribI4iv");
        _glVertexAttribI4uiv = (delegate* unmanaged<uint, uint*, void>)QuickGL.GetGLProcAddress("glVertexAttribI4uiv");
        _glGetUniformuiv = (delegate* unmanaged<uint, int, uint*, void>)QuickGL.GetGLProcAddress("glGetUniformuiv");
        _glGetFragDataLocation = (delegate* unmanaged<uint, byte*, int>)QuickGL.GetGLProcAddress("glGetFragDataLocation");
        _glUniform1ui = (delegate* unmanaged<int, uint, void>)QuickGL.GetGLProcAddress("glUniform1ui");
        _glUniform2ui = (delegate* unmanaged<int, uint, uint, void>)QuickGL.GetGLProcAddress("glUniform2ui");
        _glUniform3ui = (delegate* unmanaged<int, uint, uint, uint, void>)QuickGL.GetGLProcAddress("glUniform3ui");
        _glUniform4ui = (delegate* unmanaged<int, uint, uint, uint, uint, void>)QuickGL.GetGLProcAddress("glUniform4ui");
        _glUniform1uiv = (delegate* unmanaged<int, int, uint*, void>)QuickGL.GetGLProcAddress("glUniform1uiv");
        _glUniform2uiv = (delegate* unmanaged<int, int, uint*, void>)QuickGL.GetGLProcAddress("glUniform2uiv");
        _glUniform3uiv = (delegate* unmanaged<int, int, uint*, void>)QuickGL.GetGLProcAddress("glUniform3uiv");
        _glUniform4uiv = (delegate* unmanaged<int, int, uint*, void>)QuickGL.GetGLProcAddress("glUniform4uiv");
        _glClearBufferiv = (delegate* unmanaged<uint, int, int*, void>)QuickGL.GetGLProcAddress("glClearBufferiv");
        _glClearBufferuiv = (delegate* unmanaged<uint, int, uint*, void>)QuickGL.GetGLProcAddress("glClearBufferuiv");
        _glClearBufferfv = (delegate* unmanaged<uint, int, float*, void>)QuickGL.GetGLProcAddress("glClearBufferfv");
        _glClearBufferfi = (delegate* unmanaged<uint, int, float, int, void>)QuickGL.GetGLProcAddress("glClearBufferfi");
        _glGetStringi = (delegate* unmanaged<uint, uint, byte*>)QuickGL.GetGLProcAddress("glGetStringi");
        _glCopyBufferSubData = (delegate* unmanaged<uint, uint, nint, nint, nint, void>)QuickGL.GetGLProcAddress("glCopyBufferSubData");
        _glGetUniformIndices = (delegate* unmanaged<uint, int, nint, uint*, void>)QuickGL.GetGLProcAddress("glGetUniformIndices");
        _glGetActiveUniformsiv = (delegate* unmanaged<uint, int, uint*, uint, int*, void>)QuickGL.GetGLProcAddress("glGetActiveUniformsiv");
        _glGetUniformBlockIndex = (delegate* unmanaged<uint, byte*, uint>)QuickGL.GetGLProcAddress("glGetUniformBlockIndex");
        _glGetActiveUniformBlockiv = (delegate* unmanaged<uint, uint, uint, int*, void>)QuickGL.GetGLProcAddress("glGetActiveUniformBlockiv");
        _glGetActiveUniformBlockName = (delegate* unmanaged<uint, uint, int, int*, byte*, void>)QuickGL.GetGLProcAddress("glGetActiveUniformBlockName");
        _glUniformBlockBinding = (delegate* unmanaged<uint, uint, uint, void>)QuickGL.GetGLProcAddress("glUniformBlockBinding");
        _glDrawArraysInstanced = (delegate* unmanaged<uint, int, int, int, void>)QuickGL.GetGLProcAddress("glDrawArraysInstanced");
        _glDrawElementsInstanced = (delegate* unmanaged<uint, int, uint, void*, int, void>)QuickGL.GetGLProcAddress("glDrawElementsInstanced");
        _glFenceSync = (delegate* unmanaged<uint, uint, nint>)QuickGL.GetGLProcAddress("glFenceSync");
        _glIsSync = (delegate* unmanaged<nint, bool>)QuickGL.GetGLProcAddress("glIsSync");
        _glDeleteSync = (delegate* unmanaged<nint, void>)QuickGL.GetGLProcAddress("glDeleteSync");
        _glClientWaitSync = (delegate* unmanaged<nint, uint, ulong, uint>)QuickGL.GetGLProcAddress("glClientWaitSync");
        _glWaitSync = (delegate* unmanaged<nint, uint, ulong, void>)QuickGL.GetGLProcAddress("glWaitSync");
        _glGetInteger64v = (delegate* unmanaged<uint, long*, void>)QuickGL.GetGLProcAddress("glGetInteger64v");
        _glGetSynciv = (delegate* unmanaged<nint, uint, int, int*, int*, void>)QuickGL.GetGLProcAddress("glGetSynciv");
        _glGetInteger64i_v = (delegate* unmanaged<uint, uint, long*, void>)QuickGL.GetGLProcAddress("glGetInteger64i_v");
        _glGetBufferParameteri64v = (delegate* unmanaged<uint, uint, long*, void>)QuickGL.GetGLProcAddress("glGetBufferParameteri64v");
        _glGenSamplers = (delegate* unmanaged<int, uint*, void>)QuickGL.GetGLProcAddress("glGenSamplers");
        _glDeleteSamplers = (delegate* unmanaged<int, uint*, void>)QuickGL.GetGLProcAddress("glDeleteSamplers");
        _glIsSampler = (delegate* unmanaged<uint, bool>)QuickGL.GetGLProcAddress("glIsSampler");
        _glBindSampler = (delegate* unmanaged<uint, uint, void>)QuickGL.GetGLProcAddress("glBindSampler");
        _glSamplerParameteri = (delegate* unmanaged<uint, uint, int, void>)QuickGL.GetGLProcAddress("glSamplerParameteri");
        _glSamplerParameteriv = (delegate* unmanaged<uint, uint, int*, void>)QuickGL.GetGLProcAddress("glSamplerParameteriv");
        _glSamplerParameterf = (delegate* unmanaged<uint, uint, float, void>)QuickGL.GetGLProcAddress("glSamplerParameterf");
        _glSamplerParameterfv = (delegate* unmanaged<uint, uint, float*, void>)QuickGL.GetGLProcAddress("glSamplerParameterfv");
        _glGetSamplerParameteriv = (delegate* unmanaged<uint, uint, int*, void>)QuickGL.GetGLProcAddress("glGetSamplerParameteriv");
        _glGetSamplerParameterfv = (delegate* unmanaged<uint, uint, float*, void>)QuickGL.GetGLProcAddress("glGetSamplerParameterfv");
        _glVertexAttribDivisor = (delegate* unmanaged<uint, uint, void>)QuickGL.GetGLProcAddress("glVertexAttribDivisor");
        _glBindTransformFeedback = (delegate* unmanaged<uint, uint, void>)QuickGL.GetGLProcAddress("glBindTransformFeedback");
        _glDeleteTransformFeedbacks = (delegate* unmanaged<int, uint*, void>)QuickGL.GetGLProcAddress("glDeleteTransformFeedbacks");
        _glGenTransformFeedbacks = (delegate* unmanaged<int, uint*, void>)QuickGL.GetGLProcAddress("glGenTransformFeedbacks");
        _glIsTransformFeedback = (delegate* unmanaged<uint, bool>)QuickGL.GetGLProcAddress("glIsTransformFeedback");
        _glPauseTransformFeedback = (delegate* unmanaged<void>)QuickGL.GetGLProcAddress("glPauseTransformFeedback");
        _glResumeTransformFeedback = (delegate* unmanaged<void>)QuickGL.GetGLProcAddress("glResumeTransformFeedback");
        _glGetProgramBinary = (delegate* unmanaged<uint, int, int*, uint*, void*, void>)QuickGL.GetGLProcAddress("glGetProgramBinary");
        _glProgramBinary = (delegate* unmanaged<uint, uint, void*, int, void>)QuickGL.GetGLProcAddress("glProgramBinary");
        _glProgramParameteri = (delegate* unmanaged<uint, uint, int, void>)QuickGL.GetGLProcAddress("glProgramParameteri");
        _glInvalidateFramebuffer = (delegate* unmanaged<uint, int, uint*, void>)QuickGL.GetGLProcAddress("glInvalidateFramebuffer");
        _glInvalidateSubFramebuffer = (delegate* unmanaged<uint, int, uint*, int, int, int, int, void>)QuickGL.GetGLProcAddress("glInvalidateSubFramebuffer");
        _glTexStorage2D = (delegate* unmanaged<uint, int, uint, int, int, void>)QuickGL.GetGLProcAddress("glTexStorage2D");
        _glTexStorage3D = (delegate* unmanaged<uint, int, uint, int, int, int, void>)QuickGL.GetGLProcAddress("glTexStorage3D");
        _glGetInternalformativ = (delegate* unmanaged<uint, uint, uint, int, int*, void>)QuickGL.GetGLProcAddress("glGetInternalformativ");
    }

    internal static void Unload()
    {
        _glReadBuffer = null;
        _glDrawRangeElements = null;
        _glTexImage3D = null;
        _glTexSubImage3D = null;
        _glCopyTexSubImage3D = null;
        _glCompressedTexImage3D = null;
        _glCompressedTexSubImage3D = null;
        _glGenQueries = null;
        _glDeleteQueries = null;
        _glIsQuery = null;
        _glBeginQuery = null;
        _glEndQuery = null;
        _glGetQueryiv = null;
        _glGetQueryObjectuiv = null;
        _glUnmapBuffer = null;
        _glGetBufferPointerv = null;
        _glDrawBuffers = null;
        _glUniformMatrix2x3fv = null;
        _glUniformMatrix3x2fv = null;
        _glUniformMatrix2x4fv = null;
        _glUniformMatrix4x2fv = null;
        _glUniformMatrix3x4fv = null;
        _glUniformMatrix4x3fv = null;
        _glBlitFramebuffer = null;
        _glRenderbufferStorageMultisample = null;
        _glFramebufferTextureLayer = null;
        _glMapBufferRange = null;
        _glFlushMappedBufferRange = null;
        _glBindVertexArray = null;
        _glDeleteVertexArrays = null;
        _glGenVertexArrays = null;
        _glIsVertexArray = null;
        _glGetIntegeri_v = null;
        _glBeginTransformFeedback = null;
        _glEndTransformFeedback = null;
        _glBindBufferRange = null;
        _glBindBufferBase = null;
        _glTransformFeedbackVaryings = null;
        _glGetTransformFeedbackVarying = null;
        _glVertexAttribIPointer = null;
        _glGetVertexAttribIiv = null;
        _glGetVertexAttribIuiv = null;
        _glVertexAttribI4i = null;
        _glVertexAttribI4ui = null;
        _glVertexAttribI4iv = null;
        _glVertexAttribI4uiv = null;
        _glGetUniformuiv = null;
        _glGetFragDataLocation = null;
        _glUniform1ui = null;
        _glUniform2ui = null;
        _glUniform3ui = null;
        _glUniform4ui = null;
        _glUniform1uiv = null;
        _glUniform2uiv = null;
        _glUniform3uiv = null;
        _glUniform4uiv = null;
        _glClearBufferiv = null;
        _glClearBufferuiv = null;
        _glClearBufferfv = null;
        _glClearBufferfi = null;
        _glGetStringi = null;
        _glCopyBufferSubData = null;
        _glGetUniformIndices = null;
        _glGetActiveUniformsiv = null;
        _glGetUniformBlockIndex = null;
        _glGetActiveUniformBlockiv = null;
        _glGetActiveUniformBlockName = null;
        _glUniformBlockBinding = null;
        _glDrawArraysInstanced = null;
        _glDrawElementsInstanced = null;
        _glFenceSync = null;
        _glIsSync = null;
        _glDeleteSync = null;
        _glClientWaitSync = null;
        _glWaitSync = null;
        _glGetInteger64v = null;
        _glGetSynciv = null;
        _glGetInteger64i_v = null;
        _glGetBufferParameteri64v = null;
        _glGenSamplers = null;
        _glDeleteSamplers = null;
        _glIsSampler = null;
        _glBindSampler = null;
        _glSamplerParameteri = null;
        _glSamplerParameteriv = null;
        _glSamplerParameterf = null;
        _glSamplerParameterfv = null;
        _glGetSamplerParameteriv = null;
        _glGetSamplerParameterfv = null;
        _glVertexAttribDivisor = null;
        _glBindTransformFeedback = null;
        _glDeleteTransformFeedbacks = null;
        _glGenTransformFeedbacks = null;
        _glIsTransformFeedback = null;
        _glPauseTransformFeedback = null;
        _glResumeTransformFeedback = null;
        _glGetProgramBinary = null;
        _glProgramBinary = null;
        _glProgramParameteri = null;
        _glInvalidateFramebuffer = null;
        _glInvalidateSubFramebuffer = null;
        _glTexStorage2D = null;
        _glTexStorage3D = null;
        _glGetInternalformativ = null;
    }
    #endregion

    #region Function wrappers
    public static void glReadBuffer(uint src) { QGLFeature.VerifyFunc((nint)_glReadBuffer); _glReadBuffer(src); }
    public static void glDrawRangeElements(uint mode, uint start, uint end, int count, uint type, void* indices) { QGLFeature.VerifyFunc((nint)_glDrawRangeElements); _glDrawRangeElements(mode, start, end, count, type, indices); }
    public static void glTexImage3D(uint target, int level, int internalformat, int width, int height, int depth, int border, uint format, uint type, void* pixels) { QGLFeature.VerifyFunc((nint)_glTexImage3D); _glTexImage3D(target, level, internalformat, width, height, depth, border, format, type, pixels); }
    public static void glTexSubImage3D(uint target, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, uint format, uint type, void* pixels) { QGLFeature.VerifyFunc((nint)_glTexSubImage3D); _glTexSubImage3D(target, level, xoffset, yoffset, zoffset, width, height, depth, format, type, pixels); }
    public static void glCopyTexSubImage3D(uint target, int level, int xoffset, int yoffset, int zoffset, int x, int y, int width, int height) { QGLFeature.VerifyFunc((nint)_glCopyTexSubImage3D); _glCopyTexSubImage3D(target, level, xoffset, yoffset, zoffset, x, y, width, height); }
    public static void glCompressedTexImage3D(uint target, int level, uint internalformat, int width, int height, int depth, int border, int imageSize, void* data) { QGLFeature.VerifyFunc((nint)_glCompressedTexImage3D); _glCompressedTexImage3D(target, level, internalformat, width, height, depth, border, imageSize, data); }
    public static void glCompressedTexSubImage3D(uint target, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, uint format, int imageSize, void* data) { QGLFeature.VerifyFunc((nint)_glCompressedTexSubImage3D); _glCompressedTexSubImage3D(target, level, xoffset, yoffset, zoffset, width, height, depth, format, imageSize, data); }
    public static void glGenQueries(int n, uint* ids) { QGLFeature.VerifyFunc((nint)_glGenQueries); _glGenQueries(n, ids); }
    public static void glDeleteQueries(int n, uint* ids) { QGLFeature.VerifyFunc((nint)_glDeleteQueries); _glDeleteQueries(n, ids); }
    public static bool glIsQuery(uint id) { QGLFeature.VerifyFunc((nint)_glIsQuery); return _glIsQuery(id); }
    public static void glBeginQuery(uint target, uint id) { QGLFeature.VerifyFunc((nint)_glBeginQuery); _glBeginQuery(target, id); }
    public static void glEndQuery(uint target) { QGLFeature.VerifyFunc((nint)_glEndQuery); _glEndQuery(target); }
    public static void glGetQueryiv(uint target, uint pname, int* @params) { QGLFeature.VerifyFunc((nint)_glGetQueryiv); _glGetQueryiv(target, pname, @params); }
    public static void glGetQueryObjectuiv(uint id, uint pname, uint* @params) { QGLFeature.VerifyFunc((nint)_glGetQueryObjectuiv); _glGetQueryObjectuiv(id, pname, @params); }
    public static bool glUnmapBuffer(uint target) { QGLFeature.VerifyFunc((nint)_glUnmapBuffer); return _glUnmapBuffer(target); }
    public static void glGetBufferPointerv(uint target, uint pname, void** @params) { QGLFeature.VerifyFunc((nint)_glGetBufferPointerv); _glGetBufferPointerv(target, pname, @params); }
    public static void glDrawBuffers(int n, uint* bufs) { QGLFeature.VerifyFunc((nint)_glDrawBuffers); _glDrawBuffers(n, bufs); }
    public static void glUniformMatrix2x3fv(int location, int count, bool transpose, float* value) { QGLFeature.VerifyFunc((nint)_glUniformMatrix2x3fv); _glUniformMatrix2x3fv(location, count, transpose, value); }
    public static void glUniformMatrix3x2fv(int location, int count, bool transpose, float* value) { QGLFeature.VerifyFunc((nint)_glUniformMatrix3x2fv); _glUniformMatrix3x2fv(location, count, transpose, value); }
    public static void glUniformMatrix2x4fv(int location, int count, bool transpose, float* value) { QGLFeature.VerifyFunc((nint)_glUniformMatrix2x4fv); _glUniformMatrix2x4fv(location, count, transpose, value); }
    public static void glUniformMatrix4x2fv(int location, int count, bool transpose, float* value) { QGLFeature.VerifyFunc((nint)_glUniformMatrix4x2fv); _glUniformMatrix4x2fv(location, count, transpose, value); }
    public static void glUniformMatrix3x4fv(int location, int count, bool transpose, float* value) { QGLFeature.VerifyFunc((nint)_glUniformMatrix3x4fv); _glUniformMatrix3x4fv(location, count, transpose, value); }
    public static void glUniformMatrix4x3fv(int location, int count, bool transpose, float* value) { QGLFeature.VerifyFunc((nint)_glUniformMatrix4x3fv); _glUniformMatrix4x3fv(location, count, transpose, value); }
    public static void glBlitFramebuffer(int srcX0, int srcY0, int srcX1, int srcY1, int dstX0, int dstY0, int dstX1, int dstY1, uint mask, uint filter) { QGLFeature.VerifyFunc((nint)_glBlitFramebuffer); _glBlitFramebuffer(srcX0, srcY0, srcX1, srcY1, dstX0, dstY0, dstX1, dstY1, mask, filter); }
    public static void glRenderbufferStorageMultisample(uint target, int samples, uint internalformat, int width, int height) { QGLFeature.VerifyFunc((nint)_glRenderbufferStorageMultisample); _glRenderbufferStorageMultisample(target, samples, internalformat, width, height); }
    public static void glFramebufferTextureLayer(uint target, uint attachment, uint texture, int level, int layer) { QGLFeature.VerifyFunc((nint)_glFramebufferTextureLayer); _glFramebufferTextureLayer(target, attachment, texture, level, layer); }
    public static void* glMapBufferRange(uint target, nint offset, nint length, uint access) { QGLFeature.VerifyFunc((nint)_glMapBufferRange); return _glMapBufferRange(target, offset, length, access); }
    public static void glFlushMappedBufferRange(uint target, nint offset, nint length) { QGLFeature.VerifyFunc((nint)_glFlushMappedBufferRange); _glFlushMappedBufferRange(target, offset, length); }
    public static void glBindVertexArray(uint array) { QGLFeature.VerifyFunc((nint)_glBindVertexArray); _glBindVertexArray(array); }
    public static void glDeleteVertexArrays(int n, uint* arrays) { QGLFeature.VerifyFunc((nint)_glDeleteVertexArrays); _glDeleteVertexArrays(n, arrays); }
    public static void glGenVertexArrays(int n, uint* arrays) { QGLFeature.VerifyFunc((nint)_glGenVertexArrays); _glGenVertexArrays(n, arrays); }
    public static bool glIsVertexArray(uint array) { QGLFeature.VerifyFunc((nint)_glIsVertexArray); return _glIsVertexArray(array); }
    public static void glGetIntegeri_v(uint target, uint index, int* data) { QGLFeature.VerifyFunc((nint)_glGetIntegeri_v); _glGetIntegeri_v(target, index, data); }
    public static void glBeginTransformFeedback(uint primitiveMode) { QGLFeature.VerifyFunc((nint)_glBeginTransformFeedback); _glBeginTransformFeedback(primitiveMode); }
    public static void glEndTransformFeedback() { QGLFeature.VerifyFunc((nint)_glEndTransformFeedback); _glEndTransformFeedback(); }
    public static void glBindBufferRange(uint target, uint index, uint buffer, nint offset, nint size) { QGLFeature.VerifyFunc((nint)_glBindBufferRange); _glBindBufferRange(target, index, buffer, offset, size); }
    public static void glBindBufferBase(uint target, uint index, uint buffer) { QGLFeature.VerifyFunc((nint)_glBindBufferBase); _glBindBufferBase(target, index, buffer); }
    public static void glTransformFeedbackVaryings(uint program, int count, nint varyings, uint bufferMode) { QGLFeature.VerifyFunc((nint)_glTransformFeedbackVaryings); _glTransformFeedbackVaryings(program, count, varyings, bufferMode); }
    public static void glGetTransformFeedbackVarying(uint program, uint index, int bufSize, int* length, int* size, uint* type, byte* name) { QGLFeature.VerifyFunc((nint)_glGetTransformFeedbackVarying); _glGetTransformFeedbackVarying(program, index, bufSize, length, size, type, name); }
    public static void glVertexAttribIPointer(uint index, int size, uint type, int stride, void* pointer) { QGLFeature.VerifyFunc((nint)_glVertexAttribIPointer); _glVertexAttribIPointer(index, size, type, stride, pointer); }
    public static void glGetVertexAttribIiv(uint index, uint pname, int* @params) { QGLFeature.VerifyFunc((nint)_glGetVertexAttribIiv); _glGetVertexAttribIiv(index, pname, @params); }
    public static void glGetVertexAttribIuiv(uint index, uint pname, uint* @params) { QGLFeature.VerifyFunc((nint)_glGetVertexAttribIuiv); _glGetVertexAttribIuiv(index, pname, @params); }
    public static void glVertexAttribI4i(uint index, int x, int y, int z, int w) { QGLFeature.VerifyFunc((nint)_glVertexAttribI4i); _glVertexAttribI4i(index, x, y, z, w); }
    public static void glVertexAttribI4ui(uint index, uint x, uint y, uint z, uint w) { QGLFeature.VerifyFunc((nint)_glVertexAttribI4ui); _glVertexAttribI4ui(index, x, y, z, w); }
    public static void glVertexAttribI4iv(uint index, int* v) { QGLFeature.VerifyFunc((nint)_glVertexAttribI4iv); _glVertexAttribI4iv(index, v); }
    public static void glVertexAttribI4uiv(uint index, uint* v) { QGLFeature.VerifyFunc((nint)_glVertexAttribI4uiv); _glVertexAttribI4uiv(index, v); }
    public static void glGetUniformuiv(uint program, int location, uint* @params) { QGLFeature.VerifyFunc((nint)_glGetUniformuiv); _glGetUniformuiv(program, location, @params); }
    public static int glGetFragDataLocation(uint program, byte* name) { QGLFeature.VerifyFunc((nint)_glGetFragDataLocation); return _glGetFragDataLocation(program, name); }
    public static void glUniform1ui(int location, uint v0) { QGLFeature.VerifyFunc((nint)_glUniform1ui); _glUniform1ui(location, v0); }
    public static void glUniform2ui(int location, uint v0, uint v1) { QGLFeature.VerifyFunc((nint)_glUniform2ui); _glUniform2ui(location, v0, v1); }
    public static void glUniform3ui(int location, uint v0, uint v1, uint v2) { QGLFeature.VerifyFunc((nint)_glUniform3ui); _glUniform3ui(location, v0, v1, v2); }
    public static void glUniform4ui(int location, uint v0, uint v1, uint v2, uint v3) { QGLFeature.VerifyFunc((nint)_glUniform4ui); _glUniform4ui(location, v0, v1, v2, v3); }
    public static void glUniform1uiv(int location, int count, uint* value) { QGLFeature.VerifyFunc((nint)_glUniform1uiv); _glUniform1uiv(location, count, value); }
    public static void glUniform2uiv(int location, int count, uint* value) { QGLFeature.VerifyFunc((nint)_glUniform2uiv); _glUniform2uiv(location, count, value); }
    public static void glUniform3uiv(int location, int count, uint* value) { QGLFeature.VerifyFunc((nint)_glUniform3uiv); _glUniform3uiv(location, count, value); }
    public static void glUniform4uiv(int location, int count, uint* value) { QGLFeature.VerifyFunc((nint)_glUniform4uiv); _glUniform4uiv(location, count, value); }
    public static void glClearBufferiv(uint buffer, int drawbuffer, int* value) { QGLFeature.VerifyFunc((nint)_glClearBufferiv); _glClearBufferiv(buffer, drawbuffer, value); }
    public static void glClearBufferuiv(uint buffer, int drawbuffer, uint* value) { QGLFeature.VerifyFunc((nint)_glClearBufferuiv); _glClearBufferuiv(buffer, drawbuffer, value); }
    public static void glClearBufferfv(uint buffer, int drawbuffer, float* value) { QGLFeature.VerifyFunc((nint)_glClearBufferfv); _glClearBufferfv(buffer, drawbuffer, value); }
    public static void glClearBufferfi(uint buffer, int drawbuffer, float depth, int stencil) { QGLFeature.VerifyFunc((nint)_glClearBufferfi); _glClearBufferfi(buffer, drawbuffer, depth, stencil); }
    public static byte* glGetStringi(uint name, uint index) { QGLFeature.VerifyFunc((nint)_glGetStringi); return _glGetStringi(name, index); }
    public static void glCopyBufferSubData(uint readTarget, uint writeTarget, nint readOffset, nint writeOffset, nint size) { QGLFeature.VerifyFunc((nint)_glCopyBufferSubData); _glCopyBufferSubData(readTarget, writeTarget, readOffset, writeOffset, size); }
    public static void glGetUniformIndices(uint program, int uniformCount, nint uniformNames, uint* uniformIndices) { QGLFeature.VerifyFunc((nint)_glGetUniformIndices); _glGetUniformIndices(program, uniformCount, uniformNames, uniformIndices); }
    public static void glGetActiveUniformsiv(uint program, int uniformCount, uint* uniformIndices, uint pname, int* @params) { QGLFeature.VerifyFunc((nint)_glGetActiveUniformsiv); _glGetActiveUniformsiv(program, uniformCount, uniformIndices, pname, @params); }
    public static uint glGetUniformBlockIndex(uint program, byte* uniformBlockName) { QGLFeature.VerifyFunc((nint)_glGetUniformBlockIndex); return _glGetUniformBlockIndex(program, uniformBlockName); }
    public static void glGetActiveUniformBlockiv(uint program, uint uniformBlockIndex, uint pname, int* @params) { QGLFeature.VerifyFunc((nint)_glGetActiveUniformBlockiv); _glGetActiveUniformBlockiv(program, uniformBlockIndex, pname, @params); }
    public static void glGetActiveUniformBlockName(uint program, uint uniformBlockIndex, int bufSize, int* length, byte* uniformBlockName) { QGLFeature.VerifyFunc((nint)_glGetActiveUniformBlockName); _glGetActiveUniformBlockName(program, uniformBlockIndex, bufSize, length, uniformBlockName); }
    public static void glUniformBlockBinding(uint program, uint uniformBlockIndex, uint uniformBlockBinding) { QGLFeature.VerifyFunc((nint)_glUniformBlockBinding); _glUniformBlockBinding(program, uniformBlockIndex, uniformBlockBinding); }
    public static void glDrawArraysInstanced(uint mode, int first, int count, int instancecount) { QGLFeature.VerifyFunc((nint)_glDrawArraysInstanced); _glDrawArraysInstanced(mode, first, count, instancecount); }
    public static void glDrawElementsInstanced(uint mode, int count, uint type, void* indices, int instancecount) { QGLFeature.VerifyFunc((nint)_glDrawElementsInstanced); _glDrawElementsInstanced(mode, count, type, indices, instancecount); }
    public static nint glFenceSync(uint condition, uint flags) { QGLFeature.VerifyFunc((nint)_glFenceSync); return _glFenceSync(condition, flags); }
    public static bool glIsSync(nint sync) { QGLFeature.VerifyFunc((nint)_glIsSync); return _glIsSync(sync); }
    public static void glDeleteSync(nint sync) { QGLFeature.VerifyFunc((nint)_glDeleteSync); _glDeleteSync(sync); }
    public static uint glClientWaitSync(nint sync, uint flags, ulong timeout) { QGLFeature.VerifyFunc((nint)_glClientWaitSync); return _glClientWaitSync(sync, flags, timeout); }
    public static void glWaitSync(nint sync, uint flags, ulong timeout) { QGLFeature.VerifyFunc((nint)_glWaitSync); _glWaitSync(sync, flags, timeout); }
    public static void glGetInteger64v(uint pname, long* data) { QGLFeature.VerifyFunc((nint)_glGetInteger64v); _glGetInteger64v(pname, data); }
    public static void glGetSynciv(nint sync, uint pname, int count, int* length, int* values) { QGLFeature.VerifyFunc((nint)_glGetSynciv); _glGetSynciv(sync, pname, count, length, values); }
    public static void glGetInteger64i_v(uint target, uint index, long* data) { QGLFeature.VerifyFunc((nint)_glGetInteger64i_v); _glGetInteger64i_v(target, index, data); }
    public static void glGetBufferParameteri64v(uint target, uint pname, long* @params) { QGLFeature.VerifyFunc((nint)_glGetBufferParameteri64v); _glGetBufferParameteri64v(target, pname, @params); }
    public static void glGenSamplers(int count, uint* samplers) { QGLFeature.VerifyFunc((nint)_glGenSamplers); _glGenSamplers(count, samplers); }
    public static void glDeleteSamplers(int count, uint* samplers) { QGLFeature.VerifyFunc((nint)_glDeleteSamplers); _glDeleteSamplers(count, samplers); }
    public static bool glIsSampler(uint sampler) { QGLFeature.VerifyFunc((nint)_glIsSampler); return _glIsSampler(sampler); }
    public static void glBindSampler(uint unit, uint sampler) { QGLFeature.VerifyFunc((nint)_glBindSampler); _glBindSampler(unit, sampler); }
    public static void glSamplerParameteri(uint sampler, uint pname, int param) { QGLFeature.VerifyFunc((nint)_glSamplerParameteri); _glSamplerParameteri(sampler, pname, param); }
    public static void glSamplerParameteriv(uint sampler, uint pname, int* param) { QGLFeature.VerifyFunc((nint)_glSamplerParameteriv); _glSamplerParameteriv(sampler, pname, param); }
    public static void glSamplerParameterf(uint sampler, uint pname, float param) { QGLFeature.VerifyFunc((nint)_glSamplerParameterf); _glSamplerParameterf(sampler, pname, param); }
    public static void glSamplerParameterfv(uint sampler, uint pname, float* param) { QGLFeature.VerifyFunc((nint)_glSamplerParameterfv); _glSamplerParameterfv(sampler, pname, param); }
    public static void glGetSamplerParameteriv(uint sampler, uint pname, int* @params) { QGLFeature.VerifyFunc((nint)_glGetSamplerParameteriv); _glGetSamplerParameteriv(sampler, pname, @params); }
    public static void glGetSamplerParameterfv(uint sampler, uint pname, float* @params) { QGLFeature.VerifyFunc((nint)_glGetSamplerParameterfv); _glGetSamplerParameterfv(sampler, pname, @params); }
    public static void glVertexAttribDivisor(uint index, uint divisor) { QGLFeature.VerifyFunc((nint)_glVertexAttribDivisor); _glVertexAttribDivisor(index, divisor); }
    public static void glBindTransformFeedback(uint target, uint id) { QGLFeature.VerifyFunc((nint)_glBindTransformFeedback); _glBindTransformFeedback(target, id); }
    public static void glDeleteTransformFeedbacks(int n, uint* ids) { QGLFeature.VerifyFunc((nint)_glDeleteTransformFeedbacks); _glDeleteTransformFeedbacks(n, ids); }
    public static void glGenTransformFeedbacks(int n, uint* ids) { QGLFeature.VerifyFunc((nint)_glGenTransformFeedbacks); _glGenTransformFeedbacks(n, ids); }
    public static bool glIsTransformFeedback(uint id) { QGLFeature.VerifyFunc((nint)_glIsTransformFeedback); return _glIsTransformFeedback(id); }
    public static void glPauseTransformFeedback() { QGLFeature.VerifyFunc((nint)_glPauseTransformFeedback); _glPauseTransformFeedback(); }
    public static void glResumeTransformFeedback() { QGLFeature.VerifyFunc((nint)_glResumeTransformFeedback); _glResumeTransformFeedback(); }
    public static void glGetProgramBinary(uint program, int bufSize, int* length, uint* binaryFormat, void* binary) { QGLFeature.VerifyFunc((nint)_glGetProgramBinary); _glGetProgramBinary(program, bufSize, length, binaryFormat, binary); }
    public static void glProgramBinary(uint program, uint binaryFormat, void* binary, int length) { QGLFeature.VerifyFunc((nint)_glProgramBinary); _glProgramBinary(program, binaryFormat, binary, length); }
    public static void glProgramParameteri(uint program, uint pname, int value) { QGLFeature.VerifyFunc((nint)_glProgramParameteri); _glProgramParameteri(program, pname, value); }
    public static void glInvalidateFramebuffer(uint target, int numAttachments, uint* attachments) { QGLFeature.VerifyFunc((nint)_glInvalidateFramebuffer); _glInvalidateFramebuffer(target, numAttachments, attachments); }
    public static void glInvalidateSubFramebuffer(uint target, int numAttachments, uint* attachments, int x, int y, int width, int height) { QGLFeature.VerifyFunc((nint)_glInvalidateSubFramebuffer); _glInvalidateSubFramebuffer(target, numAttachments, attachments, x, y, width, height); }
    public static void glTexStorage2D(uint target, int levels, uint internalformat, int width, int height) { QGLFeature.VerifyFunc((nint)_glTexStorage2D); _glTexStorage2D(target, levels, internalformat, width, height); }
    public static void glTexStorage3D(uint target, int levels, uint internalformat, int width, int height, int depth) { QGLFeature.VerifyFunc((nint)_glTexStorage3D); _glTexStorage3D(target, levels, internalformat, width, height, depth); }
    public static void glGetInternalformativ(uint target, uint internalformat, uint pname, int count, int* @params) { QGLFeature.VerifyFunc((nint)_glGetInternalformativ); _glGetInternalformativ(target, internalformat, pname, count, @params); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_ES_VERSION_3_0", false, true);
}
