// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
using System.Runtime.InteropServices;
using QuickGL.Internal;

namespace QuickGL.Bindings.Extensions;

public static unsafe class GLARBmultibind
{
    #region Constants
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, uint, int, uint*, void> _glBindBuffersBase = null;
    internal static delegate* unmanaged<uint, uint, int, uint*, nint*, nint*, void> _glBindBuffersRange = null;
    internal static delegate* unmanaged<uint, int, uint*, void> _glBindTextures = null;
    internal static delegate* unmanaged<uint, int, uint*, void> _glBindSamplers = null;
    internal static delegate* unmanaged<uint, int, uint*, void> _glBindImageTextures = null;
    internal static delegate* unmanaged<uint, int, uint*, nint*, int*, void> _glBindVertexBuffers = null;

    internal static void Load()
    {
        _glBindBuffersBase = (delegate* unmanaged<uint, uint, int, uint*, void>)QGL.GetGLProcAddress("glBindBuffersBase");
        _glBindBuffersRange = (delegate* unmanaged<uint, uint, int, uint*, nint*, nint*, void>)QGL.GetGLProcAddress("glBindBuffersRange");
        _glBindTextures = (delegate* unmanaged<uint, int, uint*, void>)QGL.GetGLProcAddress("glBindTextures");
        _glBindSamplers = (delegate* unmanaged<uint, int, uint*, void>)QGL.GetGLProcAddress("glBindSamplers");
        _glBindImageTextures = (delegate* unmanaged<uint, int, uint*, void>)QGL.GetGLProcAddress("glBindImageTextures");
        _glBindVertexBuffers = (delegate* unmanaged<uint, int, uint*, nint*, int*, void>)QGL.GetGLProcAddress("glBindVertexBuffers");
    }

    internal static void Unload()
    {
        _glBindBuffersBase = null;
        _glBindBuffersRange = null;
        _glBindTextures = null;
        _glBindSamplers = null;
        _glBindImageTextures = null;
        _glBindVertexBuffers = null;
    }
    #endregion

    #region Function wrappers
    public static void glBindBuffersBase(uint target, uint first, int count, uint* buffers) { QGLFeature.VerifyFunc((nint)_glBindBuffersBase); _glBindBuffersBase(target, first, count, buffers); }
    public static void glBindBuffersRange(uint target, uint first, int count, uint* buffers, nint* offsets, nint* sizes) { QGLFeature.VerifyFunc((nint)_glBindBuffersRange); _glBindBuffersRange(target, first, count, buffers, offsets, sizes); }
    public static void glBindTextures(uint first, int count, uint* textures) { QGLFeature.VerifyFunc((nint)_glBindTextures); _glBindTextures(first, count, textures); }
    public static void glBindSamplers(uint first, int count, uint* samplers) { QGLFeature.VerifyFunc((nint)_glBindSamplers); _glBindSamplers(first, count, samplers); }
    public static void glBindImageTextures(uint first, int count, uint* textures) { QGLFeature.VerifyFunc((nint)_glBindImageTextures); _glBindImageTextures(first, count, textures); }
    public static void glBindVertexBuffers(uint first, int count, uint* buffers, nint* offsets, int* strides) { QGLFeature.VerifyFunc((nint)_glBindVertexBuffers); _glBindVertexBuffers(first, count, buffers, offsets, strides); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_ARB_multi_bind", true, false);
}
