// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:00:37.9297277Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLARBtransformfeedbackoverflowquery
{
    #region Constants
    public const int GL_TRANSFORM_FEEDBACK_STREAM_OVERFLOW_ARB = 0x000082ED;
    public const int GL_TRANSFORM_FEEDBACK_OVERFLOW_ARB = 0x000082EC;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_ARB_transform_feedback_overflow_query", true, false);
}
