// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T20:04:55.7303980Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLARBshadow
{
    #region Constants
    public const int GL_TEXTURE_COMPARE_MODE_ARB = 0x0000884C;
    public const int GL_TEXTURE_COMPARE_FUNC_ARB = 0x0000884D;
    public const int GL_COMPARE_R_TO_TEXTURE_ARB = 0x0000884E;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_ARB_shadow", true, false);
}
