// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
using System.Runtime.InteropServices;
using QuickGL.Internal;

namespace QuickGL.Bindings.Extensions;

public static unsafe class GLARBtexturefilteranisotropic
{
    #region Constants
    public const int GL_TEXTURE_MAX_ANISOTROPY = 0x000084FE;
    public const int GL_MAX_TEXTURE_MAX_ANISOTROPY = 0x000084FF;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_ARB_texture_filter_anisotropic", true, false);
}
