// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:00:37.7927286Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLARBdrawinstanced
{
    #region Constants
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, int, uint, void*, int, void> _glDrawElementsInstancedARB = null;
    internal static delegate* unmanaged<uint, int, int, int, void> _glDrawArraysInstancedARB = null;

    internal static void Load()
    {
        _glDrawElementsInstancedARB = (delegate* unmanaged<uint, int, uint, void*, int, void>)QuickGL.GetGLProcAddress("glDrawElementsInstancedARB");
        _glDrawArraysInstancedARB = (delegate* unmanaged<uint, int, int, int, void>)QuickGL.GetGLProcAddress("glDrawArraysInstancedARB");
    }

    internal static void Unload()
    {
        _glDrawElementsInstancedARB = null;
        _glDrawArraysInstancedARB = null;
    }
    #endregion

    #region Function wrappers
    public static void glDrawElementsInstancedARB(uint mode, int count, uint type, void* indices, int primcount) { QGLFeature.VerifyFunc((nint)_glDrawElementsInstancedARB); _glDrawElementsInstancedARB(mode, count, type, indices, primcount); }
    public static void glDrawArraysInstancedARB(uint mode, int first, int count, int primcount) { QGLFeature.VerifyFunc((nint)_glDrawArraysInstancedARB); _glDrawArraysInstancedARB(mode, first, count, primcount); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_ARB_draw_instanced", true, false);
}
