// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T20:04:55.7688902Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLARBvertexattrib64bit
{
    #region Constants
    public const int GL_RGB32I = 0x00008D83;
    public const int GL_DOUBLE_VEC2 = 0x00008FFC;
    public const int GL_DOUBLE_VEC3 = 0x00008FFD;
    public const int GL_DOUBLE_VEC4 = 0x00008FFE;
    public const int GL_DOUBLE_MAT2 = 0x00008F46;
    public const int GL_DOUBLE_MAT3 = 0x00008F47;
    public const int GL_DOUBLE_MAT4 = 0x00008F48;
    public const int GL_DOUBLE_MAT2x3 = 0x00008F49;
    public const int GL_DOUBLE_MAT2x4 = 0x00008F4A;
    public const int GL_DOUBLE_MAT3x2 = 0x00008F4B;
    public const int GL_DOUBLE_MAT3x4 = 0x00008F4C;
    public const int GL_DOUBLE_MAT4x2 = 0x00008F4D;
    public const int GL_DOUBLE_MAT4x3 = 0x00008F4E;
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, double, void> _glVertexAttribL1d = null;
    internal static delegate* unmanaged<uint, double, double, void> _glVertexAttribL2d = null;
    internal static delegate* unmanaged<uint, double, double, double, void> _glVertexAttribL3d = null;
    internal static delegate* unmanaged<uint, double, double, double, double, void> _glVertexAttribL4d = null;
    internal static delegate* unmanaged<uint, double*, void> _glVertexAttribL1dv = null;
    internal static delegate* unmanaged<uint, double*, void> _glVertexAttribL2dv = null;
    internal static delegate* unmanaged<uint, double*, void> _glVertexAttribL3dv = null;
    internal static delegate* unmanaged<uint, double*, void> _glVertexAttribL4dv = null;
    internal static delegate* unmanaged<uint, int, uint, int, void*, void> _glVertexAttribLPointer = null;
    internal static delegate* unmanaged<uint, uint, double*, void> _glGetVertexAttribLdv = null;

    internal static void Load()
    {
        _glVertexAttribL1d = (delegate* unmanaged<uint, double, void>)QuickGL.GetGLProcAddress("glVertexAttribL1d");
        _glVertexAttribL2d = (delegate* unmanaged<uint, double, double, void>)QuickGL.GetGLProcAddress("glVertexAttribL2d");
        _glVertexAttribL3d = (delegate* unmanaged<uint, double, double, double, void>)QuickGL.GetGLProcAddress("glVertexAttribL3d");
        _glVertexAttribL4d = (delegate* unmanaged<uint, double, double, double, double, void>)QuickGL.GetGLProcAddress("glVertexAttribL4d");
        _glVertexAttribL1dv = (delegate* unmanaged<uint, double*, void>)QuickGL.GetGLProcAddress("glVertexAttribL1dv");
        _glVertexAttribL2dv = (delegate* unmanaged<uint, double*, void>)QuickGL.GetGLProcAddress("glVertexAttribL2dv");
        _glVertexAttribL3dv = (delegate* unmanaged<uint, double*, void>)QuickGL.GetGLProcAddress("glVertexAttribL3dv");
        _glVertexAttribL4dv = (delegate* unmanaged<uint, double*, void>)QuickGL.GetGLProcAddress("glVertexAttribL4dv");
        _glVertexAttribLPointer = (delegate* unmanaged<uint, int, uint, int, void*, void>)QuickGL.GetGLProcAddress("glVertexAttribLPointer");
        _glGetVertexAttribLdv = (delegate* unmanaged<uint, uint, double*, void>)QuickGL.GetGLProcAddress("glGetVertexAttribLdv");
    }

    internal static void Unload()
    {
        _glVertexAttribL1d = null;
        _glVertexAttribL2d = null;
        _glVertexAttribL3d = null;
        _glVertexAttribL4d = null;
        _glVertexAttribL1dv = null;
        _glVertexAttribL2dv = null;
        _glVertexAttribL3dv = null;
        _glVertexAttribL4dv = null;
        _glVertexAttribLPointer = null;
        _glGetVertexAttribLdv = null;
    }
    #endregion

    #region Function wrappers
    public static void glVertexAttribL1d(uint index, double x) { QGLFeature.VerifyFunc((nint)_glVertexAttribL1d); _glVertexAttribL1d(index, x); }
    public static void glVertexAttribL2d(uint index, double x, double y) { QGLFeature.VerifyFunc((nint)_glVertexAttribL2d); _glVertexAttribL2d(index, x, y); }
    public static void glVertexAttribL3d(uint index, double x, double y, double z) { QGLFeature.VerifyFunc((nint)_glVertexAttribL3d); _glVertexAttribL3d(index, x, y, z); }
    public static void glVertexAttribL4d(uint index, double x, double y, double z, double w) { QGLFeature.VerifyFunc((nint)_glVertexAttribL4d); _glVertexAttribL4d(index, x, y, z, w); }
    public static void glVertexAttribL1dv(uint index, double* v) { QGLFeature.VerifyFunc((nint)_glVertexAttribL1dv); _glVertexAttribL1dv(index, v); }
    public static void glVertexAttribL2dv(uint index, double* v) { QGLFeature.VerifyFunc((nint)_glVertexAttribL2dv); _glVertexAttribL2dv(index, v); }
    public static void glVertexAttribL3dv(uint index, double* v) { QGLFeature.VerifyFunc((nint)_glVertexAttribL3dv); _glVertexAttribL3dv(index, v); }
    public static void glVertexAttribL4dv(uint index, double* v) { QGLFeature.VerifyFunc((nint)_glVertexAttribL4dv); _glVertexAttribL4dv(index, v); }
    public static void glVertexAttribLPointer(uint index, int size, uint type, int stride, void* pointer) { QGLFeature.VerifyFunc((nint)_glVertexAttribLPointer); _glVertexAttribLPointer(index, size, type, stride, pointer); }
    public static void glGetVertexAttribLdv(uint index, uint pname, double* @params) { QGLFeature.VerifyFunc((nint)_glGetVertexAttribLdv); _glGetVertexAttribLdv(index, pname, @params); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_ARB_vertex_attrib_64bit", true, false);
}
