// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T20:04:55.6828378Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLARBclearbufferobject
{
    #region Constants
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, uint, uint, uint, void*, void> _glClearBufferData = null;
    internal static delegate* unmanaged<uint, uint, nint, nint, uint, uint, void*, void> _glClearBufferSubData = null;

    internal static void Load()
    {
        _glClearBufferData = (delegate* unmanaged<uint, uint, uint, uint, void*, void>)QuickGL.GetGLProcAddress("glClearBufferData");
        _glClearBufferSubData = (delegate* unmanaged<uint, uint, nint, nint, uint, uint, void*, void>)QuickGL.GetGLProcAddress("glClearBufferSubData");
    }

    internal static void Unload()
    {
        _glClearBufferData = null;
        _glClearBufferSubData = null;
    }
    #endregion

    #region Function wrappers
    public static void glClearBufferData(uint target, uint internalformat, uint format, uint type, void* data) { QGLFeature.VerifyFunc((nint)_glClearBufferData); _glClearBufferData(target, internalformat, format, type, data); }
    public static void glClearBufferSubData(uint target, uint internalformat, nint offset, nint size, uint format, uint type, void* data) { QGLFeature.VerifyFunc((nint)_glClearBufferSubData); _glClearBufferSubData(target, internalformat, offset, size, format, type, data); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_ARB_clear_buffer_object", true, false);
}
