// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
using System.Runtime.InteropServices;
using QuickGL.Internal;

namespace QuickGL.Bindings.Extensions;

public static unsafe class GLARBES3compatibility
{
    #region Constants
    public const int GL_COMPRESSED_RGB8_ETC2 = 0x00009274;
    public const int GL_COMPRESSED_SRGB8_ETC2 = 0x00009275;
    public const int GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x00009276;
    public const int GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x00009277;
    public const int GL_COMPRESSED_RGBA8_ETC2_EAC = 0x00009278;
    public const int GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC = 0x00009279;
    public const int GL_COMPRESSED_R11_EAC = 0x00009270;
    public const int GL_COMPRESSED_SIGNED_R11_EAC = 0x00009271;
    public const int GL_COMPRESSED_RG11_EAC = 0x00009272;
    public const int GL_COMPRESSED_SIGNED_RG11_EAC = 0x00009273;
    public const int GL_PRIMITIVE_RESTART_FIXED_INDEX = 0x00008D69;
    public const int GL_ANY_SAMPLES_PASSED_CONSERVATIVE = 0x00008D6A;
    public const int GL_MAX_ELEMENT_INDEX = 0x00008D6B;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_ARB_ES3_compatibility", true, false);
}
