// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:43:43.7483740Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLARBbaseinstance
{
    #region Constants
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, int, int, int, uint, void> _glDrawArraysInstancedBaseInstance = null;
    internal static delegate* unmanaged<uint, int, uint, void*, int, uint, void> _glDrawElementsInstancedBaseInstance = null;
    internal static delegate* unmanaged<uint, int, uint, void*, int, int, uint, void> _glDrawElementsInstancedBaseVertexBaseInstance = null;

    internal static void Load()
    {
        _glDrawArraysInstancedBaseInstance = (delegate* unmanaged<uint, int, int, int, uint, void>)QuickGL.GetGLProcAddress("glDrawArraysInstancedBaseInstance");
        _glDrawElementsInstancedBaseInstance = (delegate* unmanaged<uint, int, uint, void*, int, uint, void>)QuickGL.GetGLProcAddress("glDrawElementsInstancedBaseInstance");
        _glDrawElementsInstancedBaseVertexBaseInstance = (delegate* unmanaged<uint, int, uint, void*, int, int, uint, void>)QuickGL.GetGLProcAddress("glDrawElementsInstancedBaseVertexBaseInstance");
    }

    internal static void Unload()
    {
        _glDrawArraysInstancedBaseInstance = null;
        _glDrawElementsInstancedBaseInstance = null;
        _glDrawElementsInstancedBaseVertexBaseInstance = null;
    }
    #endregion

    #region Function wrappers
    public static void glDrawArraysInstancedBaseInstance(uint mode, int first, int count, int instancecount, uint baseinstance) { QGLFeature.VerifyFunc((nint)_glDrawArraysInstancedBaseInstance); _glDrawArraysInstancedBaseInstance(mode, first, count, instancecount, baseinstance); }
    public static void glDrawElementsInstancedBaseInstance(uint mode, int count, uint type, void* indices, int instancecount, uint baseinstance) { QGLFeature.VerifyFunc((nint)_glDrawElementsInstancedBaseInstance); _glDrawElementsInstancedBaseInstance(mode, count, type, indices, instancecount, baseinstance); }
    public static void glDrawElementsInstancedBaseVertexBaseInstance(uint mode, int count, uint type, void* indices, int instancecount, int basevertex, uint baseinstance) { QGLFeature.VerifyFunc((nint)_glDrawElementsInstancedBaseVertexBaseInstance); _glDrawElementsInstancedBaseVertexBaseInstance(mode, count, type, indices, instancecount, basevertex, baseinstance); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_ARB_base_instance", true, false);
}
