// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLARBspirvextensions
{
    #region Constants
    public const int GL_SPIR_V_EXTENSIONS = 0x00009553;
    public const int GL_NUM_SPIR_V_EXTENSIONS = 0x00009554;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_ARB_spirv_extensions", true, false);
}
