// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
using System.Runtime.InteropServices;
using QuickGL.Internal;

namespace QuickGL.Bindings.Extensions;

public static unsafe class GLARBconditionalrenderinverted
{
    #region Constants
    public const int GL_QUERY_WAIT_INVERTED = 0x00008E17;
    public const int GL_QUERY_NO_WAIT_INVERTED = 0x00008E18;
    public const int GL_QUERY_BY_REGION_WAIT_INVERTED = 0x00008E19;
    public const int GL_QUERY_BY_REGION_NO_WAIT_INVERTED = 0x00008E1A;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_ARB_conditional_render_inverted", true, false);
}
