// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:43:43.7864241Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLARBinvalidatesubdata
{
    #region Constants
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, int, int, int, int, int, int, int, void> _glInvalidateTexSubImage = null;
    internal static delegate* unmanaged<uint, int, void> _glInvalidateTexImage = null;
    internal static delegate* unmanaged<uint, nint, nint, void> _glInvalidateBufferSubData = null;
    internal static delegate* unmanaged<uint, void> _glInvalidateBufferData = null;
    internal static delegate* unmanaged<uint, int, uint*, void> _glInvalidateFramebuffer = null;
    internal static delegate* unmanaged<uint, int, uint*, int, int, int, int, void> _glInvalidateSubFramebuffer = null;

    internal static void Load()
    {
        _glInvalidateTexSubImage = (delegate* unmanaged<uint, int, int, int, int, int, int, int, void>)QuickGL.GetGLProcAddress("glInvalidateTexSubImage");
        _glInvalidateTexImage = (delegate* unmanaged<uint, int, void>)QuickGL.GetGLProcAddress("glInvalidateTexImage");
        _glInvalidateBufferSubData = (delegate* unmanaged<uint, nint, nint, void>)QuickGL.GetGLProcAddress("glInvalidateBufferSubData");
        _glInvalidateBufferData = (delegate* unmanaged<uint, void>)QuickGL.GetGLProcAddress("glInvalidateBufferData");
        _glInvalidateFramebuffer = (delegate* unmanaged<uint, int, uint*, void>)QuickGL.GetGLProcAddress("glInvalidateFramebuffer");
        _glInvalidateSubFramebuffer = (delegate* unmanaged<uint, int, uint*, int, int, int, int, void>)QuickGL.GetGLProcAddress("glInvalidateSubFramebuffer");
    }

    internal static void Unload()
    {
        _glInvalidateTexSubImage = null;
        _glInvalidateTexImage = null;
        _glInvalidateBufferSubData = null;
        _glInvalidateBufferData = null;
        _glInvalidateFramebuffer = null;
        _glInvalidateSubFramebuffer = null;
    }
    #endregion

    #region Function wrappers
    public static void glInvalidateTexSubImage(uint texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth) { QGLFeature.VerifyFunc((nint)_glInvalidateTexSubImage); _glInvalidateTexSubImage(texture, level, xoffset, yoffset, zoffset, width, height, depth); }
    public static void glInvalidateTexImage(uint texture, int level) { QGLFeature.VerifyFunc((nint)_glInvalidateTexImage); _glInvalidateTexImage(texture, level); }
    public static void glInvalidateBufferSubData(uint buffer, nint offset, nint length) { QGLFeature.VerifyFunc((nint)_glInvalidateBufferSubData); _glInvalidateBufferSubData(buffer, offset, length); }
    public static void glInvalidateBufferData(uint buffer) { QGLFeature.VerifyFunc((nint)_glInvalidateBufferData); _glInvalidateBufferData(buffer); }
    public static void glInvalidateFramebuffer(uint target, int numAttachments, uint* attachments) { QGLFeature.VerifyFunc((nint)_glInvalidateFramebuffer); _glInvalidateFramebuffer(target, numAttachments, attachments); }
    public static void glInvalidateSubFramebuffer(uint target, int numAttachments, uint* attachments, int x, int y, int width, int height) { QGLFeature.VerifyFunc((nint)_glInvalidateSubFramebuffer); _glInvalidateSubFramebuffer(target, numAttachments, attachments, x, y, width, height); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_ARB_invalidate_subdata", true, false);
}
