// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:41:03.0241560Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLARBdepthtexture
{
    #region Constants
    public const int GL_DEPTH_COMPONENT16_ARB = 0x000081A5;
    public const int GL_DEPTH_COMPONENT24_ARB = 0x000081A6;
    public const int GL_DEPTH_COMPONENT32_ARB = 0x000081A7;
    public const int GL_TEXTURE_DEPTH_SIZE_ARB = 0x0000884A;
    public const int GL_DEPTH_TEXTURE_MODE_ARB = 0x0000884B;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_ARB_depth_texture", true, false);
}
