// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T20:04:55.7382674Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLARBtexturebufferobjectrgb32
{
    #region Constants
    public const int GL_RGB32F = 0x00008815;
    public const int GL_RGB32UI = 0x00008D71;
    public const int GL_RGB32I = 0x00008D83;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_ARB_texture_buffer_object_rgb32", true, false);
}
