// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLARBbindlesstexture
{
    #region Constants
    public const int GL_UNSIGNED_INT64_ARB = 0x0000140F;
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, ulong> _glGetTextureHandleARB = null;
    internal static delegate* unmanaged<uint, uint, ulong> _glGetTextureSamplerHandleARB = null;
    internal static delegate* unmanaged<ulong, void> _glMakeTextureHandleResidentARB = null;
    internal static delegate* unmanaged<ulong, void> _glMakeTextureHandleNonResidentARB = null;
    internal static delegate* unmanaged<uint, int, bool, int, uint, ulong> _glGetImageHandleARB = null;
    internal static delegate* unmanaged<ulong, uint, void> _glMakeImageHandleResidentARB = null;
    internal static delegate* unmanaged<ulong, void> _glMakeImageHandleNonResidentARB = null;
    internal static delegate* unmanaged<int, ulong, void> _glUniformHandleui64ARB = null;
    internal static delegate* unmanaged<int, int, ulong*, void> _glUniformHandleui64vARB = null;
    internal static delegate* unmanaged<uint, int, ulong, void> _glProgramUniformHandleui64ARB = null;
    internal static delegate* unmanaged<uint, int, int, ulong*, void> _glProgramUniformHandleui64vARB = null;
    internal static delegate* unmanaged<ulong, bool> _glIsTextureHandleResidentARB = null;
    internal static delegate* unmanaged<ulong, bool> _glIsImageHandleResidentARB = null;
    internal static delegate* unmanaged<uint, ulong, void> _glVertexAttribL1ui64ARB = null;
    internal static delegate* unmanaged<uint, ulong*, void> _glVertexAttribL1ui64vARB = null;
    internal static delegate* unmanaged<uint, uint, ulong*, void> _glGetVertexAttribLui64vARB = null;

    internal static void Load()
    {
        _glGetTextureHandleARB = (delegate* unmanaged<uint, ulong>)QuickGL.GetGLProcAddress("glGetTextureHandleARB");
        _glGetTextureSamplerHandleARB = (delegate* unmanaged<uint, uint, ulong>)QuickGL.GetGLProcAddress("glGetTextureSamplerHandleARB");
        _glMakeTextureHandleResidentARB = (delegate* unmanaged<ulong, void>)QuickGL.GetGLProcAddress("glMakeTextureHandleResidentARB");
        _glMakeTextureHandleNonResidentARB = (delegate* unmanaged<ulong, void>)QuickGL.GetGLProcAddress("glMakeTextureHandleNonResidentARB");
        _glGetImageHandleARB = (delegate* unmanaged<uint, int, bool, int, uint, ulong>)QuickGL.GetGLProcAddress("glGetImageHandleARB");
        _glMakeImageHandleResidentARB = (delegate* unmanaged<ulong, uint, void>)QuickGL.GetGLProcAddress("glMakeImageHandleResidentARB");
        _glMakeImageHandleNonResidentARB = (delegate* unmanaged<ulong, void>)QuickGL.GetGLProcAddress("glMakeImageHandleNonResidentARB");
        _glUniformHandleui64ARB = (delegate* unmanaged<int, ulong, void>)QuickGL.GetGLProcAddress("glUniformHandleui64ARB");
        _glUniformHandleui64vARB = (delegate* unmanaged<int, int, ulong*, void>)QuickGL.GetGLProcAddress("glUniformHandleui64vARB");
        _glProgramUniformHandleui64ARB = (delegate* unmanaged<uint, int, ulong, void>)QuickGL.GetGLProcAddress("glProgramUniformHandleui64ARB");
        _glProgramUniformHandleui64vARB = (delegate* unmanaged<uint, int, int, ulong*, void>)QuickGL.GetGLProcAddress("glProgramUniformHandleui64vARB");
        _glIsTextureHandleResidentARB = (delegate* unmanaged<ulong, bool>)QuickGL.GetGLProcAddress("glIsTextureHandleResidentARB");
        _glIsImageHandleResidentARB = (delegate* unmanaged<ulong, bool>)QuickGL.GetGLProcAddress("glIsImageHandleResidentARB");
        _glVertexAttribL1ui64ARB = (delegate* unmanaged<uint, ulong, void>)QuickGL.GetGLProcAddress("glVertexAttribL1ui64ARB");
        _glVertexAttribL1ui64vARB = (delegate* unmanaged<uint, ulong*, void>)QuickGL.GetGLProcAddress("glVertexAttribL1ui64vARB");
        _glGetVertexAttribLui64vARB = (delegate* unmanaged<uint, uint, ulong*, void>)QuickGL.GetGLProcAddress("glGetVertexAttribLui64vARB");
    }

    internal static void Unload()
    {
        _glGetTextureHandleARB = null;
        _glGetTextureSamplerHandleARB = null;
        _glMakeTextureHandleResidentARB = null;
        _glMakeTextureHandleNonResidentARB = null;
        _glGetImageHandleARB = null;
        _glMakeImageHandleResidentARB = null;
        _glMakeImageHandleNonResidentARB = null;
        _glUniformHandleui64ARB = null;
        _glUniformHandleui64vARB = null;
        _glProgramUniformHandleui64ARB = null;
        _glProgramUniformHandleui64vARB = null;
        _glIsTextureHandleResidentARB = null;
        _glIsImageHandleResidentARB = null;
        _glVertexAttribL1ui64ARB = null;
        _glVertexAttribL1ui64vARB = null;
        _glGetVertexAttribLui64vARB = null;
    }
    #endregion

    #region Function wrappers
    public static ulong glGetTextureHandleARB(uint texture) { QGLFeature.VerifyFunc((nint)_glGetTextureHandleARB); return _glGetTextureHandleARB(texture); }
    public static ulong glGetTextureSamplerHandleARB(uint texture, uint sampler) { QGLFeature.VerifyFunc((nint)_glGetTextureSamplerHandleARB); return _glGetTextureSamplerHandleARB(texture, sampler); }
    public static void glMakeTextureHandleResidentARB(ulong handle) { QGLFeature.VerifyFunc((nint)_glMakeTextureHandleResidentARB); _glMakeTextureHandleResidentARB(handle); }
    public static void glMakeTextureHandleNonResidentARB(ulong handle) { QGLFeature.VerifyFunc((nint)_glMakeTextureHandleNonResidentARB); _glMakeTextureHandleNonResidentARB(handle); }
    public static ulong glGetImageHandleARB(uint texture, int level, bool layered, int layer, uint format) { QGLFeature.VerifyFunc((nint)_glGetImageHandleARB); return _glGetImageHandleARB(texture, level, layered, layer, format); }
    public static void glMakeImageHandleResidentARB(ulong handle, uint access) { QGLFeature.VerifyFunc((nint)_glMakeImageHandleResidentARB); _glMakeImageHandleResidentARB(handle, access); }
    public static void glMakeImageHandleNonResidentARB(ulong handle) { QGLFeature.VerifyFunc((nint)_glMakeImageHandleNonResidentARB); _glMakeImageHandleNonResidentARB(handle); }
    public static void glUniformHandleui64ARB(int location, ulong value) { QGLFeature.VerifyFunc((nint)_glUniformHandleui64ARB); _glUniformHandleui64ARB(location, value); }
    public static void glUniformHandleui64vARB(int location, int count, ulong* value) { QGLFeature.VerifyFunc((nint)_glUniformHandleui64vARB); _glUniformHandleui64vARB(location, count, value); }
    public static void glProgramUniformHandleui64ARB(uint program, int location, ulong value) { QGLFeature.VerifyFunc((nint)_glProgramUniformHandleui64ARB); _glProgramUniformHandleui64ARB(program, location, value); }
    public static void glProgramUniformHandleui64vARB(uint program, int location, int count, ulong* values) { QGLFeature.VerifyFunc((nint)_glProgramUniformHandleui64vARB); _glProgramUniformHandleui64vARB(program, location, count, values); }
    public static bool glIsTextureHandleResidentARB(ulong handle) { QGLFeature.VerifyFunc((nint)_glIsTextureHandleResidentARB); return _glIsTextureHandleResidentARB(handle); }
    public static bool glIsImageHandleResidentARB(ulong handle) { QGLFeature.VerifyFunc((nint)_glIsImageHandleResidentARB); return _glIsImageHandleResidentARB(handle); }
    public static void glVertexAttribL1ui64ARB(uint index, ulong x) { QGLFeature.VerifyFunc((nint)_glVertexAttribL1ui64ARB); _glVertexAttribL1ui64ARB(index, x); }
    public static void glVertexAttribL1ui64vARB(uint index, ulong* v) { QGLFeature.VerifyFunc((nint)_glVertexAttribL1ui64vARB); _glVertexAttribL1ui64vARB(index, v); }
    public static void glGetVertexAttribLui64vARB(uint index, uint pname, ulong* @params) { QGLFeature.VerifyFunc((nint)_glGetVertexAttribLui64vARB); _glGetVertexAttribLui64vARB(index, pname, @params); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_ARB_bindless_texture", true, false);
}
