// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T20:04:55.7164344Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLARBsamplelocations
{
    #region Constants
    public const int GL_SAMPLE_LOCATION_SUBPIXEL_BITS_ARB = 0x0000933D;
    public const int GL_SAMPLE_LOCATION_PIXEL_GRID_WIDTH_ARB = 0x0000933E;
    public const int GL_SAMPLE_LOCATION_PIXEL_GRID_HEIGHT_ARB = 0x0000933F;
    public const int GL_PROGRAMMABLE_SAMPLE_LOCATION_TABLE_SIZE_ARB = 0x00009340;
    public const int GL_SAMPLE_LOCATION_ARB = 0x00008E50;
    public const int GL_PROGRAMMABLE_SAMPLE_LOCATION_ARB = 0x00009341;
    public const int GL_FRAMEBUFFER_PROGRAMMABLE_SAMPLE_LOCATIONS_ARB = 0x00009342;
    public const int GL_FRAMEBUFFER_SAMPLE_LOCATION_PIXEL_GRID_ARB = 0x00009343;
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, uint, int, float*, void> _glFramebufferSampleLocationsfvARB = null;
    internal static delegate* unmanaged<uint, uint, int, float*, void> _glNamedFramebufferSampleLocationsfvARB = null;
    internal static delegate* unmanaged<void> _glEvaluateDepthValuesARB = null;

    internal static void Load()
    {
        _glFramebufferSampleLocationsfvARB = (delegate* unmanaged<uint, uint, int, float*, void>)QuickGL.GetGLProcAddress("glFramebufferSampleLocationsfvARB");
        _glNamedFramebufferSampleLocationsfvARB = (delegate* unmanaged<uint, uint, int, float*, void>)QuickGL.GetGLProcAddress("glNamedFramebufferSampleLocationsfvARB");
        _glEvaluateDepthValuesARB = (delegate* unmanaged<void>)QuickGL.GetGLProcAddress("glEvaluateDepthValuesARB");
    }

    internal static void Unload()
    {
        _glFramebufferSampleLocationsfvARB = null;
        _glNamedFramebufferSampleLocationsfvARB = null;
        _glEvaluateDepthValuesARB = null;
    }
    #endregion

    #region Function wrappers
    public static void glFramebufferSampleLocationsfvARB(uint target, uint start, int count, float* v) { QGLFeature.VerifyFunc((nint)_glFramebufferSampleLocationsfvARB); _glFramebufferSampleLocationsfvARB(target, start, count, v); }
    public static void glNamedFramebufferSampleLocationsfvARB(uint framebuffer, uint start, int count, float* v) { QGLFeature.VerifyFunc((nint)_glNamedFramebufferSampleLocationsfvARB); _glNamedFramebufferSampleLocationsfvARB(framebuffer, start, count, v); }
    public static void glEvaluateDepthValuesARB() { QGLFeature.VerifyFunc((nint)_glEvaluateDepthValuesARB); _glEvaluateDepthValuesARB(); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_ARB_sample_locations", true, false);
}
