// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:41:03.1387632Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLARBtexturegather
{
    #region Constants
    public const int GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET_ARB = 0x00008E5E;
    public const int GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET_ARB = 0x00008E5F;
    public const int GL_MAX_PROGRAM_TEXTURE_GATHER_COMPONENTS_ARB = 0x00008F9F;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_ARB_texture_gather", true, false);
}
