// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:41:03.3789853Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTtexturestorage
{
    #region Constants
    public const int GL_TEXTURE_IMMUTABLE_FORMAT_EXT = 0x0000912F;
    public const int GL_ALPHA8_EXT = 0x0000803C;
    public const int GL_LUMINANCE8_EXT = 0x00008040;
    public const int GL_LUMINANCE8_ALPHA8_EXT = 0x00008045;
    public const int GL_RGBA32F_EXT = 0x00008814;
    public const int GL_RGB32F_EXT = 0x00008815;
    public const int GL_ALPHA32F_EXT = 0x00008816;
    public const int GL_LUMINANCE32F_EXT = 0x00008818;
    public const int GL_LUMINANCE_ALPHA32F_EXT = 0x00008819;
    public const int GL_RGBA16F_EXT = 0x0000881A;
    public const int GL_RGB16F_EXT = 0x0000881B;
    public const int GL_ALPHA16F_EXT = 0x0000881C;
    public const int GL_LUMINANCE16F_EXT = 0x0000881E;
    public const int GL_LUMINANCE_ALPHA16F_EXT = 0x0000881F;
    public const int GL_RGB10_A2_EXT = 0x00008059;
    public const int GL_RGB10_EXT = 0x00008052;
    public const int GL_BGRA8_EXT = 0x000093A1;
    public const int GL_R8_EXT = 0x00008229;
    public const int GL_RG8_EXT = 0x0000822B;
    public const int GL_R32F_EXT = 0x0000822E;
    public const int GL_RG32F_EXT = 0x00008230;
    public const int GL_R16F_EXT = 0x0000822D;
    public const int GL_RG16F_EXT = 0x0000822F;
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, int, uint, int, void> _glTexStorage1DEXT = null;
    internal static delegate* unmanaged<uint, int, uint, int, int, void> _glTexStorage2DEXT = null;
    internal static delegate* unmanaged<uint, int, uint, int, int, int, void> _glTexStorage3DEXT = null;
    internal static delegate* unmanaged<uint, uint, int, uint, int, void> _glTextureStorage1DEXT = null;
    internal static delegate* unmanaged<uint, uint, int, uint, int, int, void> _glTextureStorage2DEXT = null;
    internal static delegate* unmanaged<uint, uint, int, uint, int, int, int, void> _glTextureStorage3DEXT = null;

    internal static void Load()
    {
        _glTexStorage1DEXT = (delegate* unmanaged<uint, int, uint, int, void>)QuickGL.GetGLProcAddress("glTexStorage1DEXT");
        _glTexStorage2DEXT = (delegate* unmanaged<uint, int, uint, int, int, void>)QuickGL.GetGLProcAddress("glTexStorage2DEXT");
        _glTexStorage3DEXT = (delegate* unmanaged<uint, int, uint, int, int, int, void>)QuickGL.GetGLProcAddress("glTexStorage3DEXT");
        _glTextureStorage1DEXT = (delegate* unmanaged<uint, uint, int, uint, int, void>)QuickGL.GetGLProcAddress("glTextureStorage1DEXT");
        _glTextureStorage2DEXT = (delegate* unmanaged<uint, uint, int, uint, int, int, void>)QuickGL.GetGLProcAddress("glTextureStorage2DEXT");
        _glTextureStorage3DEXT = (delegate* unmanaged<uint, uint, int, uint, int, int, int, void>)QuickGL.GetGLProcAddress("glTextureStorage3DEXT");
    }

    internal static void Unload()
    {
        _glTexStorage1DEXT = null;
        _glTexStorage2DEXT = null;
        _glTexStorage3DEXT = null;
        _glTextureStorage1DEXT = null;
        _glTextureStorage2DEXT = null;
        _glTextureStorage3DEXT = null;
    }
    #endregion

    #region Function wrappers
    public static void glTexStorage1DEXT(uint target, int levels, uint internalformat, int width) { QGLFeature.VerifyFunc((nint)_glTexStorage1DEXT); _glTexStorage1DEXT(target, levels, internalformat, width); }
    public static void glTexStorage2DEXT(uint target, int levels, uint internalformat, int width, int height) { QGLFeature.VerifyFunc((nint)_glTexStorage2DEXT); _glTexStorage2DEXT(target, levels, internalformat, width, height); }
    public static void glTexStorage3DEXT(uint target, int levels, uint internalformat, int width, int height, int depth) { QGLFeature.VerifyFunc((nint)_glTexStorage3DEXT); _glTexStorage3DEXT(target, levels, internalformat, width, height, depth); }
    public static void glTextureStorage1DEXT(uint texture, uint target, int levels, uint internalformat, int width) { QGLFeature.VerifyFunc((nint)_glTextureStorage1DEXT); _glTextureStorage1DEXT(texture, target, levels, internalformat, width); }
    public static void glTextureStorage2DEXT(uint texture, uint target, int levels, uint internalformat, int width, int height) { QGLFeature.VerifyFunc((nint)_glTextureStorage2DEXT); _glTextureStorage2DEXT(texture, target, levels, internalformat, width, height); }
    public static void glTextureStorage3DEXT(uint texture, uint target, int levels, uint internalformat, int width, int height, int depth) { QGLFeature.VerifyFunc((nint)_glTextureStorage3DEXT); _glTextureStorage3DEXT(texture, target, levels, internalformat, width, height, depth); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_texture_storage", true, false);
}
