// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:00:38.1645455Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTtexturesRGBdecode
{
    #region Constants
    public const int GL_SKIP_DECODE_EXT = 0x00008A4A;
    public const int GL_DECODE_EXT = 0x00008A49;
    public const int GL_TEXTURE_SRGB_DECODE_EXT = 0x00008A48;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_texture_sRGB_decode", true, false);
}
