// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTtexturenorm16
{
    #region Constants
    public const int GL_R16_EXT = 0x0000822A;
    public const int GL_RG16_EXT = 0x0000822C;
    public const int GL_RGBA16_EXT = 0x0000805B;
    public const int GL_RGB16_EXT = 0x00008054;
    public const int GL_R16_SNORM_EXT = 0x00008F98;
    public const int GL_RG16_SNORM_EXT = 0x00008F99;
    public const int GL_RGB16_SNORM_EXT = 0x00008F9A;
    public const int GL_RGBA16_SNORM_EXT = 0x00008F9B;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_texture_norm16", true, true);
}
