// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:00:38.1471815Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTtexturemirrorclamp
{
    #region Constants
    public const int GL_MIRROR_CLAMP_TO_BORDER_EXT = 0x00008912;
    public const int GL_MIRROR_CLAMP_TO_EDGE_EXT = 0x00008743;
    public const int GL_MIRROR_CLAMP_EXT = 0x00008742;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_texture_mirror_clamp", true, false);
}
