// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:41:03.2761438Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTpackedpixels
{
    #region Constants
    public const int GL_UNSIGNED_BYTE_3_3_2_EXT = 0x00008032;
    public const int GL_UNSIGNED_SHORT_4_4_4_4_EXT = 0x00008033;
    public const int GL_UNSIGNED_SHORT_5_5_5_1_EXT = 0x00008034;
    public const int GL_UNSIGNED_INT_8_8_8_8_EXT = 0x00008035;
    public const int GL_UNSIGNED_INT_10_10_10_2_EXT = 0x00008036;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_packed_pixels", true, false);
}
