// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:00:38.0307703Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTmultidrawindirect
{
    #region Constants
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, uint, void*, int, int, void> _glMultiDrawElementsIndirectEXT = null;
    internal static delegate* unmanaged<uint, void*, int, int, void> _glMultiDrawArraysIndirectEXT = null;

    internal static void Load()
    {
        _glMultiDrawElementsIndirectEXT = (delegate* unmanaged<uint, uint, void*, int, int, void>)QuickGL.GetGLProcAddress("glMultiDrawElementsIndirectEXT");
        _glMultiDrawArraysIndirectEXT = (delegate* unmanaged<uint, void*, int, int, void>)QuickGL.GetGLProcAddress("glMultiDrawArraysIndirectEXT");
    }

    internal static void Unload()
    {
        _glMultiDrawElementsIndirectEXT = null;
        _glMultiDrawArraysIndirectEXT = null;
    }
    #endregion

    #region Function wrappers
    public static void glMultiDrawElementsIndirectEXT(uint mode, uint type, void* indirect, int drawcount, int stride) { QGLFeature.VerifyFunc((nint)_glMultiDrawElementsIndirectEXT); _glMultiDrawElementsIndirectEXT(mode, type, indirect, drawcount, stride); }
    public static void glMultiDrawArraysIndirectEXT(uint mode, void* indirect, int drawcount, int stride) { QGLFeature.VerifyFunc((nint)_glMultiDrawArraysIndirectEXT); _glMultiDrawArraysIndirectEXT(mode, indirect, drawcount, stride); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_multi_draw_indirect", true, true);
}
