// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
using System.Runtime.InteropServices;
using QuickGL.Internal;

namespace QuickGL.Bindings.Extensions;

public static unsafe class GLEXTfogcoord
{
    #region Constants
    public const int GL_FOG_COORDINATE_SOURCE_EXT = 0x00008450;
    public const int GL_FOG_COORDINATE_EXT = 0x00008451;
    public const int GL_FRAGMENT_DEPTH_EXT = 0x00008452;
    public const int GL_CURRENT_FOG_COORDINATE_EXT = 0x00008453;
    public const int GL_FOG_COORDINATE_ARRAY_TYPE_EXT = 0x00008454;
    public const int GL_FOG_COORDINATE_ARRAY_STRIDE_EXT = 0x00008455;
    public const int GL_FOG_COORDINATE_ARRAY_POINTER_EXT = 0x00008456;
    public const int GL_FOG_COORDINATE_ARRAY_EXT = 0x00008457;
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<float, void> _glFogCoordfEXT = null;
    internal static delegate* unmanaged<float*, void> _glFogCoordfvEXT = null;
    internal static delegate* unmanaged<double, void> _glFogCoorddEXT = null;
    internal static delegate* unmanaged<double*, void> _glFogCoorddvEXT = null;
    internal static delegate* unmanaged<uint, int, void*, void> _glFogCoordPointerEXT = null;

    internal static void Load()
    {
        _glFogCoordfEXT = (delegate* unmanaged<float, void>)QGL.GetGLProcAddress("glFogCoordfEXT");
        _glFogCoordfvEXT = (delegate* unmanaged<float*, void>)QGL.GetGLProcAddress("glFogCoordfvEXT");
        _glFogCoorddEXT = (delegate* unmanaged<double, void>)QGL.GetGLProcAddress("glFogCoorddEXT");
        _glFogCoorddvEXT = (delegate* unmanaged<double*, void>)QGL.GetGLProcAddress("glFogCoorddvEXT");
        _glFogCoordPointerEXT = (delegate* unmanaged<uint, int, void*, void>)QGL.GetGLProcAddress("glFogCoordPointerEXT");
    }

    internal static void Unload()
    {
        _glFogCoordfEXT = null;
        _glFogCoordfvEXT = null;
        _glFogCoorddEXT = null;
        _glFogCoorddvEXT = null;
        _glFogCoordPointerEXT = null;
    }
    #endregion

    #region Function wrappers
    public static void glFogCoordfEXT(float coord) { QGLFeature.VerifyFunc((nint)_glFogCoordfEXT); _glFogCoordfEXT(coord); }
    public static void glFogCoordfvEXT(float* coord) { QGLFeature.VerifyFunc((nint)_glFogCoordfvEXT); _glFogCoordfvEXT(coord); }
    public static void glFogCoorddEXT(double coord) { QGLFeature.VerifyFunc((nint)_glFogCoorddEXT); _glFogCoorddEXT(coord); }
    public static void glFogCoorddvEXT(double* coord) { QGLFeature.VerifyFunc((nint)_glFogCoorddvEXT); _glFogCoorddvEXT(coord); }
    public static void glFogCoordPointerEXT(uint type, int stride, void* pointer) { QGLFeature.VerifyFunc((nint)_glFogCoordPointerEXT); _glFogCoordPointerEXT(type, stride, pointer); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_fog_coord", true, false);
}
