// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:41:03.3071098Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTshaderframebufferfetchnoncoherent
{
    #region Constants
    public const int GL_FRAGMENT_SHADER_DISCARDS_SAMPLES_EXT = 0x00008A52;
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<void> _glFramebufferFetchBarrierEXT = null;

    internal static void Load()
    {
        _glFramebufferFetchBarrierEXT = (delegate* unmanaged<void>)QuickGL.GetGLProcAddress("glFramebufferFetchBarrierEXT");
    }

    internal static void Unload()
    {
        _glFramebufferFetchBarrierEXT = null;
    }
    #endregion

    #region Function wrappers
    public static void glFramebufferFetchBarrierEXT() { QGLFeature.VerifyFunc((nint)_glFramebufferFetchBarrierEXT); _glFramebufferFetchBarrierEXT(); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_shader_framebuffer_fetch_non_coherent", true, false);
}
