// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:00:37.9841878Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTcullvertex
{
    #region Constants
    public const int GL_CULL_VERTEX_OBJECT_POSITION_EXT = 0x000081AC;
    public const int GL_CULL_VERTEX_EYE_POSITION_EXT = 0x000081AB;
    public const int GL_CULL_VERTEX_EXT = 0x000081AA;
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, float*, void> _glCullParameterfvEXT = null;
    internal static delegate* unmanaged<uint, double*, void> _glCullParameterdvEXT = null;

    internal static void Load()
    {
        _glCullParameterfvEXT = (delegate* unmanaged<uint, float*, void>)QuickGL.GetGLProcAddress("glCullParameterfvEXT");
        _glCullParameterdvEXT = (delegate* unmanaged<uint, double*, void>)QuickGL.GetGLProcAddress("glCullParameterdvEXT");
    }

    internal static void Unload()
    {
        _glCullParameterfvEXT = null;
        _glCullParameterdvEXT = null;
    }
    #endregion

    #region Function wrappers
    public static void glCullParameterfvEXT(uint pname, float* @params) { QGLFeature.VerifyFunc((nint)_glCullParameterfvEXT); _glCullParameterfvEXT(pname, @params); }
    public static void glCullParameterdvEXT(uint pname, double* @params) { QGLFeature.VerifyFunc((nint)_glCullParameterdvEXT); _glCullParameterdvEXT(pname, @params); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_cull_vertex", true, false);
}
