// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:00:37.9466611Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTEGLimagestoragecompression
{
    #region Constants
    public const int GL_SURFACE_COMPRESSION_FIXED_RATE_NONE_EXT = 0x000096C1;
    public const int GL_SURFACE_COMPRESSION_FIXED_RATE_DEFAULT_EXT = 0x000096C2;
    public const int GL_SURFACE_COMPRESSION_EXT = 0x000096C0;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_EGL_image_storage_compression", true, true);
}
