// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
using System.Runtime.InteropServices;
using QuickGL.Internal;

namespace QuickGL.Bindings.Extensions;

public static unsafe class GLEXTdepthclamp
{
    #region Constants
    public const int GL_DEPTH_CLAMP_EXT = 0x0000864F;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_depth_clamp", true, true);
}
