// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
using System.Runtime.InteropServices;
using QuickGL.Internal;

namespace QuickGL.Bindings.Extensions;

public static unsafe class GLEXTmeshshader
{
    #region Constants
    public const int GL_MESH_SHADER_EXT = 0x00009559;
    public const int GL_TASK_SHADER_EXT = 0x0000955A;
    public const int GL_MAX_MESH_UNIFORM_BLOCKS_EXT = 0x00008E60;
    public const int GL_MAX_MESH_TEXTURE_IMAGE_UNITS_EXT = 0x00008E61;
    public const int GL_MAX_MESH_IMAGE_UNIFORMS_EXT = 0x00008E62;
    public const int GL_MAX_MESH_UNIFORM_COMPONENTS_EXT = 0x00008E63;
    public const int GL_MAX_MESH_ATOMIC_COUNTER_BUFFERS_EXT = 0x00008E64;
    public const int GL_MAX_MESH_ATOMIC_COUNTERS_EXT = 0x00008E65;
    public const int GL_MAX_MESH_SHADER_STORAGE_BLOCKS_EXT = 0x00008E66;
    public const int GL_MAX_COMBINED_MESH_UNIFORM_COMPONENTS_EXT = 0x00008E67;
    public const int GL_MAX_TASK_UNIFORM_BLOCKS_EXT = 0x00008E68;
    public const int GL_MAX_TASK_TEXTURE_IMAGE_UNITS_EXT = 0x00008E69;
    public const int GL_MAX_TASK_IMAGE_UNIFORMS_EXT = 0x00008E6A;
    public const int GL_MAX_TASK_UNIFORM_COMPONENTS_EXT = 0x00008E6B;
    public const int GL_MAX_TASK_ATOMIC_COUNTER_BUFFERS_EXT = 0x00008E6C;
    public const int GL_MAX_TASK_ATOMIC_COUNTERS_EXT = 0x00008E6D;
    public const int GL_MAX_TASK_SHADER_STORAGE_BLOCKS_EXT = 0x00008E6E;
    public const int GL_MAX_COMBINED_TASK_UNIFORM_COMPONENTS_EXT = 0x00008E6F;
    public const int GL_MAX_TASK_WORK_GROUP_TOTAL_COUNT_EXT = 0x00009740;
    public const int GL_MAX_MESH_WORK_GROUP_TOTAL_COUNT_EXT = 0x00009741;
    public const int GL_MAX_MESH_WORK_GROUP_INVOCATIONS_EXT = 0x00009757;
    public const int GL_MAX_TASK_WORK_GROUP_INVOCATIONS_EXT = 0x00009759;
    public const int GL_MAX_TASK_PAYLOAD_SIZE_EXT = 0x00009742;
    public const int GL_MAX_TASK_SHARED_MEMORY_SIZE_EXT = 0x00009743;
    public const int GL_MAX_MESH_SHARED_MEMORY_SIZE_EXT = 0x00009744;
    public const int GL_MAX_TASK_PAYLOAD_AND_SHARED_MEMORY_SIZE_EXT = 0x00009745;
    public const int GL_MAX_MESH_PAYLOAD_AND_SHARED_MEMORY_SIZE_EXT = 0x00009746;
    public const int GL_MAX_MESH_OUTPUT_MEMORY_SIZE_EXT = 0x00009747;
    public const int GL_MAX_MESH_PAYLOAD_AND_OUTPUT_MEMORY_SIZE_EXT = 0x00009748;
    public const int GL_MAX_MESH_OUTPUT_VERTICES_EXT = 0x00009538;
    public const int GL_MAX_MESH_OUTPUT_PRIMITIVES_EXT = 0x00009756;
    public const int GL_MAX_MESH_OUTPUT_COMPONENTS_EXT = 0x00009749;
    public const int GL_MAX_MESH_OUTPUT_LAYERS_EXT = 0x0000974A;
    public const int GL_MAX_MESH_MULTIVIEW_VIEW_COUNT_EXT = 0x00009557;
    public const int GL_MESH_OUTPUT_PER_VERTEX_GRANULARITY_EXT = 0x000092DF;
    public const int GL_MESH_OUTPUT_PER_PRIMITIVE_GRANULARITY_EXT = 0x00009543;
    public const int GL_MAX_PREFERRED_TASK_WORK_GROUP_INVOCATIONS_EXT = 0x0000974B;
    public const int GL_MAX_PREFERRED_MESH_WORK_GROUP_INVOCATIONS_EXT = 0x0000974C;
    public const int GL_MESH_PREFERS_LOCAL_INVOCATION_VERTEX_OUTPUT_EXT = 0x0000974D;
    public const int GL_MESH_PREFERS_LOCAL_INVOCATION_PRIMITIVE_OUTPUT_EXT = 0x0000974E;
    public const int GL_MESH_PREFERS_COMPACT_VERTEX_OUTPUT_EXT = 0x0000974F;
    public const int GL_MESH_PREFERS_COMPACT_PRIMITIVE_OUTPUT_EXT = 0x00009750;
    public const int GL_MAX_TASK_WORK_GROUP_COUNT_EXT = 0x00009751;
    public const int GL_MAX_MESH_WORK_GROUP_COUNT_EXT = 0x00009752;
    public const int GL_MAX_MESH_WORK_GROUP_SIZE_EXT = 0x00009758;
    public const int GL_MAX_TASK_WORK_GROUP_SIZE_EXT = 0x0000975A;
    public const int GL_MESH_WORK_GROUP_SIZE_EXT = 0x0000953E;
    public const int GL_TASK_WORK_GROUP_SIZE_EXT = 0x0000953F;
    public const int GL_MESH_VERTICES_OUT_EXT = 0x00009579;
    public const int GL_MESH_PRIMITIVES_OUT_EXT = 0x0000957A;
    public const int GL_MESH_OUTPUT_TYPE_EXT = 0x0000957B;
    public const int GL_UNIFORM_BLOCK_REFERENCED_BY_MESH_SHADER_EXT = 0x0000959C;
    public const int GL_UNIFORM_BLOCK_REFERENCED_BY_TASK_SHADER_EXT = 0x0000959D;
    public const int GL_REFERENCED_BY_MESH_SHADER_EXT = 0x000095A0;
    public const int GL_REFERENCED_BY_TASK_SHADER_EXT = 0x000095A1;
    public const int GL_TASK_SHADER_INVOCATIONS_EXT = 0x00009753;
    public const int GL_MESH_SHADER_INVOCATIONS_EXT = 0x00009754;
    public const int GL_MESH_PRIMITIVES_GENERATED_EXT = 0x00009755;
    public const int GL_MESH_SHADER_BIT_EXT = 0x00000040;
    public const int GL_TASK_SHADER_BIT_EXT = 0x00000080;
    public const int GL_MESH_SUBROUTINE_EXT = 0x0000957C;
    public const int GL_TASK_SUBROUTINE_EXT = 0x0000957D;
    public const int GL_MESH_SUBROUTINE_UNIFORM_EXT = 0x0000957E;
    public const int GL_TASK_SUBROUTINE_UNIFORM_EXT = 0x0000957F;
    public const int GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_MESH_SHADER_EXT = 0x0000959E;
    public const int GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TASK_SHADER_EXT = 0x0000959F;
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, uint, uint, void> _glDrawMeshTasksEXT = null;
    internal static delegate* unmanaged<nint, void> _glDrawMeshTasksIndirectEXT = null;
    internal static delegate* unmanaged<nint, int, int, void> _glMultiDrawMeshTasksIndirectEXT = null;
    internal static delegate* unmanaged<nint, nint, int, int, void> _glMultiDrawMeshTasksIndirectCountEXT = null;

    internal static void Load()
    {
        _glDrawMeshTasksEXT = (delegate* unmanaged<uint, uint, uint, void>)QGL.GetGLProcAddress("glDrawMeshTasksEXT");
        _glDrawMeshTasksIndirectEXT = (delegate* unmanaged<nint, void>)QGL.GetGLProcAddress("glDrawMeshTasksIndirectEXT");
        _glMultiDrawMeshTasksIndirectEXT = (delegate* unmanaged<nint, int, int, void>)QGL.GetGLProcAddress("glMultiDrawMeshTasksIndirectEXT");
        _glMultiDrawMeshTasksIndirectCountEXT = (delegate* unmanaged<nint, nint, int, int, void>)QGL.GetGLProcAddress("glMultiDrawMeshTasksIndirectCountEXT");
    }

    internal static void Unload()
    {
        _glDrawMeshTasksEXT = null;
        _glDrawMeshTasksIndirectEXT = null;
        _glMultiDrawMeshTasksIndirectEXT = null;
        _glMultiDrawMeshTasksIndirectCountEXT = null;
    }
    #endregion

    #region Function wrappers
    public static void glDrawMeshTasksEXT(uint num_groups_x, uint num_groups_y, uint num_groups_z) { QGLFeature.VerifyFunc((nint)_glDrawMeshTasksEXT); _glDrawMeshTasksEXT(num_groups_x, num_groups_y, num_groups_z); }
    public static void glDrawMeshTasksIndirectEXT(nint indirect) { QGLFeature.VerifyFunc((nint)_glDrawMeshTasksIndirectEXT); _glDrawMeshTasksIndirectEXT(indirect); }
    public static void glMultiDrawMeshTasksIndirectEXT(nint indirect, int drawcount, int stride) { QGLFeature.VerifyFunc((nint)_glMultiDrawMeshTasksIndirectEXT); _glMultiDrawMeshTasksIndirectEXT(indirect, drawcount, stride); }
    public static void glMultiDrawMeshTasksIndirectCountEXT(nint indirect, nint drawcount, int maxdrawcount, int stride) { QGLFeature.VerifyFunc((nint)_glMultiDrawMeshTasksIndirectCountEXT); _glMultiDrawMeshTasksIndirectCountEXT(indirect, drawcount, maxdrawcount, stride); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_mesh_shader", true, false);
}
