// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
using System.Runtime.InteropServices;
using QuickGL.Internal;

namespace QuickGL.Bindings.Extensions;

public static unsafe class GLEXTtexturefilterminmax
{
    #region Constants
    public const int GL_TEXTURE_REDUCTION_MODE_EXT = 0x00009366;
    public const int GL_WEIGHTED_AVERAGE_EXT = 0x00009367;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_texture_filter_minmax", true, false);
}
