// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T20:04:55.8839915Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTtexture
{
    #region Constants
    public const int GL_ALPHA4_EXT = 0x0000803B;
    public const int GL_ALPHA8_EXT = 0x0000803C;
    public const int GL_ALPHA12_EXT = 0x0000803D;
    public const int GL_ALPHA16_EXT = 0x0000803E;
    public const int GL_LUMINANCE4_EXT = 0x0000803F;
    public const int GL_LUMINANCE8_EXT = 0x00008040;
    public const int GL_LUMINANCE12_EXT = 0x00008041;
    public const int GL_LUMINANCE16_EXT = 0x00008042;
    public const int GL_LUMINANCE4_ALPHA4_EXT = 0x00008043;
    public const int GL_LUMINANCE6_ALPHA2_EXT = 0x00008044;
    public const int GL_LUMINANCE8_ALPHA8_EXT = 0x00008045;
    public const int GL_LUMINANCE12_ALPHA4_EXT = 0x00008046;
    public const int GL_LUMINANCE12_ALPHA12_EXT = 0x00008047;
    public const int GL_LUMINANCE16_ALPHA16_EXT = 0x00008048;
    public const int GL_INTENSITY_EXT = 0x00008049;
    public const int GL_INTENSITY4_EXT = 0x0000804A;
    public const int GL_INTENSITY8_EXT = 0x0000804B;
    public const int GL_INTENSITY12_EXT = 0x0000804C;
    public const int GL_INTENSITY16_EXT = 0x0000804D;
    public const int GL_RGB2_EXT = 0x0000804E;
    public const int GL_RGB4_EXT = 0x0000804F;
    public const int GL_RGB5_EXT = 0x00008050;
    public const int GL_RGB8_EXT = 0x00008051;
    public const int GL_RGB10_EXT = 0x00008052;
    public const int GL_RGB12_EXT = 0x00008053;
    public const int GL_RGB16_EXT = 0x00008054;
    public const int GL_RGBA2_EXT = 0x00008055;
    public const int GL_RGBA4_EXT = 0x00008056;
    public const int GL_RGB5_A1_EXT = 0x00008057;
    public const int GL_RGBA8_EXT = 0x00008058;
    public const int GL_RGB10_A2_EXT = 0x00008059;
    public const int GL_RGBA12_EXT = 0x0000805A;
    public const int GL_RGBA16_EXT = 0x0000805B;
    public const int GL_TEXTURE_RED_SIZE_EXT = 0x0000805C;
    public const int GL_TEXTURE_GREEN_SIZE_EXT = 0x0000805D;
    public const int GL_TEXTURE_BLUE_SIZE_EXT = 0x0000805E;
    public const int GL_TEXTURE_ALPHA_SIZE_EXT = 0x0000805F;
    public const int GL_TEXTURE_LUMINANCE_SIZE_EXT = 0x00008060;
    public const int GL_TEXTURE_INTENSITY_SIZE_EXT = 0x00008061;
    public const int GL_REPLACE_EXT = 0x00008062;
    public const int GL_PROXY_TEXTURE_1D_EXT = 0x00008063;
    public const int GL_PROXY_TEXTURE_2D_EXT = 0x00008064;
    public const int GL_TEXTURE_TOO_LARGE_EXT = 0x00008065;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_texture", true, false);
}
