// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:43:43.9125137Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTblendsubtract
{
    #region Constants
    public const int GL_FUNC_SUBTRACT_EXT = 0x0000800A;
    public const int GL_FUNC_REVERSE_SUBTRACT_EXT = 0x0000800B;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_blend_subtract", true, false);
}
