// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTindexarrayformats
{
    #region Constants
    public const int GL_IUI_V2F_EXT = 0x000081AD;
    public const int GL_IUI_V3F_EXT = 0x000081AE;
    public const int GL_IUI_N3F_V2F_EXT = 0x000081AF;
    public const int GL_IUI_N3F_V3F_EXT = 0x000081B0;
    public const int GL_T2F_IUI_V2F_EXT = 0x000081B1;
    public const int GL_T2F_IUI_V3F_EXT = 0x000081B2;
    public const int GL_T2F_IUI_N3F_V2F_EXT = 0x000081B3;
    public const int GL_T2F_IUI_N3F_V3F_EXT = 0x000081B4;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_index_array_formats", true, false);
}
