// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:43:44.0458964Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTtexturesharedexponent
{
    #region Constants
    public const int GL_RGB9_E5_EXT = 0x00008C3D;
    public const int GL_UNSIGNED_INT_5_9_9_9_REV_EXT = 0x00008C3E;
    public const int GL_TEXTURE_SHARED_SIZE_EXT = 0x00008C3F;
    #endregion

    #region Function pointers

    internal static void Load()
    {
    }

    internal static void Unload()
    {
    }
    #endregion

    #region Function wrappers
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_texture_shared_exponent", true, false);
}
