// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
using System.Runtime.InteropServices;
using QuickGL.Internal;

namespace QuickGL.Bindings.Extensions;

public static unsafe class GLEXTmemoryobjectfd
{
    #region Constants
    public const int GL_HANDLE_TYPE_OPAQUE_FD_EXT = 0x00009586;
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, ulong, uint, int, void> _glImportMemoryFdEXT = null;

    internal static void Load()
    {
        _glImportMemoryFdEXT = (delegate* unmanaged<uint, ulong, uint, int, void>)QGL.GetGLProcAddress("glImportMemoryFdEXT");
    }

    internal static void Unload()
    {
        _glImportMemoryFdEXT = null;
    }
    #endregion

    #region Function wrappers
    public static void glImportMemoryFdEXT(uint memory, ulong size, uint handleType, int fd) { QGLFeature.VerifyFunc((nint)_glImportMemoryFdEXT); _glImportMemoryFdEXT(memory, size, handleType, fd); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_memory_object_fd", true, false);
}
