// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:00:38.1762864Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTvertexweighting
{
    #region Constants
    public const int GL_VERTEX_WEIGHT_ARRAY_EXT = 0x0000850C;
    public const int GL_CURRENT_VERTEX_WEIGHT_EXT = 0x0000850B;
    public const int GL_VERTEX_WEIGHT_ARRAY_STRIDE_EXT = 0x0000850F;
    public const int GL_VERTEX_WEIGHT_ARRAY_TYPE_EXT = 0x0000850E;
    public const int GL_MODELVIEW1_EXT = 0x0000850A;
    public const int GL_MODELVIEW0_MATRIX_EXT = 0x00000BA6;
    public const int GL_VERTEX_WEIGHT_ARRAY_POINTER_EXT = 0x00008510;
    public const int GL_VERTEX_WEIGHT_ARRAY_SIZE_EXT = 0x0000850D;
    public const int GL_MODELVIEW0_EXT = 0x00001700;
    public const int GL_VERTEX_WEIGHTING_EXT = 0x00008509;
    public const int GL_MODELVIEW1_MATRIX_EXT = 0x00008506;
    public const int GL_MODELVIEW1_STACK_DEPTH_EXT = 0x00008502;
    public const int GL_MODELVIEW0_STACK_DEPTH_EXT = 0x00000BA3;
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<int, uint, int, void*, void> _glVertexWeightPointerEXT = null;
    internal static delegate* unmanaged<float*, void> _glVertexWeightfvEXT = null;
    internal static delegate* unmanaged<float, void> _glVertexWeightfEXT = null;

    internal static void Load()
    {
        _glVertexWeightPointerEXT = (delegate* unmanaged<int, uint, int, void*, void>)QuickGL.GetGLProcAddress("glVertexWeightPointerEXT");
        _glVertexWeightfvEXT = (delegate* unmanaged<float*, void>)QuickGL.GetGLProcAddress("glVertexWeightfvEXT");
        _glVertexWeightfEXT = (delegate* unmanaged<float, void>)QuickGL.GetGLProcAddress("glVertexWeightfEXT");
    }

    internal static void Unload()
    {
        _glVertexWeightPointerEXT = null;
        _glVertexWeightfvEXT = null;
        _glVertexWeightfEXT = null;
    }
    #endregion

    #region Function wrappers
    public static void glVertexWeightPointerEXT(int size, uint type, int stride, void* pointer) { QGLFeature.VerifyFunc((nint)_glVertexWeightPointerEXT); _glVertexWeightPointerEXT(size, type, stride, pointer); }
    public static void glVertexWeightfvEXT(float* weight) { QGLFeature.VerifyFunc((nint)_glVertexWeightfvEXT); _glVertexWeightfvEXT(weight); }
    public static void glVertexWeightfEXT(float weight) { QGLFeature.VerifyFunc((nint)_glVertexWeightfEXT); _glVertexWeightfEXT(weight); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_vertex_weighting", true, false);
}
