// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTmultiviewdrawbuffers
{
    #region Constants
    public const int GL_COLOR_ATTACHMENT_EXT = 0x000090F0;
    public const int GL_MULTIVIEW_EXT = 0x000090F1;
    public const int GL_DRAW_BUFFER_EXT = 0x00000C01;
    public const int GL_READ_BUFFER_EXT = 0x00000C02;
    public const int GL_MAX_MULTIVIEW_BUFFERS_EXT = 0x000090F2;
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, int, void> _glReadBufferIndexedEXT = null;
    internal static delegate* unmanaged<int, uint*, int*, void> _glDrawBuffersIndexedEXT = null;
    internal static delegate* unmanaged<uint, uint, int*, void> _glGetIntegeri_vEXT = null;

    internal static void Load()
    {
        _glReadBufferIndexedEXT = (delegate* unmanaged<uint, int, void>)QuickGL.GetGLProcAddress("glReadBufferIndexedEXT");
        _glDrawBuffersIndexedEXT = (delegate* unmanaged<int, uint*, int*, void>)QuickGL.GetGLProcAddress("glDrawBuffersIndexedEXT");
        _glGetIntegeri_vEXT = (delegate* unmanaged<uint, uint, int*, void>)QuickGL.GetGLProcAddress("glGetIntegeri_vEXT");
    }

    internal static void Unload()
    {
        _glReadBufferIndexedEXT = null;
        _glDrawBuffersIndexedEXT = null;
        _glGetIntegeri_vEXT = null;
    }
    #endregion

    #region Function wrappers
    public static void glReadBufferIndexedEXT(uint src, int index) { QGLFeature.VerifyFunc((nint)_glReadBufferIndexedEXT); _glReadBufferIndexedEXT(src, index); }
    public static void glDrawBuffersIndexedEXT(int n, uint* location, int* indices) { QGLFeature.VerifyFunc((nint)_glDrawBuffersIndexedEXT); _glDrawBuffersIndexedEXT(n, location, indices); }
    public static void glGetIntegeri_vEXT(uint target, uint index, int* data) { QGLFeature.VerifyFunc((nint)_glGetIntegeri_vEXT); _glGetIntegeri_vEXT(target, index, data); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_multiview_draw_buffers", true, true);
}
