// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:00:37.9838071Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTdiscardframebuffer
{
    #region Constants
    public const int GL_STENCIL_EXT = 0x00001802;
    public const int GL_DEPTH_EXT = 0x00001801;
    public const int GL_COLOR_EXT = 0x00001800;
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, int, uint*, void> _glDiscardFramebufferEXT = null;

    internal static void Load()
    {
        _glDiscardFramebufferEXT = (delegate* unmanaged<uint, int, uint*, void>)QuickGL.GetGLProcAddress("glDiscardFramebufferEXT");
    }

    internal static void Unload()
    {
        _glDiscardFramebufferEXT = null;
    }
    #endregion

    #region Function wrappers
    public static void glDiscardFramebufferEXT(uint target, int numAttachments, uint* attachments) { QGLFeature.VerifyFunc((nint)_glDiscardFramebufferEXT); _glDiscardFramebufferEXT(target, numAttachments, attachments); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_discard_framebuffer", true, true);
}
