// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTinstancedarrays
{
    #region Constants
    public const int GL_VERTEX_ATTRIB_ARRAY_DIVISOR_EXT = 0x000088FE;
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, int, int, int, void> _glDrawArraysInstancedEXT = null;
    internal static delegate* unmanaged<uint, int, uint, void*, int, void> _glDrawElementsInstancedEXT = null;
    internal static delegate* unmanaged<uint, uint, void> _glVertexAttribDivisorEXT = null;

    internal static void Load()
    {
        _glDrawArraysInstancedEXT = (delegate* unmanaged<uint, int, int, int, void>)QuickGL.GetGLProcAddress("glDrawArraysInstancedEXT");
        _glDrawElementsInstancedEXT = (delegate* unmanaged<uint, int, uint, void*, int, void>)QuickGL.GetGLProcAddress("glDrawElementsInstancedEXT");
        _glVertexAttribDivisorEXT = (delegate* unmanaged<uint, uint, void>)QuickGL.GetGLProcAddress("glVertexAttribDivisorEXT");
    }

    internal static void Unload()
    {
        _glDrawArraysInstancedEXT = null;
        _glDrawElementsInstancedEXT = null;
        _glVertexAttribDivisorEXT = null;
    }
    #endregion

    #region Function wrappers
    public static void glDrawArraysInstancedEXT(uint mode, int start, int count, int primcount) { QGLFeature.VerifyFunc((nint)_glDrawArraysInstancedEXT); _glDrawArraysInstancedEXT(mode, start, count, primcount); }
    public static void glDrawElementsInstancedEXT(uint mode, int count, uint type, void* indices, int primcount) { QGLFeature.VerifyFunc((nint)_glDrawElementsInstancedEXT); _glDrawElementsInstancedEXT(mode, count, type, indices, primcount); }
    public static void glVertexAttribDivisorEXT(uint index, uint divisor) { QGLFeature.VerifyFunc((nint)_glVertexAttribDivisorEXT); _glVertexAttribDivisorEXT(index, divisor); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_instanced_arrays", true, true);
}
