// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:00:38.0336250Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTmultisampledrendertotexture
{
    #region Constants
    public const int GL_MAX_SAMPLES_EXT = 0x00008D57;
    public const int GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_EXT = 0x00008D56;
    public const int GL_RENDERBUFFER_SAMPLES_EXT = 0x00008CAB;
    public const int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_SAMPLES_EXT = 0x00008D6C;
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, uint, uint, uint, int, int, void> _glFramebufferTexture2DMultisampleEXT = null;
    internal static delegate* unmanaged<uint, int, uint, int, int, void> _glRenderbufferStorageMultisampleEXT = null;

    internal static void Load()
    {
        _glFramebufferTexture2DMultisampleEXT = (delegate* unmanaged<uint, uint, uint, uint, int, int, void>)QuickGL.GetGLProcAddress("glFramebufferTexture2DMultisampleEXT");
        _glRenderbufferStorageMultisampleEXT = (delegate* unmanaged<uint, int, uint, int, int, void>)QuickGL.GetGLProcAddress("glRenderbufferStorageMultisampleEXT");
    }

    internal static void Unload()
    {
        _glFramebufferTexture2DMultisampleEXT = null;
        _glRenderbufferStorageMultisampleEXT = null;
    }
    #endregion

    #region Function wrappers
    public static void glFramebufferTexture2DMultisampleEXT(uint target, uint attachment, uint textarget, uint texture, int level, int samples) { QGLFeature.VerifyFunc((nint)_glFramebufferTexture2DMultisampleEXT); _glFramebufferTexture2DMultisampleEXT(target, attachment, textarget, texture, level, samples); }
    public static void glRenderbufferStorageMultisampleEXT(uint target, int samples, uint internalformat, int width, int height) { QGLFeature.VerifyFunc((nint)_glRenderbufferStorageMultisampleEXT); _glRenderbufferStorageMultisampleEXT(target, samples, internalformat, width, height); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_multisampled_render_to_texture", true, true);
}
