// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
// Generated at: 2025-09-27T19:00:37.9462462Z
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTEGLimagestorage
{
    #region Constants
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, nint, int*, void> _glEGLImageTargetTexStorageEXT = null;
    internal static delegate* unmanaged<uint, nint, int*, void> _glEGLImageTargetTextureStorageEXT = null;

    internal static void Load()
    {
        _glEGLImageTargetTexStorageEXT = (delegate* unmanaged<uint, nint, int*, void>)QuickGL.GetGLProcAddress("glEGLImageTargetTexStorageEXT");
        _glEGLImageTargetTextureStorageEXT = (delegate* unmanaged<uint, nint, int*, void>)QuickGL.GetGLProcAddress("glEGLImageTargetTextureStorageEXT");
    }

    internal static void Unload()
    {
        _glEGLImageTargetTexStorageEXT = null;
        _glEGLImageTargetTextureStorageEXT = null;
    }
    #endregion

    #region Function wrappers
    public static void glEGLImageTargetTexStorageEXT(uint target, nint image, int* attrib_list) { QGLFeature.VerifyFunc((nint)_glEGLImageTargetTexStorageEXT); _glEGLImageTargetTexStorageEXT(target, image, attrib_list); }
    public static void glEGLImageTargetTextureStorageEXT(uint texture, nint image, int* attrib_list) { QGLFeature.VerifyFunc((nint)_glEGLImageTargetTextureStorageEXT); _glEGLImageTargetTextureStorageEXT(texture, image, attrib_list); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_EGL_image_storage", true, false);
}
