// This file has been automatically generated
// Generated by: QGLBindingsGen (https://github.com/vlOd2/QGLBindingsGen)
using System.Runtime.InteropServices;
using QuickGLNS.Internal;

namespace QuickGLNS.Bindings.Extensions;

public static unsafe class GLEXTseparateshaderobjects
{
    #region Constants
    public const int GL_ACTIVE_PROGRAM_EXT = 0x00008259;
    public const int GL_VERTEX_SHADER_BIT_EXT = 0x00000001;
    public const int GL_FRAGMENT_SHADER_BIT_EXT = 0x00000002;
    public const uint GL_ALL_SHADER_BITS_EXT = 0xFFFFFFFFU;
    public const int GL_PROGRAM_SEPARABLE_EXT = 0x00008258;
    public const int GL_PROGRAM_PIPELINE_BINDING_EXT = 0x0000825A;
    #endregion

    #region Function pointers
    internal static delegate* unmanaged<uint, uint, void> _glUseShaderProgramEXT = null;
    internal static delegate* unmanaged<uint, void> _glActiveProgramEXT = null;
    internal static delegate* unmanaged<uint, byte*, uint> _glCreateShaderProgramEXT = null;
    internal static delegate* unmanaged<uint, uint, void> _glActiveShaderProgramEXT = null;
    internal static delegate* unmanaged<uint, void> _glBindProgramPipelineEXT = null;
    internal static delegate* unmanaged<uint, int, byte**, uint> _glCreateShaderProgramvEXT = null;
    internal static delegate* unmanaged<int, uint*, void> _glDeleteProgramPipelinesEXT = null;
    internal static delegate* unmanaged<int, uint*, void> _glGenProgramPipelinesEXT = null;
    internal static delegate* unmanaged<uint, int, int*, byte*, void> _glGetProgramPipelineInfoLogEXT = null;
    internal static delegate* unmanaged<uint, uint, int*, void> _glGetProgramPipelineivEXT = null;
    internal static delegate* unmanaged<uint, bool> _glIsProgramPipelineEXT = null;
    internal static delegate* unmanaged<uint, uint, int, void> _glProgramParameteriEXT = null;
    internal static delegate* unmanaged<uint, int, float, void> _glProgramUniform1fEXT = null;
    internal static delegate* unmanaged<uint, int, int, float*, void> _glProgramUniform1fvEXT = null;
    internal static delegate* unmanaged<uint, int, int, void> _glProgramUniform1iEXT = null;
    internal static delegate* unmanaged<uint, int, int, int*, void> _glProgramUniform1ivEXT = null;
    internal static delegate* unmanaged<uint, int, float, float, void> _glProgramUniform2fEXT = null;
    internal static delegate* unmanaged<uint, int, int, float*, void> _glProgramUniform2fvEXT = null;
    internal static delegate* unmanaged<uint, int, int, int, void> _glProgramUniform2iEXT = null;
    internal static delegate* unmanaged<uint, int, int, int*, void> _glProgramUniform2ivEXT = null;
    internal static delegate* unmanaged<uint, int, float, float, float, void> _glProgramUniform3fEXT = null;
    internal static delegate* unmanaged<uint, int, int, float*, void> _glProgramUniform3fvEXT = null;
    internal static delegate* unmanaged<uint, int, int, int, int, void> _glProgramUniform3iEXT = null;
    internal static delegate* unmanaged<uint, int, int, int*, void> _glProgramUniform3ivEXT = null;
    internal static delegate* unmanaged<uint, int, float, float, float, float, void> _glProgramUniform4fEXT = null;
    internal static delegate* unmanaged<uint, int, int, float*, void> _glProgramUniform4fvEXT = null;
    internal static delegate* unmanaged<uint, int, int, int, int, int, void> _glProgramUniform4iEXT = null;
    internal static delegate* unmanaged<uint, int, int, int*, void> _glProgramUniform4ivEXT = null;
    internal static delegate* unmanaged<uint, int, int, bool, float*, void> _glProgramUniformMatrix2fvEXT = null;
    internal static delegate* unmanaged<uint, int, int, bool, float*, void> _glProgramUniformMatrix3fvEXT = null;
    internal static delegate* unmanaged<uint, int, int, bool, float*, void> _glProgramUniformMatrix4fvEXT = null;
    internal static delegate* unmanaged<uint, uint, uint, void> _glUseProgramStagesEXT = null;
    internal static delegate* unmanaged<uint, void> _glValidateProgramPipelineEXT = null;
    internal static delegate* unmanaged<uint, int, uint, void> _glProgramUniform1uiEXT = null;
    internal static delegate* unmanaged<uint, int, uint, uint, void> _glProgramUniform2uiEXT = null;
    internal static delegate* unmanaged<uint, int, uint, uint, uint, void> _glProgramUniform3uiEXT = null;
    internal static delegate* unmanaged<uint, int, uint, uint, uint, uint, void> _glProgramUniform4uiEXT = null;
    internal static delegate* unmanaged<uint, int, int, uint*, void> _glProgramUniform1uivEXT = null;
    internal static delegate* unmanaged<uint, int, int, uint*, void> _glProgramUniform2uivEXT = null;
    internal static delegate* unmanaged<uint, int, int, uint*, void> _glProgramUniform3uivEXT = null;
    internal static delegate* unmanaged<uint, int, int, uint*, void> _glProgramUniform4uivEXT = null;
    internal static delegate* unmanaged<uint, int, int, bool, float*, void> _glProgramUniformMatrix2x3fvEXT = null;
    internal static delegate* unmanaged<uint, int, int, bool, float*, void> _glProgramUniformMatrix3x2fvEXT = null;
    internal static delegate* unmanaged<uint, int, int, bool, float*, void> _glProgramUniformMatrix2x4fvEXT = null;
    internal static delegate* unmanaged<uint, int, int, bool, float*, void> _glProgramUniformMatrix4x2fvEXT = null;
    internal static delegate* unmanaged<uint, int, int, bool, float*, void> _glProgramUniformMatrix3x4fvEXT = null;
    internal static delegate* unmanaged<uint, int, int, bool, float*, void> _glProgramUniformMatrix4x3fvEXT = null;

    internal static void Load()
    {
        _glUseShaderProgramEXT = (delegate* unmanaged<uint, uint, void>)QuickGL.GetGLProcAddress("glUseShaderProgramEXT");
        _glActiveProgramEXT = (delegate* unmanaged<uint, void>)QuickGL.GetGLProcAddress("glActiveProgramEXT");
        _glCreateShaderProgramEXT = (delegate* unmanaged<uint, byte*, uint>)QuickGL.GetGLProcAddress("glCreateShaderProgramEXT");
        _glActiveShaderProgramEXT = (delegate* unmanaged<uint, uint, void>)QuickGL.GetGLProcAddress("glActiveShaderProgramEXT");
        _glBindProgramPipelineEXT = (delegate* unmanaged<uint, void>)QuickGL.GetGLProcAddress("glBindProgramPipelineEXT");
        _glCreateShaderProgramvEXT = (delegate* unmanaged<uint, int, byte**, uint>)QuickGL.GetGLProcAddress("glCreateShaderProgramvEXT");
        _glDeleteProgramPipelinesEXT = (delegate* unmanaged<int, uint*, void>)QuickGL.GetGLProcAddress("glDeleteProgramPipelinesEXT");
        _glGenProgramPipelinesEXT = (delegate* unmanaged<int, uint*, void>)QuickGL.GetGLProcAddress("glGenProgramPipelinesEXT");
        _glGetProgramPipelineInfoLogEXT = (delegate* unmanaged<uint, int, int*, byte*, void>)QuickGL.GetGLProcAddress("glGetProgramPipelineInfoLogEXT");
        _glGetProgramPipelineivEXT = (delegate* unmanaged<uint, uint, int*, void>)QuickGL.GetGLProcAddress("glGetProgramPipelineivEXT");
        _glIsProgramPipelineEXT = (delegate* unmanaged<uint, bool>)QuickGL.GetGLProcAddress("glIsProgramPipelineEXT");
        _glProgramParameteriEXT = (delegate* unmanaged<uint, uint, int, void>)QuickGL.GetGLProcAddress("glProgramParameteriEXT");
        _glProgramUniform1fEXT = (delegate* unmanaged<uint, int, float, void>)QuickGL.GetGLProcAddress("glProgramUniform1fEXT");
        _glProgramUniform1fvEXT = (delegate* unmanaged<uint, int, int, float*, void>)QuickGL.GetGLProcAddress("glProgramUniform1fvEXT");
        _glProgramUniform1iEXT = (delegate* unmanaged<uint, int, int, void>)QuickGL.GetGLProcAddress("glProgramUniform1iEXT");
        _glProgramUniform1ivEXT = (delegate* unmanaged<uint, int, int, int*, void>)QuickGL.GetGLProcAddress("glProgramUniform1ivEXT");
        _glProgramUniform2fEXT = (delegate* unmanaged<uint, int, float, float, void>)QuickGL.GetGLProcAddress("glProgramUniform2fEXT");
        _glProgramUniform2fvEXT = (delegate* unmanaged<uint, int, int, float*, void>)QuickGL.GetGLProcAddress("glProgramUniform2fvEXT");
        _glProgramUniform2iEXT = (delegate* unmanaged<uint, int, int, int, void>)QuickGL.GetGLProcAddress("glProgramUniform2iEXT");
        _glProgramUniform2ivEXT = (delegate* unmanaged<uint, int, int, int*, void>)QuickGL.GetGLProcAddress("glProgramUniform2ivEXT");
        _glProgramUniform3fEXT = (delegate* unmanaged<uint, int, float, float, float, void>)QuickGL.GetGLProcAddress("glProgramUniform3fEXT");
        _glProgramUniform3fvEXT = (delegate* unmanaged<uint, int, int, float*, void>)QuickGL.GetGLProcAddress("glProgramUniform3fvEXT");
        _glProgramUniform3iEXT = (delegate* unmanaged<uint, int, int, int, int, void>)QuickGL.GetGLProcAddress("glProgramUniform3iEXT");
        _glProgramUniform3ivEXT = (delegate* unmanaged<uint, int, int, int*, void>)QuickGL.GetGLProcAddress("glProgramUniform3ivEXT");
        _glProgramUniform4fEXT = (delegate* unmanaged<uint, int, float, float, float, float, void>)QuickGL.GetGLProcAddress("glProgramUniform4fEXT");
        _glProgramUniform4fvEXT = (delegate* unmanaged<uint, int, int, float*, void>)QuickGL.GetGLProcAddress("glProgramUniform4fvEXT");
        _glProgramUniform4iEXT = (delegate* unmanaged<uint, int, int, int, int, int, void>)QuickGL.GetGLProcAddress("glProgramUniform4iEXT");
        _glProgramUniform4ivEXT = (delegate* unmanaged<uint, int, int, int*, void>)QuickGL.GetGLProcAddress("glProgramUniform4ivEXT");
        _glProgramUniformMatrix2fvEXT = (delegate* unmanaged<uint, int, int, bool, float*, void>)QuickGL.GetGLProcAddress("glProgramUniformMatrix2fvEXT");
        _glProgramUniformMatrix3fvEXT = (delegate* unmanaged<uint, int, int, bool, float*, void>)QuickGL.GetGLProcAddress("glProgramUniformMatrix3fvEXT");
        _glProgramUniformMatrix4fvEXT = (delegate* unmanaged<uint, int, int, bool, float*, void>)QuickGL.GetGLProcAddress("glProgramUniformMatrix4fvEXT");
        _glUseProgramStagesEXT = (delegate* unmanaged<uint, uint, uint, void>)QuickGL.GetGLProcAddress("glUseProgramStagesEXT");
        _glValidateProgramPipelineEXT = (delegate* unmanaged<uint, void>)QuickGL.GetGLProcAddress("glValidateProgramPipelineEXT");
        _glProgramUniform1uiEXT = (delegate* unmanaged<uint, int, uint, void>)QuickGL.GetGLProcAddress("glProgramUniform1uiEXT");
        _glProgramUniform2uiEXT = (delegate* unmanaged<uint, int, uint, uint, void>)QuickGL.GetGLProcAddress("glProgramUniform2uiEXT");
        _glProgramUniform3uiEXT = (delegate* unmanaged<uint, int, uint, uint, uint, void>)QuickGL.GetGLProcAddress("glProgramUniform3uiEXT");
        _glProgramUniform4uiEXT = (delegate* unmanaged<uint, int, uint, uint, uint, uint, void>)QuickGL.GetGLProcAddress("glProgramUniform4uiEXT");
        _glProgramUniform1uivEXT = (delegate* unmanaged<uint, int, int, uint*, void>)QuickGL.GetGLProcAddress("glProgramUniform1uivEXT");
        _glProgramUniform2uivEXT = (delegate* unmanaged<uint, int, int, uint*, void>)QuickGL.GetGLProcAddress("glProgramUniform2uivEXT");
        _glProgramUniform3uivEXT = (delegate* unmanaged<uint, int, int, uint*, void>)QuickGL.GetGLProcAddress("glProgramUniform3uivEXT");
        _glProgramUniform4uivEXT = (delegate* unmanaged<uint, int, int, uint*, void>)QuickGL.GetGLProcAddress("glProgramUniform4uivEXT");
        _glProgramUniformMatrix2x3fvEXT = (delegate* unmanaged<uint, int, int, bool, float*, void>)QuickGL.GetGLProcAddress("glProgramUniformMatrix2x3fvEXT");
        _glProgramUniformMatrix3x2fvEXT = (delegate* unmanaged<uint, int, int, bool, float*, void>)QuickGL.GetGLProcAddress("glProgramUniformMatrix3x2fvEXT");
        _glProgramUniformMatrix2x4fvEXT = (delegate* unmanaged<uint, int, int, bool, float*, void>)QuickGL.GetGLProcAddress("glProgramUniformMatrix2x4fvEXT");
        _glProgramUniformMatrix4x2fvEXT = (delegate* unmanaged<uint, int, int, bool, float*, void>)QuickGL.GetGLProcAddress("glProgramUniformMatrix4x2fvEXT");
        _glProgramUniformMatrix3x4fvEXT = (delegate* unmanaged<uint, int, int, bool, float*, void>)QuickGL.GetGLProcAddress("glProgramUniformMatrix3x4fvEXT");
        _glProgramUniformMatrix4x3fvEXT = (delegate* unmanaged<uint, int, int, bool, float*, void>)QuickGL.GetGLProcAddress("glProgramUniformMatrix4x3fvEXT");
    }

    internal static void Unload()
    {
        _glUseShaderProgramEXT = null;
        _glActiveProgramEXT = null;
        _glCreateShaderProgramEXT = null;
        _glActiveShaderProgramEXT = null;
        _glBindProgramPipelineEXT = null;
        _glCreateShaderProgramvEXT = null;
        _glDeleteProgramPipelinesEXT = null;
        _glGenProgramPipelinesEXT = null;
        _glGetProgramPipelineInfoLogEXT = null;
        _glGetProgramPipelineivEXT = null;
        _glIsProgramPipelineEXT = null;
        _glProgramParameteriEXT = null;
        _glProgramUniform1fEXT = null;
        _glProgramUniform1fvEXT = null;
        _glProgramUniform1iEXT = null;
        _glProgramUniform1ivEXT = null;
        _glProgramUniform2fEXT = null;
        _glProgramUniform2fvEXT = null;
        _glProgramUniform2iEXT = null;
        _glProgramUniform2ivEXT = null;
        _glProgramUniform3fEXT = null;
        _glProgramUniform3fvEXT = null;
        _glProgramUniform3iEXT = null;
        _glProgramUniform3ivEXT = null;
        _glProgramUniform4fEXT = null;
        _glProgramUniform4fvEXT = null;
        _glProgramUniform4iEXT = null;
        _glProgramUniform4ivEXT = null;
        _glProgramUniformMatrix2fvEXT = null;
        _glProgramUniformMatrix3fvEXT = null;
        _glProgramUniformMatrix4fvEXT = null;
        _glUseProgramStagesEXT = null;
        _glValidateProgramPipelineEXT = null;
        _glProgramUniform1uiEXT = null;
        _glProgramUniform2uiEXT = null;
        _glProgramUniform3uiEXT = null;
        _glProgramUniform4uiEXT = null;
        _glProgramUniform1uivEXT = null;
        _glProgramUniform2uivEXT = null;
        _glProgramUniform3uivEXT = null;
        _glProgramUniform4uivEXT = null;
        _glProgramUniformMatrix2x3fvEXT = null;
        _glProgramUniformMatrix3x2fvEXT = null;
        _glProgramUniformMatrix2x4fvEXT = null;
        _glProgramUniformMatrix4x2fvEXT = null;
        _glProgramUniformMatrix3x4fvEXT = null;
        _glProgramUniformMatrix4x3fvEXT = null;
    }
    #endregion

    #region Function wrappers
    public static void glUseShaderProgramEXT(uint type, uint program) { QGLFeature.VerifyFunc((nint)_glUseShaderProgramEXT); _glUseShaderProgramEXT(type, program); }
    public static void glActiveProgramEXT(uint program) { QGLFeature.VerifyFunc((nint)_glActiveProgramEXT); _glActiveProgramEXT(program); }
    public static uint glCreateShaderProgramEXT(uint type, byte* @string) { QGLFeature.VerifyFunc((nint)_glCreateShaderProgramEXT); return _glCreateShaderProgramEXT(type, @string); }
    public static void glActiveShaderProgramEXT(uint pipeline, uint program) { QGLFeature.VerifyFunc((nint)_glActiveShaderProgramEXT); _glActiveShaderProgramEXT(pipeline, program); }
    public static void glBindProgramPipelineEXT(uint pipeline) { QGLFeature.VerifyFunc((nint)_glBindProgramPipelineEXT); _glBindProgramPipelineEXT(pipeline); }
    public static uint glCreateShaderProgramvEXT(uint type, int count, byte** strings) { QGLFeature.VerifyFunc((nint)_glCreateShaderProgramvEXT); return _glCreateShaderProgramvEXT(type, count, strings); }
    public static void glDeleteProgramPipelinesEXT(int n, uint* pipelines) { QGLFeature.VerifyFunc((nint)_glDeleteProgramPipelinesEXT); _glDeleteProgramPipelinesEXT(n, pipelines); }
    public static void glGenProgramPipelinesEXT(int n, uint* pipelines) { QGLFeature.VerifyFunc((nint)_glGenProgramPipelinesEXT); _glGenProgramPipelinesEXT(n, pipelines); }
    public static void glGetProgramPipelineInfoLogEXT(uint pipeline, int bufSize, int* length, byte* infoLog) { QGLFeature.VerifyFunc((nint)_glGetProgramPipelineInfoLogEXT); _glGetProgramPipelineInfoLogEXT(pipeline, bufSize, length, infoLog); }
    public static void glGetProgramPipelineivEXT(uint pipeline, uint pname, int* @params) { QGLFeature.VerifyFunc((nint)_glGetProgramPipelineivEXT); _glGetProgramPipelineivEXT(pipeline, pname, @params); }
    public static bool glIsProgramPipelineEXT(uint pipeline) { QGLFeature.VerifyFunc((nint)_glIsProgramPipelineEXT); return _glIsProgramPipelineEXT(pipeline); }
    public static void glProgramParameteriEXT(uint program, uint pname, int value) { QGLFeature.VerifyFunc((nint)_glProgramParameteriEXT); _glProgramParameteriEXT(program, pname, value); }
    public static void glProgramUniform1fEXT(uint program, int location, float v0) { QGLFeature.VerifyFunc((nint)_glProgramUniform1fEXT); _glProgramUniform1fEXT(program, location, v0); }
    public static void glProgramUniform1fvEXT(uint program, int location, int count, float* value) { QGLFeature.VerifyFunc((nint)_glProgramUniform1fvEXT); _glProgramUniform1fvEXT(program, location, count, value); }
    public static void glProgramUniform1iEXT(uint program, int location, int v0) { QGLFeature.VerifyFunc((nint)_glProgramUniform1iEXT); _glProgramUniform1iEXT(program, location, v0); }
    public static void glProgramUniform1ivEXT(uint program, int location, int count, int* value) { QGLFeature.VerifyFunc((nint)_glProgramUniform1ivEXT); _glProgramUniform1ivEXT(program, location, count, value); }
    public static void glProgramUniform2fEXT(uint program, int location, float v0, float v1) { QGLFeature.VerifyFunc((nint)_glProgramUniform2fEXT); _glProgramUniform2fEXT(program, location, v0, v1); }
    public static void glProgramUniform2fvEXT(uint program, int location, int count, float* value) { QGLFeature.VerifyFunc((nint)_glProgramUniform2fvEXT); _glProgramUniform2fvEXT(program, location, count, value); }
    public static void glProgramUniform2iEXT(uint program, int location, int v0, int v1) { QGLFeature.VerifyFunc((nint)_glProgramUniform2iEXT); _glProgramUniform2iEXT(program, location, v0, v1); }
    public static void glProgramUniform2ivEXT(uint program, int location, int count, int* value) { QGLFeature.VerifyFunc((nint)_glProgramUniform2ivEXT); _glProgramUniform2ivEXT(program, location, count, value); }
    public static void glProgramUniform3fEXT(uint program, int location, float v0, float v1, float v2) { QGLFeature.VerifyFunc((nint)_glProgramUniform3fEXT); _glProgramUniform3fEXT(program, location, v0, v1, v2); }
    public static void glProgramUniform3fvEXT(uint program, int location, int count, float* value) { QGLFeature.VerifyFunc((nint)_glProgramUniform3fvEXT); _glProgramUniform3fvEXT(program, location, count, value); }
    public static void glProgramUniform3iEXT(uint program, int location, int v0, int v1, int v2) { QGLFeature.VerifyFunc((nint)_glProgramUniform3iEXT); _glProgramUniform3iEXT(program, location, v0, v1, v2); }
    public static void glProgramUniform3ivEXT(uint program, int location, int count, int* value) { QGLFeature.VerifyFunc((nint)_glProgramUniform3ivEXT); _glProgramUniform3ivEXT(program, location, count, value); }
    public static void glProgramUniform4fEXT(uint program, int location, float v0, float v1, float v2, float v3) { QGLFeature.VerifyFunc((nint)_glProgramUniform4fEXT); _glProgramUniform4fEXT(program, location, v0, v1, v2, v3); }
    public static void glProgramUniform4fvEXT(uint program, int location, int count, float* value) { QGLFeature.VerifyFunc((nint)_glProgramUniform4fvEXT); _glProgramUniform4fvEXT(program, location, count, value); }
    public static void glProgramUniform4iEXT(uint program, int location, int v0, int v1, int v2, int v3) { QGLFeature.VerifyFunc((nint)_glProgramUniform4iEXT); _glProgramUniform4iEXT(program, location, v0, v1, v2, v3); }
    public static void glProgramUniform4ivEXT(uint program, int location, int count, int* value) { QGLFeature.VerifyFunc((nint)_glProgramUniform4ivEXT); _glProgramUniform4ivEXT(program, location, count, value); }
    public static void glProgramUniformMatrix2fvEXT(uint program, int location, int count, bool transpose, float* value) { QGLFeature.VerifyFunc((nint)_glProgramUniformMatrix2fvEXT); _glProgramUniformMatrix2fvEXT(program, location, count, transpose, value); }
    public static void glProgramUniformMatrix3fvEXT(uint program, int location, int count, bool transpose, float* value) { QGLFeature.VerifyFunc((nint)_glProgramUniformMatrix3fvEXT); _glProgramUniformMatrix3fvEXT(program, location, count, transpose, value); }
    public static void glProgramUniformMatrix4fvEXT(uint program, int location, int count, bool transpose, float* value) { QGLFeature.VerifyFunc((nint)_glProgramUniformMatrix4fvEXT); _glProgramUniformMatrix4fvEXT(program, location, count, transpose, value); }
    public static void glUseProgramStagesEXT(uint pipeline, uint stages, uint program) { QGLFeature.VerifyFunc((nint)_glUseProgramStagesEXT); _glUseProgramStagesEXT(pipeline, stages, program); }
    public static void glValidateProgramPipelineEXT(uint pipeline) { QGLFeature.VerifyFunc((nint)_glValidateProgramPipelineEXT); _glValidateProgramPipelineEXT(pipeline); }
    public static void glProgramUniform1uiEXT(uint program, int location, uint v0) { QGLFeature.VerifyFunc((nint)_glProgramUniform1uiEXT); _glProgramUniform1uiEXT(program, location, v0); }
    public static void glProgramUniform2uiEXT(uint program, int location, uint v0, uint v1) { QGLFeature.VerifyFunc((nint)_glProgramUniform2uiEXT); _glProgramUniform2uiEXT(program, location, v0, v1); }
    public static void glProgramUniform3uiEXT(uint program, int location, uint v0, uint v1, uint v2) { QGLFeature.VerifyFunc((nint)_glProgramUniform3uiEXT); _glProgramUniform3uiEXT(program, location, v0, v1, v2); }
    public static void glProgramUniform4uiEXT(uint program, int location, uint v0, uint v1, uint v2, uint v3) { QGLFeature.VerifyFunc((nint)_glProgramUniform4uiEXT); _glProgramUniform4uiEXT(program, location, v0, v1, v2, v3); }
    public static void glProgramUniform1uivEXT(uint program, int location, int count, uint* value) { QGLFeature.VerifyFunc((nint)_glProgramUniform1uivEXT); _glProgramUniform1uivEXT(program, location, count, value); }
    public static void glProgramUniform2uivEXT(uint program, int location, int count, uint* value) { QGLFeature.VerifyFunc((nint)_glProgramUniform2uivEXT); _glProgramUniform2uivEXT(program, location, count, value); }
    public static void glProgramUniform3uivEXT(uint program, int location, int count, uint* value) { QGLFeature.VerifyFunc((nint)_glProgramUniform3uivEXT); _glProgramUniform3uivEXT(program, location, count, value); }
    public static void glProgramUniform4uivEXT(uint program, int location, int count, uint* value) { QGLFeature.VerifyFunc((nint)_glProgramUniform4uivEXT); _glProgramUniform4uivEXT(program, location, count, value); }
    public static void glProgramUniformMatrix2x3fvEXT(uint program, int location, int count, bool transpose, float* value) { QGLFeature.VerifyFunc((nint)_glProgramUniformMatrix2x3fvEXT); _glProgramUniformMatrix2x3fvEXT(program, location, count, transpose, value); }
    public static void glProgramUniformMatrix3x2fvEXT(uint program, int location, int count, bool transpose, float* value) { QGLFeature.VerifyFunc((nint)_glProgramUniformMatrix3x2fvEXT); _glProgramUniformMatrix3x2fvEXT(program, location, count, transpose, value); }
    public static void glProgramUniformMatrix2x4fvEXT(uint program, int location, int count, bool transpose, float* value) { QGLFeature.VerifyFunc((nint)_glProgramUniformMatrix2x4fvEXT); _glProgramUniformMatrix2x4fvEXT(program, location, count, transpose, value); }
    public static void glProgramUniformMatrix4x2fvEXT(uint program, int location, int count, bool transpose, float* value) { QGLFeature.VerifyFunc((nint)_glProgramUniformMatrix4x2fvEXT); _glProgramUniformMatrix4x2fvEXT(program, location, count, transpose, value); }
    public static void glProgramUniformMatrix3x4fvEXT(uint program, int location, int count, bool transpose, float* value) { QGLFeature.VerifyFunc((nint)_glProgramUniformMatrix3x4fvEXT); _glProgramUniformMatrix3x4fvEXT(program, location, count, transpose, value); }
    public static void glProgramUniformMatrix4x3fvEXT(uint program, int location, int count, bool transpose, float* value) { QGLFeature.VerifyFunc((nint)_glProgramUniformMatrix4x3fvEXT); _glProgramUniformMatrix4x3fvEXT(program, location, count, transpose, value); }
    #endregion

    internal static QGLFeature FeatureInfo => new("GL_EXT_separate_shader_objects", true, false);
}
